### ISSUE TITLE
having duplication in the added libraries to the generated code

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#1011]
Consider the following example:
```
class PaperDistribution{
  depend java.util.*; 
  String[] data;
}
```
In the generated code, we will have two times the library `import java.util.*` imported.
These cases must be detected and one time the library needs to be added.

**Comment by TimLethbridge** [comment]
One depend is created by default; the other is created by the depend. When depend is used, there should be a check to see if it is going to be created by default anywhere. Alternatively the code generator should look for duplicates before outputting.

**Comment by BernardYuan** [comment]
After having Umple Release 1.27 I found the behavior of this issue has changed. It seems that there are no dependencies added by default in the newer version release. Example:
1. With dependencies input:
`class SomeTest{
    depend a.b.c;
    sth;
}`
 The output imports are:
`import a.b.c;`
2. With no dependency input there will be no imports generated at all.

I would suggest closing this issue and open another one, depending on whether it is Umple's responsibility to by default provide necessary dependencies such as java.util.*.

**Comment by TimLethbridge** [comment]
@BernardYuan No the issue still is a problem. Try the original case where the attribute is String[] data;
Your test in the last comment doesn't have the []
