### ISSUE TITLE
Allow multiple variable modifiers

### ISSUE THREAD

**Issue by AdamBJ** [umple/umple#1012]
## Brief Description

Consider the following Umple class:

```
class Hi {
  internal const String console = "";
}
```

I want Umple to generate a `private static String` for me. However, I can only choose `internal` or `const`, not both. Therefore, the only way to get a `private static` string is to hardcode it and have Umple consider it extra code.

## Minimum Steps to Reproduce

Put the provided snippet into UmpleOnline

**Comment by TimLethbridge** [comment]
Fixed by PR #1106 in conjunction with issue #322
