### ISSUE TITLE
Key attributes cause NPE when used with traits

### ISSUE THREAD

**Issue by ahmedvc** [umple/umple#1023]
When using traits in the presence of a key, a null pointer exception will be thrown and the model will not be generated.
Try the model below.
trait API{
  att1;
}

class Some{
  isA API;
  id;
  key {id}
}

**Comment by TimLethbridge** [comment]
@vahdat-ab - I don't know if you want to tackle this yourself

**Comment by vahdat-ab** [comment]
@TimLethbridge Yes. I just fixed it. It's because of the issue #449.
doing PR in a few minutes.

**Comment by vahdat-ab** [comment]
@ahmedvc  thanks for the catch. It's been fixed and I'll send PR in a few minutes. running a full build on my local machine.
