### ISSUE TITLE
Aspect-orientation (after/before) does not work with Umple methods anymore

### ISSUE THREAD

**Issue by ahmedvc** [umple/umple#1024]
When trying after/before keywords in a normal Umple method, as in the model below, the parser will give a warning that code cannot be injected. When generating the model, the code blocks of after and before will be ignored.

class Test{
  
  void test(){
  }
  
  after test{
    //Some after
  }
  
  before test{
    //Some before
  }

}

**Comment by TimLethbridge** [comment]
This is a duplicate of #1002 so I am closing it
