### ISSUE TITLE
Mixin does not include all inherited traits

### ISSUE THREAD

**Issue by ahmedvc** [umple/umple#1034]
We can use multiple traits with a class. However, when using the mixin feature to define a trait, only the last mixin class will detect the trait. Considering the model below, only the trait Mix3 will be recognised.

trait Mix1{
  void test1(){
  }
}

trait Mix2{
  void test2(){
  }
}

trait Mix3{
  void test3(){
  }
}

class Test{
  isA Mix1;
}

class Test{
  isA Mix2;
}

class Test{
  isA Mix3;
}

The only way to get it working is to declare all of our traits in a single isA call as bellow

class Test{
  isA Mix1, Mix2, Mix3;
}

**Comment by vahdat-ab** [comment]
I assigned this to me. 
It's odd because it must be done automatically by the Umple compiler. I'll explore it.

**Comment by vahdat-ab** [comment]
This issue is not related to the way traits have been implemented. The source of the issue is the way mixins have been implemented. Consider the following example:
```
class C{
}

interface I{
}


class Test{
isA C;

}

class Test{
isA I;
}
```
The generator will disregard extending class `C` and just implement interface `I`

**Comment by opeyemiAdesina** [comment]
@vahdat_ab, The model doesn't seem to correct Umple model... Two Umple classes with name: Test in the same model.

**Comment by vahdat-ab** [comment]
@opeyemiAdesina I didn't get the point. Could you plz explain more?

**Comment by opeyemiAdesina** [comment]
What I meant is that two classes has the same name in the model example you posted.

**Comment by vahdat-ab** [comment]
@opeyemiAdesina yes. It is a valid example. In Umple, we call it mixins. It allows us to separate a class, for example, to modeling and language specific parts.
we used it a lot inside Umple compiler.

**Comment by TimLethbridge** [comment]
Two classes with the same name just mix. That is the whole point

Timothy C Lethbridge
