### ISSUE TITLE
impemIent ctrl+A on UMPLE online on non mac computers

### ISSUE THREAD

**Issue by shaygeller** [umple/umple#1056]
I work on windows, with chrome. 
There is no option to use ctrl+A to mark all the umple code.

**Comment by TimLethbridge** [comment]
Keep the bindings working as they do now on the mac (command a selects all text, and control a toggles the attributes). But on windows control a would select all text, and shift-control a would toggle attributes.
Depending on whether the text or diagram is in focus, different code is used for the bindings. Also the pop-up labels must be consistent.

**Comment by YiranShu** [comment]
@TimLethbridge 
Can I make Ctrl+A still toggle attributes and Shift-Ctrl + A select all text on non-Mac machines? This modification will not change the bindings for mac and will keep the popup labels consistent.

**Comment by TimLethbridge** [comment]
Change toggle attributes to ctrl-shift-A, so that ctrl-A now has its default text-select function in windows

**Comment by YiranShu** [comment]
@TimLethbridge 
OK, so Ctrl+A selects all text on non-mac computers; Command+A selects all text on mac; Ctrl+Shift+A for toggle attributes.
