### ISSUE TITLE
Association class gives wrong error messages when reflexive

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1058]
The following Umple code generates an incorrect warning. It should be naming the associations after the role names

Error on line 3 : Class 'Profile' may not have multiple associations with the same name 'friendships'. More information (19)

```
associationClass Friendship {
  * Profile invitee;
  * Profile inviter;
  status;
}
class Profile {
    name;
}
```

**Comment by TimLethbridge** [comment]
To resolve this, you need to make sure it works properly in cases where the multiplicity is not exactly as shown, and also it should work with the following:

```
class Friendship {
  * -- 1 Profile invitee;
  * -- 1 Profile inviter;
  status;
}
class Profile {
    name;
}
```
that currently also gives the same error 19.
In fact, I suggest starting with the above as it is a simpler case

The problem in the above case is that one or both of the * ends needs to be given a role name, so the message should help with this. The message is generated when analysing class Profile, when in fact it is class Friendship where the association is found, so that adds to the confusion.

Perhaps the message could be adjusted to There are multiple associations between class 'Profile' and class 'Friendship'. Role names need to be added at the 'Profile' end to distinguish the association ends in that class.

However, it turns out that in the associationClass case, there is no way to add such role names I think. It may be necessary to add to the grammar the ability to add role names after the *.

**Comment by runqingz** [comment]
In Summary:
1. Fix the error message of 19 (notice error 180 looks like a similar error) to be more informative
2. Potential fix for association class (add grammar to have the ability to add role name after * in the example above)
Questions:
- The fix to warning message itself does not require test since it is a cosmetic fix?
- Modification on grammar to adopt new requirement will need some testing.
- Not sure about give the grammar the ability to add role names after the * in the association class. What is the expecting expression to be like?

**Comment by TimLethbridge** [comment]
Note that every error or warning message should have a test to check that it occurs when expected.

As for putting role names on association classes. I think that the optional role name for the 'other end' should come after the multiplicity. so the following code would be accepted.

```
associationClass Friendship {
  * inviterFriend Profile invitee;
  * inviteeFriend Profile inviter;
  status;
}
class Profile {
    name;
}
```
But note: Only one of the roles would be needed to avoid the error, although both should be allowed. Role names should also be allowed on any association class, not just ones with the same class. So you will need to add multiple tests for all cases.

The following would then be the logical version using an ordinary class (although only one of the role names is again allowed. The following code should already be accepted.

```
class Friendship {
  * inviterFriend -- 1 Profile invitee;
  * inviteeFriend -- 1 Profile inviter;
  status;
}
class Profile {
    name;
}
```

**Comment by runqingz** [comment]
Yes, I noticed there is test for raising error message. Those tests expect failing with certain error code. What I mean is should I test the actual message content? My editing on error message does not fail those tests that raise parsing error.

**Comment by runqingz** [comment]
It is causing some issue when I modify singleAssociationEnd to ` singleAssociationEnd : [[multiplicity]] [~roleName]? [type] [~roleName]?; ` instance like
``` class A{} 
 associationClass B{ 
  * A a1;
  * A a2; 
} 
```
Will be interpret as` [singleAssociationEnd][upperbound:*] [roleName: A] [type: a1] `
I am not sure how to walk around this problem without some huge changes to singleAssociationEnd grammar format.

**Comment by TimLethbridge** [comment]
it seems the rule needs to be that the 'otherEndRoleName' can only be present if the regular role name is there.

So one way to write it would be:

```
singleAssociationEnd : [[multiplicity]] ( ( [otherEndroleName] [type] [roleName] ) | ( [type] [~roleName]?  ) ) ;
```

**Comment by runqingz** [comment]
Do we allow user to put associationClass as
```
 associationClass B{ 
  * b1 A;
  * b2 C; 
} 
```
in this case it would raise the error that b1 is not a class or interface. I think it is hard to distinguish between ` [[multiplicity]][roleName][type] | [[multiplicity]][type][roleName] `
