### ISSUE TITLE
UmpleOnline expects runtime dependencies to be available at specific system paths

### ISSUE THREAD

**Issue by fhackett** [umple/umple#1081]
## Brief Description

UmpleOnline fails to run some of its subprocesses on machines that do not have the programs it requires installed at the exact locations it expects.

## Minimum Steps to Reproduce

1. Find a machine where GraphViz's dot is installed somewhere other than `/usr/local/bin`. The Nix package manager can be used for this. Run `nix-shell --pure -p php56 jdk ruby ant git nettools rake graphviz zip` to generate an appropriate environment.
2. Rebuild Umple
3. Launch UmpleOnline (I do this with the builtin PHP server, should be the same with Apache), with default settings.
4. Try to generate a state machine diagram

## Expected Result

The diagram appears.

## Actual Result

```
dot (part of GraphViz) does not appear to be installed on the server in /usr/local/bin/dot
```

**Comment by TimLethbridge** [comment]
UmpleOnline was written with absolute paths deliberately, it turns out. Php run frm the Mac web server does not include the right path elements.

See the following, for example, for some commentary.
https://stackoverflow.com/questions/1631075/php-exec-command-relative-paths-not-working

**Comment by Nava2** [comment]
May I suggest [dotenv](https://medium.com/@thejasonfile/using-dotenv-package-to-create-environment-variables-33da4ac4ea8f) and environment variables? It would probably solve the problem!

**Comment by fhackett** [comment]
Summary from a quick in person conversation: this may be an issue with the default Mac setup.

This [link](https://gist.github.com/srayhunter/5208619) suggests a way to fix the issue at the level of Apache configuration.

**Comment by TimLethbridge** [comment]
So the suggestion in the link in the last comment is too complex (requires turning off Mac security, rebooting etc.)

However a much simpler solution works: Simply setting the path, 

I will leave it to you, but please modify compiler_config.php to have after around line 19
```
$PATH = "/usr/local/bin:/usr/bin:/bin";
putenv("PATH=$PATH");
```
or something like that. This will work on Mac OS. Please test on Linux and update your PR to incorporate. The hard paths for dot and zip can be removed. Note that windows installations will need to be special cased here, but that has always been the case.

**Comment by fhackett** [comment]
Thanks for testing, @TimLethbridge.

> requires turning off Mac security

(grumble, grumble macs grumble)

The solution you proposed seems reasonable. I'll tweak it to make it as portable as possible and update the PR when I'm done.
