### ISSUE TITLE
Equals function outputs syntax error in Java when key is an Integer[ ]

### ISSUE THREAD

**Issue by JoshuaMcManus** [umple/umple#1089]
## Description

Using the following Umple code and generating java output will result in a syntax error:
class Test {
  Integer[] vars;
  key {vars};
}

Specifically, this creates an equals() function which compares each value of the array to that of another array. The issue is that the Integer array is cast to an int upon each comparison and then checked if it is null. We need to check if all the values in the array are null (since an Integer can be null), but casting to an int is invalid since an int cannot be null.

**Comment by vahdat-ab** [comment]
This following is part of the generated code in which the problematic lines are described through comments:
```
  private List<Integer> vars;
  ...

  public boolean equals(Object obj)
  {
    if (obj == null) { return false; }
    if (!getClass().equals(obj.getClass())) { return false; }

    Test compareTo = (Test)obj;
  
    if (vars.size() != compareTo.vars.size())
    {
      return false;
    }

    for (int i=0; i<vars.size(); i++)
    {
      int me = vars.get(i);
      int them = compareTo.vars.get(i);
      if (me == null && them != null)  // the problem: me and them are not objects.
      {
       return false;
      }
      else if (me != null && !me.equals(them)) //the problem: me and them are not objects.
      {
        return false;
      }
    }

    return true;
  }


```
