### ISSUE TITLE
Making statemachines observable? 

### ISSUE THREAD

**Issue by mathiasi** [umple/umple#1119]
First time I've come across Umple and really liking it so far, however I've encountered one issue that I could not find a way around. Consider the following example:
````
class GarageDoor
{
  isA Observable;
   status {
      Open { buttonOrObstacle -> Closing;  }
      Closing {
          buttonOrObstacle -> Opening;
          reachBottom -> Closed;
      }
      Closed { buttonOrObstacle -> Opening; }
      Opening {
          buttonOrObstacle -> HalfOpen;
          reachTop -> Open;
      }
      HalfOpen { buttonOrObstacle -> Opening; }
  }
}

class Observable{
 StateObserver[] observers;

  void notifyObservers(Status newState){
    for (StateObserver observer : observers){
      observer.onStateChanged(newState);
    }
  }
}

interface StateObserver{
  void onStateChanged(Status newState);
}
````
Here I'm trying to make the Status StateMachine observable however I need to have a way to override the generated SetStatus method but I can't seem to find a way to change the visibility of setStatus from private to protected, so that I can call notify - is there a way to do so? Or alternative way of achieving this?

**Comment by vahdat-ab** [comment]
I hope I understood your question correctly. 
As long as I know, the method `setStatus` is generated automatically and its visibility is fixed. One way you can deal with that is to create a new `protected` method that calls `setStatus` (something like a wrapper). Then, you can get the required flexibility through that.

Another approach:
use aspect-oriented features of Umple (`before` and `after`).
for example,
```
  after setStatus {
    //do what you want.
  }
```

@TimLethbridge  and others might have others solution as well.

**Comment by mathiasi** [comment]
Thanks! The after-keyword was exactly what I was looking for. And using the before-keyword I was able to extend the functionality so that I can observe the old state and new state. If anyone else comes across this, here is a working example:
````
class GarageDoor
{
  isA Observable;
   status {
      Open { buttonOrObstacle -> Closing;  }
      Closing {
          buttonOrObstacle -> Opening;
          reachBottom -> Closed;
      }
      Closed { buttonOrObstacle -> Opening; }
      Opening {
          buttonOrObstacle -> HalfOpen;
          reachTop -> Open;
      }
      HalfOpen { buttonOrObstacle -> Opening; }
  }
  before setStatus{
    Status oldState = status;
  }
  after setStatus{
    notifyObservers(oldState, status);
  }
}

class Observable{
 StateObserver[] observers;

  void notifyObservers(GarageDoor.Status oldState, GarageDoor.Status newState){
    for (StateObserver observer : observers){
      observer.onStateChanged(oldState, newState);
    }
  }
}

interface StateObserver{
  void onStateChanged(GarageDoor.Status oldState, GarageDoor.Status newState);
}
````
