### ISSUE TITLE
Squash the size of Docker image by creating a base image and doing minor pushes between releases

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1121]
We are now pushing Docker images of UmpleOnline. However the image is quite big (300MB ...) and each new branch, pr and merge to master creates a new one. However the most common changes are either replacement of one of the Jars or some other file in the umpleonline hierarchy. These can be pretty small. It should therefore be possible to set up a situation where there is a base umple image, with most pushes only pushing changed files.

The proposal is to push to an umpleonline-base image only on every release (tag on github), and then to only push other changed files between times.

That would require the publishing script to figure out the deltas, but that shouldn't be too hard.

There is a new --squash tag on the Docker build command. Could this be used to merge changes into the UmpleOnline layer? I note there are already two layers created ... one for the COPY and one for the change of permissions. At least these could be squashed.

Some ideas about making smaller Docker images are here: https://developers.redhat.com/blog/2016/03/09/more-about-docker-images-size/
https://opensolitude.com/2015/05/13/docker-images-should-be-small.html

**Comment by fhackett** [comment]
I went through and generated a breakdown of the layers in our current (as of writing) latest image via `docker history`:
```
finn@nixos ~> docker history umple/umpleonline
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
```
The actual UmpleOnline website, jars and all (~60MB):
```
f77abe997534        3 days ago          /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "su...   0B                  
<missing>           3 days ago          /bin/sh -c chown -R :nginx /var/www &&    ...   29.4MB              
<missing>           3 days ago          /bin/sh -c #(nop) COPY dir:97381dbefedeffd...   29.4MB              
<missing>           3 days ago          /bin/sh -c ln -s /usr/lib/jvm/default-jvm/...   0B
```
Support and configuration files (<1KB):
```
<missing>           3 days ago          /bin/sh -c #(nop) COPY file:6a5a739ee25a25...   121B                
<missing>           3 days ago          /bin/sh -c #(nop) COPY file:dcd26e13956533...   481B                
<missing>           3 days ago          /bin/sh -c #(nop) COPY file:e5bb0f55e714c8...   138B
```
Software dependencies (Java, PHP, Python, etc...) (233MB):
```
<missing>           3 days ago          /bin/sh -c adduser -D -H -h /var/cache/php...   233MB
```
More metadata:
```
<missing>           3 days ago          /bin/sh -c #(nop)  MAINTAINER Umple umple-...   0B
```
The base image, shared between containers so anything below this point is actually irrelevant:
```
<missing>           6 weeks ago         /bin/sh -c #(nop)  CMD ["nginx" "-g" "daem...   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  STOPSIGNAL [SIGTERM]         0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  EXPOSE 80/tcp                0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop) COPY file:1d1ac3b9a14c94...   1.09kB              
<missing>           6 weeks ago         /bin/sh -c #(nop) COPY file:af94db45bb7e4b...   643B                
<missing>           6 weeks ago         /bin/sh -c GPG_KEYS=B0F4253373F8F6F510D421...   11.5MB              
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV NGINX_VERSION=1.13.5     0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  LABEL maintainer=NGINX ...   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:9d67752278c0e5a...   3.99MB 
```

I read through the links you posted @TimLethbridge and it seems we're actually doing pretty well on those fronts. The only issue is that we depend on some heavyweight software like Java and co which are inflating the image. I looked into --squash and while it could be useful (it would save another 30MB in theory) it is still experimental and is unlikely to work on Travis's production docker instances due the flag you have to pass to the Docker daemon on startup.

A common base image containing the Java dependencies would indeed fix the main issue here. [EDIT] I thought a bit about security patches and release cycles (our base image last build 6 weeks ago), and to save more space I think we can afford to only rebuild once per tag.

I would like to note however that for the sake of reproducibility most of the dependencies are version pinned anyway - it would be important to check up on the Dockerfiles every month or so and make sure to do version upgrades, etc... or our Docker images will be out of date.
