### ISSUE TITLE
Implementing new feature that allows modification in JJs Association is reflected in Umple Code

### ISSUE THREAD

**Issue by runqingz** [umple/umple#1127]
## Brief Description

Currently, editing association end by moving the association line among different class in JJs class diagram will not result in refreshing Umple code to reflect those changes. However, this feature should be implemented for better User experience.

## Minimum Steps to Reproduce

In Umple online

1. Create multiple classes
2. Create a new association among any pair of the classes.
3. Move the association link to different class

## Expected Result

Umple code should refresh to reflect the new structure of the diagram

## Actual Result

Currently JointJs option does not have such feature

***Note:*** This is relate to issue #600

**Comment by runqingz** [comment]
@vahdat-ab as you suggest in the meeting, this feature should be implemented by extending UmpleSync actions (e.g. adding new editAssociationEndAction). However, I feel like this will increase unnecessary complexity. 
1. The JSON action object create by jjs_parse (makeUmpleCodeFromAssociation around line 812) need to be extended to parsing old Association Ends and new Association Ends in order to locate and modify the associations, which might/might not influence other existing actions.
2. By adding this new action, we only improve the performance in this case: 
```
class Class1 {* -- * Class2}
class Class2 {}
class Class3 {}
```
Modified to 
```
class Class1 {* -- * Class3}
class Class2 {}
class Class3 {}
```
Where we just modify the String, however in another case: 

```
class Class1 {* -- * Class2}
class Class2 {}
class Class3 {}
```
Modified to 
```
class Class1 {}
class Class2 {}
class Class3 {* -- * Class2}
```
The behaviour is pretty much the same as remove old one then add new one (textParse, umpleParse -> find old association, set that line to "" -> textParse, umpleParse-> findClass -> add new association String)

My point is that, if we are not expecting any feature extension on edit association end action, add this new action seems over complicated the issue. We can just remove then add without huge performance drawback

**Comment by vahdat-ab** [comment]
In that case, go with removing and adding associations. Please document a hint to this issue in the code, so in the future, if we need more features we can get ideas about our decision.

**Comment by runqingz** [comment]
@vahdat-ab I investigate the events provide by JJS Api, basically the issue I have right now is the information of all possible events provided do not fully contain the ends before changing and after changing. 

For example, in the example above ` Class1->Class2 `  to ` Class1 -> Class3 `, on disconnect, it only provides knowledge that it is disconnected from Class2; on connect, it only provides knowledge that it is connected to Class3. Under this condition, it is not able to provide complete information "the association is disconnected from Class2 then connect to Class3" on any of link related event, which is essential for editing Association End.

 I would suggest this fact force JointJs editing Association to be a combination of deleting and adding.

**Comment by runqingz** [comment]
This comment is for future implementation. If JointJs provides an link related event in the future that it provides full information "this link is disconnected from node1 then connected to node2". At that point, this feature should be implemented using a single new UmpleSync action (e.g. EditAssociationEnd).
