### ISSUE TITLE
Add a separate Diagram Type option for state diagrams in joint.js

### ISSUE THREAD

**Issue by runqingz** [umple/umple#1131]
## Brief Description

The current JointJS state diagram option is triggered by click on the red outline (if state machine exists). However this is hard to use and might cause confusion. I would suggest to add a separate diagram type option for a better user interface.

***Note***: this is related to issue #600

**Comment by runqingz** [comment]
@vahdat-ab I'm sorry to bug you but I am kind of stuck too long on this (which I believe should be easy). I basically added a new radio button and duplicated and modified new code everywhere that is related to JointJsClassDiagram in umple.php, umple_action.js, umple_page.js. 

However clicking on the button is still not caught by the scripts. The system here is much more complicated than anything I have worked on before and I can not really see what I missed to hook up the event (I am pretty sure the consistency of ids).

Would it be possible for you to suggest me some other possible files I should also modify? or maybe check what I have done so far?

**Comment by vahdat-ab** [comment]
@runqingz  I believe the feature that allows us to see in which class we have a state machine is a practical one. I would keep it. The solution to implement it might be weak but you may want to improve it. Having all state machines in one diagram is another way to represent state machines, which has its own benefits.
The technique to be able to select the class you need to fouse on and see just its state machines is really important. Yesterday, I was part of a user interface study in which they all mentioned such feature is critical. Old tools achieve this through providing a popup menu and showing links, but recently they all provide an icon when you click on it, it shows the state machines. Having a red dot was just a prototype. You need to replace it with the standard icons for state machines. You can find it online or through UML specifications.
Regarding your issue with UmpleOline radio buttons (if you want to show all state machines in one diagram) I would say @TimLethbridge  will be the right person to answer this.

**Comment by TimLethbridge** [comment]
I would be in favor of having *both* the feature whereby you can click on an icon in a class diagram and jump to the state diagram, plus the ability to see all the state diagrams. And yes change the red dot. My suggestion is that the diagram that shows all SDs could allow collapsing them so you can focus on one. The diagram that appears when you click on a class diagram woul be the same, but would have only the relevant class's state diagram uncollapsed.

**Comment by runqingz** [comment]
In this case, I would only modified the red dot to a standard state machine icon. Then option to show all JointJs state machine diagram should be implement after JointJs state digram can render collapsed state machine from all class (currently it fails to render state with multi-classes).

**Comment by TimLethbridge** [comment]
Closing because I don't want to do further work on joint.js
