### ISSUE TITLE
Allow state machine modification in JointJs diagram

### ISSUE THREAD

**Issue by runqingz** [umple/umple#1132]
## Brief Description

Currently the implementation UmpleSync does not have action that update umpleCode that correspond to when the stateMachine diagram is changes. This is because the only option (graphViz) UmpleOnline used to have for showing state machine diagram does not allow modification. However JointJs diagram showing state machine allows same operation as class diagram (moving transition end, delete transition). New UmpleSync action should be added to update code once user modify the diagram (DeleteTransitionAction, AddTransitionAction). Edit Transition action will be implementation as a combination of removing then adding as discussed in issue #1127 (same data structure)

***Note:*** This is related to issue #600 

## Tesing

JUnit testing should be added to test the new feature works as expected

**Comment by TimLethbridge** [comment]
The joint.js diagram should *eventually* allow:
 a) Creation of new states (perhaps the 'class' icon would change to
'state' in the UmpleOnline edit palette when viewing a statemahcine using
joint.js)
 b) Deletion of states (e.g. with a garbage can icon like in the joint.js
class diagrams)
 c) Editing of state contents (e.g. actions)
 d) Moviing a state inside another to create a substate
 e) Adding of transition (use the association icon, but relabel when in a
joint.js state diagram)
 f) Deleting of transitions (same way it works in class diagrams)

For now, do just e and f as this is what this calls for. But eventually
the others will have to be done.

This will require adding new json generation.

**Comment by TimLethbridge** [comment]
I am reopening this since PR #1414 brought code into use, but it still needs refinement. The feature is not activated in the user interface of Joint.js

**Comment by TimLethbridge** [comment]
Closing because I don't want to do further work on joint.js
