### ISSUE TITLE
Command line debugging tests fail to run on Appveyor and cruise-control

### ISSUE THREAD

**Issue by JoshuaMcManus** [umple/umple#1176]
## Brief Description
Refer to Issue #882 to see changes made for command line debugging. (Seetestbed/test/cruise.compiler.CompilerErrorOutputTests and testbed/test/cruise.compiler.RuntimeErrorOutputTests)

The tests built for the command line debugging fix are not running on Appveyor and cruise-control machines. The majority of tests run fine on all other machines (including Travis), but all fail to find the text files used to verify the results in the other two machines.

The likely cause behind this is the use of relative paths in CompilerErrorUtil.java and RuntimeErrorUtil.java. These two utility functions expect the execution environment to be one directory deep from the root, and attempts to find the correct files relative to that position. Appveyor and cruise-control likely have a different execution environment and thus get an invalid path when opening the expected .txt files.

**Comment by JoshuaMcManus** [comment]
Note that @TimLethbridge disabled these tests on the machines in order to have the builds pass, when a fix is found you will want to remove the workaround.

**Comment by TimLethbridge** [comment]
For the record, the workaround is to add the following line to _appveyor.xml and _cc.xml in the build directory. Removing these lines will re-activate the tests on those build servers.

```
<property name="excludeCompilerErrorOutput" value="true"/> 
```

**Comment by TimLethbridge** [comment]
This was only partially fixed. The commit message had the word partially, but the word fixed caused its complete closure. Reopening.

**Comment by TimLethbridge** [comment]
In Appveyor, if I activate the error output tests, then 6 of 9 tests fail:
```
jar:file:/usr/local/Cellar/ant/1.10.5/libexec/lib/ant.jar!/org/apache/tools/ant/P$
    [junit] TEST cruise.runtime.RuntimeErrorOutputTests FAILED
```
This is done in branch Java11AndIssue1176

What we need to do is to see why the

CompareOutputToExpected()

method at RuntimeErrorUtil.java

is failing in these 6 specific cases. I suspect it might be line-end  
differences in Windows. The output is being compared to specific files
coming from directory.
testbed/test/cruise/runtime/expected

**Comment by YiranShu** [comment]
@TimLethbridge 
I pulled the branch Java11AndIssue1176. The full build fails immediately after I launch a full build. So I cannot see the 6 failing cases you mentioned. Following is the failure message I encountered.
yiran@yiran-virtual-machine:~/program/Umple/umple/build$ ant -Dmyenv=local
Buildfile: /home/yiran/program/Umple/umple/build/build.xml
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

build:
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

qaBuildingPage:
     [echo] Starting Build
     [copy] Copying 1 file to /home/yiran/program/Umple/umple/dist/qa
     [echo] Building Sandbox for Testing Infrastructure
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

build:
     [echo] A sample build file for the Sandbox
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

template.clean:
   [delete] Deleting directory /home/yiran/program/Umple/umple/cruise.umple.validator/bin
   [delete] Deleting directory /home/yiran/program/Umple/umple/cruise.umplificator/bin
   [delete] Deleting directory /home/yiran/program/Umple/umple/sandbox/bin
   [delete] Deleting directory /home/yiran/program/Umple/umple/dist/sandbox
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

template.init:
    [mkdir] Created dir: /home/yiran/program/Umple/umple/cruise.umple.validator/bin
    [mkdir] Created dir: /home/yiran/program/Umple/umple/cruise.umplificator/bin
    [mkdir] Created dir: /home/yiran/program/Umple/umple/sandbox/bin
    [mkdir] Created dir: /home/yiran/program/Umple/umple/dist/sandbox
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

umpleSandbox:
     [java] Error: Unable to access jarfile /home/yiran/program/Umple/umple/dist/libs/umple-1.29.1.4260.b21abf3a3.jar
     [echo] Using myenv=local
     [echo] Last Version: 1.29.1.4260.b21abf3a3

qaLandingPage:
     [echo] Creating a QA Landing Page
     [copy] Copying 1 file to /home/yiran/program/Umple/umple/dist/qa

BUILD FAILED
/home/yiran/program/Umple/umple/build/build.xml:9: /home/yiran/program/Umple/umple/build/build.xml:14: The following error occurred while executing this line:
/home/yiran/program/Umple/umple/build/build.sandbox.xml:59: The following error occurred while executing this line:
/home/yiran/program/Umple/umple/build/build.sandbox.xml:24: Java returned: 1

Total time: 0 seconds

**Comment by TimLethbridge** [comment]
I am going to merge PR #1387 off branch Java11AndIssue1176 so please start a new branch for further work on this. Umple needs to compile properly under Java 11.

**Comment by TimLethbridge** [comment]
This has now been solved. The tests are active in Appveyor
