### ISSUE TITLE
Generator NuXMV (nuSMV) broken for some examples. Need to check all examples

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1226]
All the class diagram examples result in crashes of the NuSMV generator
```
Exception java.lang.IndexOutOfBoundsException in at java.util.ArrayList.rangeCheck(ArrayList.java:653) at java.util.ArrayList.get(ArrayList.java:429) at cruise.umple.nusmv.NuSMVCoordinator.genMainVariableFor(NuSMVCoordinator.java:272) at cruise.umple.nusmv.NuSMVCoordinator.generateModel(NuSMVCoordinator.java:331)
```

All Examples should be checked.

**Comment by gublan24** [comment]
The model checker NuSMV analyzes the finite-state and infinite-state systems. In umple, it is used to analyze state machines. The generator looks at class(es) with state machines. It fails if the umple file has class(es) but no state machines.

The alternative output when there are classes with no state machines can be: ```


``` 
-- This file is generated from model.ump --

-- PLEASE DO NOT EDIT THIS CODE --
-- This code was generated using the UMPLE @UMPLE_VERSION@ modeling language! --

/* To generate NuSMV model, your umple file should contain some state machines. */

**Comment by TimLethbridge** [comment]
Yes, this makes sense.

**Comment by gublan24** [comment]
Good. 

A minor issue; it will be difficult to test the output as the expected result will be parsed as an empty file after ignoring the comments. So, do we need to test the output ?

**Comment by TimLethbridge** [comment]
No just test that it doesn't fail (if you can)
