### ISSUE TITLE
Some test cases in testbed are never executed

### ISSUE THREAD

**Issue by BernardYuan** [umple/umple#1254]
In testbed, test cases from package **cruise.association.specializations** and **cruise.association.compositions** seem to have no corresponding JUnit tests. Therefore, it is doubted that those test cases are only compiled, but never executed. Therefore, some runtime errors from the code generated from Umple test cases will not be captured.

**Comment by BernardYuan** [comment]
@TimLethbridge This is the testbed issue I have mentioned in our weekly meeting.

**Comment by BernardYuan** [comment]
Fix this after fixing issue #988 , otherwise lots of testcases can be expected to fail.

**Comment by RalphNgassa** [comment]
There are indeed no existing unit test for **cruise.association.specializations** and **cruise.association.compositions** as it was mentionned. But going through the testbed source files I noticed a comment present in **TestHarnessHarnessAssociationsSpecialization.ump** saying that if cruise.association.specializations test cases compiled then it means they were successful.  I believe this explains why there are no corresponding junit test.

Unfortunately, there no similar comments present in the compositions test source files but that might explain why there are no corresponding compositions junit tests.

The comment:

![image](https://user-images.githubusercontent.com/71353825/124293465-b52f1780-db24-11eb-8d77-326d1600736d.png)

**Comment by TimLethbridge** [comment]
Was closed by #1796
