### ISSUE TITLE
Missing immediate validation for graphical edits in UmpleOnline

### ISSUE THREAD

**Issue by ZainabAlShowely** [umple/umple#1298]
When adding new attributes to classes in the Umpleonline editable diagram, several checks are missing, causing errors as the code will no longer reflect the diagram content.
An error message indicating that the Umple code is unable to be updated is added to the text editor multiple times, but the expected behavior is not allowing adding the attribute (as with non-alphanumerical names).

Duplicate attributes name and attributes names conflicting with association names or state machines cause the issue.

Other checks may need to be added to method names as well.

**Comment by TimLethbridge** [comment]
There are two types of diagram edit checks:
  1) In-diagram, puts message at top for basic atrribute name errors that are not alphanumeric
  2) Compilation checks. This seems to only happen if the text is edited manually, or by 'undo'. But should be happening after every diagram edit.
