### ISSUE TITLE
Need for namespace reset override

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1315]
Currently if you say 

```
namespace n;
class X {}

namespace m;
class Y {}

class X{}
```

you get in UmpleOnline
```
Warning on line 7 : Redefining the namespace of class X to m. More information (30)
Warning on line 9 : Redefining the namespace of class X to m. More information (30)
```

There are two problems here:

1. You might want in the second redefinition to not redefine the namespace to m. This is a serious problem when using a new file or mixset. 

2. In UmpleOnline the second message appears due to the hidden diagram information. The warning and redefinition will *always* appear.

Solution alternatives

a) Reverse the situation. Only take the first namespace, and leave it in place. Also add a 'namespace -;' syntax that would indicate that following this point no namespace is active. That could be injected to step putting subsequent classes in a namespace. This could be injected at the start of the diagram code.

b) Add an extra optional second argument to the namespace directive 'final' (or something similar) to prevent overrides and warnings about them.

c) Leave the first namespace as the final namespace. Don't override on any redefinition by default, and hence drop the warning. Also add a 'override' as a possible second argument to force an override should this be desired. The idea of having namespace - would still be a good idea but would not be needed to be injected in UmpleOnline for diagrams.

Suggest option c

**Comment by vahdat-ab** [comment]
The issue you opened is one of the issues I have faced a while ago and tried to fix this with some constraints and warning. There are many scenarios you may imagine to mix namespaces. It becomes more complicated when you use `use` statements that have several namespaces defined inside the used files. Even the order of using statement will cause some concerns (with respect to other use statements or other names spaces)
The person who wants to fix this issue must also consider these cases. 
Fixing this issue with new definitions may cause some problems in building UmpleCompiler because there are some dependencies about how use statement works.

**Comment by TimLethbridge** [comment]
OK. So here is the proposed solution, reflecting Vahdat's issue and respecting the need to enable existing systems to still compile.

1. Add 'final' as an optional second argument to the namespace directive. This prevents classes set with this namespace directive from being reset by a later mixin or mixset triggered by a use statement.

2. Add  '-' as an optional argument to the namespace directive. This cancels any outstanding namespace. Subsequently defined classes default to no namespace (unless a redefinition is encountered in a subsequent mixin/mixset for them. Note that '- final' makes no sense.

3. Add a warning if an attempt to redefine a final namespace is encountered (saying it is ignored), The existing warning would still be in place for non-final namespace redefinition.

4. Document as follows.
  - Best practice is to specify 'namespace X final' before a group of classes to be in the namespace and then 'namespace -' after the block. This could even be done in a mixin to structure the system.

**Comment by TimLethbridge** [comment]
See also #52

**Comment by TimLethbridge** [comment]
In fact although the warning messages 30 say that the namespace is being redefined, in fact it it is not.

also if you attempt to specify the original  namespace, you still get the warning:

```
namespace n;
class X {}

namespace m;
class Y {}


namespace n;
class X{}
```

Therefore the best solution is

1. Change the warning message to say, 'Attempt to redefine ...'. Assume by default all initial namespaces are redefined.

2. Remove the warning in the case above in this comment, when it is actually not changing what was previously set.

3. Add an --override that would allow changing of the namespace in a mixin e.g.


```
namespace n;
class X {}

namespace m;
class Y {}

namespace p --override;
class X{}
```
In this case, class X would end up being in p not in n

**Comment by TimLethbridge** [comment]
The school example shows a case that this issue should solve.

**Comment by fjtheknight** [comment]
@TimLethbridge 
I am not sure I understand the utility of overriding a namespace (Any cases where overriding namespaces is useful?). I think the best thing is to leave the namespaces as final (the class's namespace is the first namespace encountered before the class was declared). 

So in this example:

````
namespace n;
class X {}

namespace m;
class Y {}

class X{}
````

n will be the namespace for class X, while the second 'class X{}' will just be considered as a mixset and injected into class X.

I think this will also solve the issue with what Vahdat described, and with the second warning resulting from the hidden diagram information.

**Comment by TimLethbridge** [comment]
@fjtheknight 

The problem is that currently, when the second definition of class X occurs, we are in the context of namespace m. So it is unclear what the developer's intent was. Curently 'the first namespace encountered for a class is the final one' and the message needs modifying (see the comment on Sept 23).  But in a complex system the user may not be aware that some aspect of the class had been defined in another file and was encountered first. In fact, the user may be using a bit of 'library' Umple code, and may want to overide a default package.

So let me refine and re-iterate what needs to happen. These can be done in separate PRs.

1. Warning 30 needs to be adusted to say `Ignored attempt to redefining the namespace of class {0} to {1} . Use --redefine to force this';`
2. 
3. A --redefine option following the namespace needs to be added to allow redefinitions.
4. 
5. A - option for the name of the namespace needs to be added to cancel the current namespace specification
6. 
7. Examples need to be fixed so those with hidden layout no longer specify error 30.

**Comment by TimLethbridge** [comment]
The subissue of erroneous warning 31 was noticed when working on this issue. The algorithm I suggest to solve this might work as follows:

Create a attribute 
```
String nameSpaceNotUsedYet; // null if there is no outstanding unused namspace
```

1. When parsing, initialize this to null.
2. When defining a class in a namespace, set this to null as we are using the namespace.
3. When encountering a namespace directive (i.e. changing the namespace), 
  If nameSpaceNotUsedYet is not null,  issue warning 31
  Set nameSpaceNotUsedYet to the new namespace.
