### ISSUE TITLE
Selecting  "Show Files in Separate Tabs" and then "view source" generates <p></p> at the end of the last file

### ISSUE THREAD

**Issue by fjtheknight** [umple/umple#1478]
With the following example
```
class A{}
class B{}
```

If we click "Generate Code", select "Show Files in Separate Tabs" and then "view source" for the last file (which is class B in this example), the code contains ```<p></p> ```at the end. This always happens with the last file (even if there is only one file) and with different languages.

**Comment by TimLethbridge** [comment]
Actually, even with a single file the tab shows the extraneous characters; or with any example in fact!
