### ISSUE TITLE
UmpleOnline module to allow running experiments

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1490]
This has been implemented and is available in UmpleOnline. Documentation is at:
http://tasks.umple.org

This project would allow some of the following features:

An experimenter could define an experiment for which he or she would like participants (e.g. discovering which modeling mistakes are the most common; learning how long it takes someone to build a model, experimenting with usability of Umple itself).

After obtaining ethics approval, they would load the experiment design in a computer-readable way into UmpleOnline.

UmpleOnline would have a new button at the top that would solicit 'Participate in a Modeling Experiment' from users. This would present the experiment in a series of steps where the user would modify or draw a model and then hit 'submit'. Following submit, the user might be directed to a survey tool to answer additional questions.

**Comment by TimLethbridge** [comment]
To develop and put into practice a capability in UmpleOnline for running experiments. This will faculitate  further in Umple Issue #88 

2.1 Motivations

The motivations for the work are as follows:

•	Many empirical studies have been done targeting specific tools, languages, and features in the software modeling community
•	Studies show there are many weaknesses in tools, and lack of tool and language use
•	We need to know what features are most useful in a modeling tool
•	We need to drive more widespread use of model-driven engineering (MDE) by overcoming its obstacles
•	We need to make it easy to do many studies, collaboratively with researchers around the world
•	Studies should not be overly-specific to tools, languages, problems, or types of users

The overall objective then is for many tool developers to create an experimental platform so experiments can be done in different tools, to compare them. For the current project we will just be creating the Umple-based platform. We will also do some experiments with it to test that platform.

The general vision for an experiment tool would be as follows. The system should be able to do the following (items marked * would be needed for the first version, to be developed in this project)

A. Prompt people to participate *
•	Tell them what would be involved
•	Obtain and record their consent

B. Present them with inputs: *
•	Requirements
•	initial models
•	change to be made
•	questions to answer
•	tasks/goals to achieve

C. Record
•	Feature use (commands etc.)
•	Evolving model at each time step *
•	Errors encountered
•	Optional: Users comments
•	For some studies: Answers to specific questions, completion of tasks *

D. Follow up with survey questions (e.g. jump to Google Form or SurveyMonkey)
•	Demographics
•	What they liked or disliked

E. Allow the user to opt-out at any time *

F. Maintain security of the data
•	Only sent encrypted to authorized researchers


Researcher data input

Researchers would need to produce a json file which would contain the information above. The tool would load the json file and create the end user view as below. One of the items in the json format would be where to send experiment data when done (as per item F above).

End user view

In UmpleOnline, the above would appear to end users as follows:

There would be a button ‘participate in a study’ that a user could click if they were a random user interested in participating in a study. Alternatively, a researcher might have given the user a URL to go to to directly initiate the study.

Upon initiation, a subwindow would appear with the information in item A above. When the user has consented, the material in item B above would appear in this subwindow, except any initial model which would appear in the main interface (text and diagram)

The software would record the state of the model as the user changes it, and any responses to specific questions.

eliverables

Prior to the start of the student project, the student will be provided with:
•	A json schema for an experiment design; this will be discussed with other researchers so they may be able to implement the same design in their tools
•	Some example simple experiment designs in the json format. These will form a set of test cases
•	An expansion of this document with additional details

Key deliverables for this student project:

1.	The student will be asked to fix one or to small issues (bugs or small feature changes) in the existing UmpleOnline so he can learn about the codebase.
2.	Load for the json file (or sets of available files)
3.	Parser for the json file.
4.	Window opener that then initiates following the steps in Section 2.5 above.
5.	Demonstration that the system works with the provided test cases (in Miscosoft Edge, Google Chrome, Firefox), and additional test cases sufficient to verify all aspects of the delivered code (as per steps 2-4).

**Comment by TimLethbridge** [comment]
For Part C above, recording Feature use, it should work as follows.

I suggest work on this starts by recording the model versions only as the first iteration.

There should be an commandLog.php file that would be invoked to record the LogOfCommands.txt and add an item to the LogOfModelVersions directory as discussed below.

Some of the information here can be recorded when the compiler.php or other php code is called.

Logging would only happen if recording is enabled, so there would need to be a command to initiate recording which would write the first version of the LogOfCommands.txt file below. For testing, just create the LogOfCommends.txt file

 It would be important that if no logging is going on, then the system not be slowed down.

In the user's UmpleOnline directory (ump/tmpxxxxxx or ump/2020xxxxxxxxx the logging mechanism should record a file with a name LogOfCommands.txt )
In this file there should be one line per trace. Lines should be of the format

```
yyyymmdd-hh:mm:ss <LogCode> <arguments>
```

Not all LogCodes (listed below) would have arguments

<LogCode> might be one of the following (where the - lines are comments (this is not a complete list)

  LoadFile <fileOrExamplename>
    - Recorded every time a new file or example is loaded

  EditFile <editSeqNumber>
    - Recorded after typing or diagram editing results in a new saved file in LogOfModelVersions
    - editSeqNumber would be used to record the file version (see below)
  
  Draw <class|association|generalization>

  Undo

  Redo

  Generate  <typeGenerated>

  GraphFormatChange <graphFormat>

  OptionChange <optionType> <newOptionValue>
  
 Also, every time the model.ump is updated while tracing a copy of the new file should be put in a directory called 

LogOfModelVersions

The filename would be model-n.ump, where n would be the version number (corresponding to the editSeqNumber above)

**Comment by TimLethbridge** [comment]
Issue 1490 starting point for item B above (presenting users with inputs and related functions)

B1. In the ump directory there should be a subdirectory called 'tasks'. [Start by creating this].

B2. In the tasks subdirectory a professor could add assignments or a professor could add experiments. We will not distinguish (for now) and call these task subdirectories.

B3. Each task subdirectory should have an unguessable name created using the same algorithm as is used for temporary and bookmarkable directories in ump, except prefixed by 'taskyymmdd' (instead of 'tmp' or just 'yymmdd') (where the date would be present), and then followed by a series of 8 or 9 random characters from 0-9 and a-z. An example might be task2007016g2k9d64v [Create a php program that will generate one of these]

B4. A task subdirectory would be created by a researcher or professor who is authorized. Initially we won't restrict authorization. It will contain 
  1) A file requirement in instructions.md This will be rendered as the description of the task
  2) Optional .ump files (1 or more) to be loaded as the starting point for the experiment or assignment
  3) Other information in a taskdetails.json This should include a taskname of the researcher/professor's choosing (string of up to 20 characters with no spaces). The taskname must be unique, so all other task directories would have to be checked upon creation. Other information may be added here later, for example a list of allowed users which for now we will ignore and refer to as uuuuuu; we might also put a deadline date here
  [Enhance the php file that will prompt for items 1, 2 and 3] when it creates the task subdirectory.

B5. Once a task subdirectory is present, UmpleOnline should have be able to load a task at startup. Currently it can load an example or a file. Loading a task would be programmed very similarly. The 'taskname' should be used, not the directory name. The system would have to search all task directories to find the matching taskname; this might be inefficient if there are lots, but for now this will do. [This would be done in umple.php and related files. This could be done before B3 and B4 above, if the task subdirectory is manually added first] When as task is loaded for a user, its ump files would be loaded in the normal way [Do this first].

B6. It would be necessary, when creating an ump directory for a task, to make it 'bookmarkable' right away. and also to prefix it with the taskname, and userid, so for example, instead of an ump directory being named something like 2007168hr2ige8b, it would be something like task-taskname-uuuuuuuu-200716b6ws7yrg [Do this before item B7]

B7. When loading the task, the instructions copied from the task subdirectory would be rendered as html (converted from Markdown in a very basic way) and loaded into a pane just above the  Line=  E G S  T D line. This panel could be expanded or contracted by the user to take up more or less space. Also there would be a button 'hide' and 'submit task' button. The submit button would add information (to be determined) to the data recorded in the taskdetails.json

B8. For security reasons, it is important that end users never can see the task subdirectory name, only the taskname.

B9. When working on a task, all details of the user's interaction may be recorded in their ump/task-... directory. [Haowen Shi is working on this.]

B10. A student could submit an assignment to a learning management system like Brightspace by simply sending the URL. On the other hand, a professor or researcher could take a look at all of the work being done by requesting that the system send all the directories in ump that start with the taskname. [we will need to create a php file to zip the relevant directories and initiate this, but there would have to be some security to prevent arbitrary people from doing this, as the taskname can be seen by users]

**Comment by WeiqiMaster** [comment]
How should the user interface look like for a professor to add assignments or experiments?

**Comment by TimLethbridge** [comment]
Start off doing this very simply as a prototype. Just create an html form that would create a tasks directory with the relevant information. The form would post to a php program that would save the directory.

At some point we are going to have to require a password to be created so the professor/researcher can edit the task, so we will need to store a name of the researcher, an email and a userid too (along with the requirements, ump file, etc. One more point I forgot: There should be a field with a URL for submitters to go to after they submit (could be a survey).

Also we will need a way for me to authorize a professor/research to do this. Perhaps initially anybody could set this up, but once I authorize, they could then edit and do other surveys/assignments.

I leave this to you to draft. Send me a branch with your idea for feedback (before doing a pull request)

**Comment by TimLethbridge** [comment]
The following is VERY ROUGH. And is for background only to help with thinking about login in and interconnection requirements.

Key use cases:

1. A professor or researcher posts the following to a special interface in UmplleOnline
  A. Text describing instructions, including requirements (i.e. what the system being modeled should do; whether to create class or state diagrams, etc.)
  B. Maybe: Target audience (anybody, specific people to be invited, etc. (?? list of emails, userids,  )
  C. How the answers are going to be sent back (email of the professor or researcher??)

2. Umple admin approves the professor (who then can submit any assignments/experiments)

3. Once assignment/experiment is in the system, a URL is generate that the professor can give to students/participants

4. Student/participant using the URL loads up the information in 1A above (which appears) and uses UmpleOnline as normal. They have to identify themselves with their userid from 1B (if this is needed).

5. When done student/participant selects 'Submit' and the contents of the ump/xxxx directory for their work is sent to the destination in 1C.



To the greatest extent possible, when implementing this issue we need to think about in future conforming with the LTI specification, so please read about this before proceeding.

For details on LTI 1.3 see here:
https://www.imsglobal.org/spec/lti/v1p3

There is a FAQ here
https://www.imsglobal.org/lti-fundamentals-faq

Tools interoperability guide is here:
https://www.imsglobal.org/spec/lti/v1p3

Umple would be a tool, that ought to be able to plug in to a platform such as Brightspace or Moodle. Ultimately Umple would need to accept the ability to be launched by a platform.

It could be launched by a platform by an instructor/experimentor, who could be setting up an assignment or experiment. So UmpleOnline would have to send
  deplyment_id (which university / integration)
  context_id (i.e. the course ... can display label, title in UmpleOnline)
  user (sub)
  role 


Key information from the LTI standard

platform has
  contexts (courses)
  user (communicates unique ID, and may share firstname, lastname, email address)
  role: learner, instructor, adminsitrator

Messages to tool (i.e. Umple) - via a user's browser
  - Alternative is services - platform to Umple

Tool sends Openid Tokens
Umple sends JSON Web Tokens (JWT)

sub claim possible for anonymous Umple access

**Comment by TimLethbridge** [comment]
This is mostly done. Leaving around for now since it hasn't been used much
