### ISSUE TITLE
enum declaration in associationClass causes error

### ISSUE THREAD

**Issue by loucadufault** [umple/umple#1522]
Declaring an enum and creating an attribute with type that enum in an association class causes the error:

"Association class 'NameOfAssociationClss' is missing an end. More information (8)"

This is a **minimum** test case to validate the problem. 

1. Create two classes
2. Create an association class between them
3. Declare an enum in the association class
4. Declare an attribute in the association class with type that enum
5. Obtain error linking to here:  http://manual.umple.org/?E008AssociationClassMissingEnd.html

If using a large code sample, feel free to use a [gist](https://gist.github.com/) or [UmpleOnline](http://cruise.eecs.uottawa.ca/umpleonline/).

## Describe the expected result that didn't happen

Creates an attribute of that enum type, and creates the association class successfully.

## Actual Result

Error: http://manual.umple.org/?E008AssociationClassMissingEnd.html

Please include any build log output. If long, please paste it into a [gist](https://gist.github.com/) and link to it here. 

## Labelling and Assigning

If possible, please try to add any relevant label's for this issue, such as 'associations', 'Component-UmpleOnline', etc. as well as Priority- and Diffic- label.

If you are planning on fixing this issue, or know who will, please assign it to yourself.

In the above use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for formatting.

**Comment by TimLethbridge** [comment]
I have checked this with the following code

```
class X {
 name;
}
class Y {
 id;
}

associationClass XY {
 * X;
 * Y;
 enum completeness {very, aLittle}
}

```
