### ISSUE TITLE
"Photo Ready" option in Umple Online will cut off the diagram if the diagram is scrollable

### ISSUE THREAD

**Issue by WeiqiMaster** [umple/umple#1546]
Possible Solution: 1. Consider providing a downloading .png diagram option
2. Give a link that directs to a new tab to show the full image.

**Comment by TimLethbridge** [comment]
I think the solution is simply be to not turn off the scrollbars. This feature was put in so people could have a nice view (in addition to the view graphiviz view, and mostly for small models. Generating a png I think would be hard to do from arbitrary DOM content. Also people can still hide the text (control-t) and even the menu if they want to make the image fill the screen, so making a separate tab would not have much benefit.

**Comment by WeiqiMaster** [comment]
When the diagram grows relatively large, display the full diagram is almost impossible without scrolling because users can't change the scale of each component. Currently, the only way to get a nice full image of the diagram is to generate the GraphViz diagram, but that option is hard to find. So I think adding a link that directs to .svg file at a more visible position would be great. And also change the "Photo Ready" function to be scrollable.

**Comment by TimLethbridge** [comment]
Fixed by issue #1557
