### ISSUE TITLE
Prevent "Download the following as a zip file" from disappearing

### ISSUE THREAD

**Issue by stevenli5** [umple/umple#1565]
## Specify a Brief Description

After generating Java Code, the "Download the following as a zip file" option disappears after selecting "Show Files in Separate Tabs" and unselecting it.

## Give the minimum Steps to Reproduce

1. Generate code under "Java Code" **Edit: This issue is consistent for all coding languages**
2. Here we see the "Download the following as a zip file" option
3. Check off the box for "Show Files in Separate Tabs"
4. Repeat step 3
5. The "Download the following as a zip file" option disappears

## Describe the expected result that didn't happen

![image](https://user-images.githubusercontent.com/60322211/84602798-deb4cc80-ae57-11ea-94e0-14ab4cc67a92.png)

## Actual Result

![image](https://user-images.githubusercontent.com/60322211/84602802-e6747100-ae57-11ea-9741-20d867a1a983.png)

## Labelling and Assigning

Component-UmpleOnline
Diffic-Easy
Priority-Low, as this problem can be fixed easily by regenerating the code.

**Comment by TimLethbridge** [comment]
Thanks @stevenli5 
Right. The download link should ideally reappear, or not disappear at all.
