### ISSUE TITLE
Certain code won't generate a valid Graphviz state diagram

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1596]
The code in the attached diagram fails to generate a valid state diagram. The reason is unclear. I had thought it may be due to complexity of the actions or guards, but even if display of these is switched off it does not display.

[umplefiles (1).zip](https://github.com/umple/umple/files/4902849/umplefiles.1.zip)

**Comment by WeiqiMaster** [comment]
This file seems to be fine. I just tried it on Firefox, Chrome and Command line. GvStateDiagram can be successfully generated without failure or warnings.

**Comment by TimLethbridge** [comment]
OK this problem exists on the server (which has an earlier version of dot installed). We are going to have to upgrade the server, but graphiviz can't be updated past version 1.39 there unfortunately until we upgrade Linux. It gives 
```
Error: trouble in init_rank
	%0 2
...
libpath/shortest.c:324: triangulation failed
libpath/shortest.c:192: source point not in any triangle
Error: in routesplines, Pshortestpath failed
out of memory
Segmentation fault
...

on the example in the file.  We will not attempt to fix this issue programmatically, but please in future test on the server as well if you can't reproduce a problem locally.
