### ISSUE TITLE
The UI of Umple on the Safari Web Browser differs from Google Chrome & a function is missing.

### ISSUE THREAD

**Issue by 1998Charles** [umple/umple#1597]
Dear Umple development team,

Good afternoon.
I found an issue in Umple regarding differences appearing by using different browsers, which are Google Chrome and the Safari Web Brower.

In the Safari Web Browser, the Tabbed Document Interface (TDI) function is unavailable. Moreover, the functional buttons are a bit crowed and distributed unnaturally.
However, in Google Chrome, everything seems to be perfect for me. 

My Safari Web Browser version is 13.1.1 (15609.2.9.1.2).
My Google Chrome version is 83.0.4103.116.

Additionally, I have another immature UI design suggestion. For my understanding, while Umple is trying to process works, it will temporarily ban some functional buttons by using Strikethrough. Instead of using Strikethrough, Umple might use some other styles, such as fading the texts of buttons and changing the colour of buttons. The reason is that when I initially saw the Strikethrough, I thought it was a little bug of failure to display multiple windows (I thought the Strikethrough was an edge of another window.)

Here are some screenshots.

<img width="1279" alt="Safari (web browser) 13 1 1 (15609 2 9 1 2)" src="https://user-images.githubusercontent.com/60756026/87181522-79b29200-c2b0-11ea-92b4-37f9ba6c3af8.png">
<img width="1278" alt="Google Chrome 83 0 4103 116" src="https://user-images.githubusercontent.com/60756026/87181530-7e774600-c2b0-11ea-9da5-ce6e4d6d8659.png">
<img width="1232" alt="Design Suggestion" src="https://user-images.githubusercontent.com/60756026/87181543-82a36380-c2b0-11ea-9027-3163c604758e.png">

Here is a Google Drive link in case of failure to upload these three screenshots.

https://drive.google.com/drive/folders/1ItcFeGiZ1UisQeLejJH_dic-CVjFv56N?usp=sharing

Incidentally, this is my first time to report an issue. Please excuse me and correct me if I made a mistake or have other immature behaviours.

Thank you very much for your hard work.
Stay safe and healthy.

All the best,
Xiaoxi Jia
xjia033@uottawa.ca
300000227

**Comment by TimLethbridge** [comment]
@1998Charles I use Safari 99% of the time, and I see the tabs present without a problem. Can you please check that it wasn't because you clicked on 'Toggle Tabs'? If you still can't get any tabs, then I will have to dig in whatever else is special about your setup.

Your point about the 'strikethrough' is an excellent one that has bothered me too. It would be much better if it was 'temporarily fade out to very light grey'. We will see if we can do that.

**Comment by 1998Charles** [comment]
Hello,

Thank you very much, Professor Lethbridge.

My apology.
I was able to see TDI after clicking the 'Toggle Tabs.'
I have one more small suggestion. It would be nice if we might add a 'status indicator' for the 'Toggle Tabs,' which could indicate whether the tabs are being 'Toggled' or not.

Thank you very much.

@TimLethbridge 

Respectfully,
Xiaoxi Jia
xjia033@uottawa.ca
300000227

**Comment by TimLethbridge** [comment]
I have queued commit with a fix for the strikethrough issue ... I have changed it to lowering the opacity, which looks much nicer. That will close the issue, since the other matters are dealt with.
