### ISSUE TITLE
Umple UI design suggestions about 'Toggle Tabs' 

### ISSUE THREAD

**Issue by 1998Charles** [umple/umple#1598]
Dear Umple development team,

I have two small UI design suggestions for the 'Toggle Tabs' switch.

1. It would be much more helpful for beginners to have a 'Toggle Tabs' indicator, which can indicate whether the switch is activated or not. For example, the fade-out effect, a textual sign or even a dot icon would be friendly and straightforward.

2. After the 'Toggle Tabs' switch activates, it might look better and straighter if some extra space would be added between the buttons and the main window.

<img width="1269" alt="BeforeToggling" src="https://user-images.githubusercontent.com/60756026/87203958-bc389680-c2d1-11ea-8520-25d2057a939c.png">
<img width="1266" alt="AfterToggling" src="https://user-images.githubusercontent.com/60756026/87203978-c35fa480-c2d1-11ea-877e-41e0ae340e8b.png">
<img width="1197" alt="MoreSpaceNeeded" src="https://user-images.githubusercontent.com/60756026/87203993-c8245880-c2d1-11ea-9ff1-938b1fadaa52.png">

I appreciate your listening and hard works.

Stay safe and healthy.

Best regards,
Xiaoxi Jia
xjia033@uottawa.ca
300000227

**Comment by TimLethbridge** [comment]
Having a few pixels of vertical space would be OK, but the whole idea behind 'toggle tabs' is to reclaim screen real estate that is not needed (for small devices). Having less blank space above this row of buttons might be good.

As for darkening or lightening, or changing 'show tabs', 'hide tabs', I think there is an outstanding PR on this. #1531 that I will try to merge soon, and that relates to #1517

**Comment by TimLethbridge** [comment]
The toggle tabs now says hide or show tabs, depending on the situation
