### ISSUE TITLE
Specify that a state machine should be generated with events in an event queue

### ISSUE THREAD

**Issue by Nava2** [umple/umple#160]
Originally reported on Google Code with ID 260
Owned by `msstraightway`

---

Add a keyword 'queued' before a state machine that would change how events work. Events
would be queued. This would generate slightly more complex code but would make the
code work in a multi-threaded environment.

See also issue 232

---

Reported by @umple on 2012-01-27 19:39:43

**Comment by Nava2** [comment]
Also see issue 162 " Add support for synchronized events methods".

---

Reported by @obahy on 2012-01-31 02:25:18

**Comment by Nava2** [comment]
Reported by @umple on 2012-02-15 17:40:08
- **Status changed**: `Accepted`
- **Labels added**: Component-Syntax

**Comment by Nava2** [comment]
See the new page in the private Umple wiki page http://cruise.site.uottawa.ca/wiki/index.php/CoreRealTimeConcepts
where we are speccing this out as part of thesis work.

---

Reported by @umple on 2012-06-14 21:55:03
- **Labels added**: Diffic-Med, realTime

**Comment by Nava2** [comment]
Reported by @umple on 2012-09-27 19:51:30
- **Owner changed**: `msstraightway`

**Comment by Nava2** [comment]
In addition to standard queued syntax, we also need:

pooled sm { ... }  - This would result in only taking messages from the queue where
there is a transition in the curent state

queued(n) {sm { ...} for a given state a certain number of inputs would
be saved for later (remaining in the queue) if they cannot be processed

---

Reported by @umple on 2013-02-07 17:39:37

**Comment by Nava2** [comment]
Reported by @umple on 2013-12-13 16:18:12
- **Status changed**: `MostlyDone`

**Comment by Nava2** [comment]
Pooled now committed as of r3519

---

Reported by @umple on 2014-02-20 20:33:59

**Comment by TimLethbridge** [comment]
This was completed long ago
