### ISSUE TITLE
Add an ability to specify guards on entry and exit actions

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1600]
Some users have assumed that guards can be specified on entry and exit. If they do this now, they just get an error message saying that the State Machine cannot be parsed. It might be good to allow them as syntactic sugar that is handled purely in parsing (hence this would an easy change).

On a transition, a guard, shown in square brackets, constrains whether or not the transition would be taken, and any associated action run. This issue suggests simply allowing a optional Boolean expression in square brackets that could follow the entry or exit keyword, that would be simply prepended to the entry or exit action. This would merely be syntactic sugar.

For example

The following code in should be allowed in Umple

```
       entry [power] / {display("Radiator is on at high power");}
       entry [!power] {display("Radiator is on at low power");}
```

It ought not to affect code generation, since during parsing the Boolean expression could just be prepended to the action with an extra {} block.

So the above would be equivalent to if the user had written, and indeed following parsing, the internal representations would be the same.

```
      entry / {if(power) {display("Radiator is on at low power");}}
      entry / {if(!power) {display("Radiator is on at low power");}}
```

The following is similar, but it is not quite as safe due to the lack of an extra set of curly brackets.

```
      entry / {if(power) display("Radiator is on at low power");}
      entry / {if(!power) display("Radiator is on at low power");}
```

The user could also write the following for the same effect, but don't try to generate like this.
```
       entry/ {
         if(power) display("Radiator is on at high power");
         else display("Radiator is on at low power");}
       }
```

When doing this, please add to the Umple user manual, and also make sure you include a couple of tests

**Comment by WeiqiMaster** [comment]
I think this treatment is not adequate as entry action can have a 'go to' state like following:
```
class X {
  sm {
    s1 {
      entry / {
        System.out.println("Starting first sleep");
      }
      -> s2;
    }
  }
}  
```
