### ISSUE TITLE
If a main class of an Umple file contains 'command = s.nextLine();,' running the CommandIssuer will throw an exception

### ISSUE THREAD

**Issue by 1998Charles** [umple/umple#1605]
If a main class of an Umple file contains 'command = s.nextLine();,' running the CommandIssuer will throw an exception
```
public static void main(String[] argv) {

  Scanner s = new Scanner(System.in);
  String command;

  while(true) {

    command = s.nextLine();
    
    switch(command) {

      case "q": System.exit(0);
          
      default:
        break;
    }
  }
}
```
```
command = s.nextLine();
```
For example,

<img width="616" alt="1" src="https://user-images.githubusercontent.com/60756026/88013352-30511680-caea-11ea-9d91-67d43528d03e.png">

```
java -jar CommandIssuer.jar 1:n c  | java Dishwasher
```
```
java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at Dishwasher.main(Dishwasher.ump:79)
```

<img width="626" alt="2" src="https://user-images.githubusercontent.com/60756026/88013408-524a9900-caea-11ea-918a-98f35339ad75.png">

```
java -jar CommandIssuer.jar 1:n c  | java Dishwasher
```
```
java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at Dishwasher.main(DishwasherWithDoorOpenSuspension.ump:118)
```
<img width="621" alt="3" src="https://user-images.githubusercontent.com/60756026/88013425-5bd40100-caea-11ea-912a-b97c7415cd83.png">

```
java -jar CommandIssuer.jar 1:n c  | java Oven
```
```
java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at Oven.main(Oven.ump:465)
```

**Comment by TimLethbridge** [comment]
This is not about Umple, but about an Umple Application called CommandIssuer. I will nevertheless look at it
