### ISSUE TITLE
Responsive adjustment of diagram pane sometimes results in it being misplaced on bottom

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1663]
If a window is readjusted, the and text diagram pane are supposed to change size. But at some sizes the calculations are incorrect and result in the diagram pane being placed below the menu, and a little to the right of centre (see screen shot).
![Screen Shot 2021-02-03 at 2 38 50 ](https://user-images.githubusercontent.com/479230/106800105-0eeeec80-662e-11eb-88b1-59f31a088985.png)

Below a certain width, the diagram appears below the text and full width (to accommodate phones and tablets), and this works fine.

**Comment by TimLethbridge** [comment]
This only seems to happen when the font has been enlarged (by doing command-- on a Mac (the default font/zoom state does not have the problem)

The problem is the same in Safari for Mac and Chrome and Edge for Mac.

**Comment by TimLethbridge** [comment]
The code that needs changing is in umpleonline/scripts/umple_layout.js

As resizing takes place it seems that perhaps there is one pixel too many in  the calculation of the width of the text pane, not leaving enough space left for the canvas pane

**Comment by TimLethbridge** [comment]
When testing to reproduce this or test a fix:

- Dynamically adjust the outer border of the window; all the internal parts of UmpleOnline should grow or shrink according to the logic in umple_layout.js When this bug is active, you may notice the diagram jumping from bottom to right side and back several times. If you shrink the window to be narrow the system should use its logic for small screen mode (search for isInSmallScreenMode. This may not have the bug, as the diagram is below anyway. But when widening the window again the diagram should once again appear on the left. 

- Dynamically adjust the border between the menu and the diagram area. Hover over that border and the cursor should change indicating you can adjust the split.

- Zoom in using the browsers controls (making all elements and fonts bigger). Then repeat the above tests. Zoom out and repeat. do this zooming in several increments. Zooming in is accomplished by control-+ or command-+ or various menus, depending on browser.

- Hide and reshow the text and diagram to make sure everything works (click on the T and D buttons near the top).

- Do all of these tests in Chrome and other browsers. Ultimately we want to check the solution in Safari, Edge, Firefox and Opera. Try downloading other browsers available in your operating system

**Comment by TimLethbridge** [comment]
To debug the javascript code, use Page.setFeedbackMessage() to output debug data to the screen. Or use catFeedbackMessage() to add to existing feedback.

**Comment by Svetlana154** [comment]
There is another bug that relates to the re-sizing of the panels and it only appears in one specific scenario:
<br/>If the body is using the Large Screen Manager (so the one where the text editor, the main menu and the diagram panel are all in one row), but the editors have yet to reach their required minimum width - 284px for the text editor and 420px for the diagram editor - they cannot be properly resized by hovering over their borders near the main menu. The editor's width ends up jumping in size, before returning back to its original width upon release.
<br/>This case can only occur if the user is adjusting the window size or zooming in/out to that stage.
<br/>
Proposed change: the users should not have the option to resize the editors while the panels do not meet the required minimum size
