### ISSUE TITLE
Add support for periodic prompting for survey response in UmpleOnline

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1695]
There is a need for a tool that would prompt an UmpleOnline user to please consider responding to a survey. This is needed for UX PhD student Reyhaneh Kalantari.

It would work as follows:

1. The survey would be in SurveyMonkey and would have a a predefined URL. This has been set up for the initial survey. The person working on this issue  would not need to worry about it.

2. Upon Umpleonline startup, it should look for a file aaSurvey.txt in the ump directory. This file would be in json format and would look like:
{
  InvitationalMessage: HTMLTEXT
  RecruitmentText: HTMLTEXT
  MinutesBeforePrompt: Integer
  RandomizedFrequency: Integer
  SurveyURL: Integer
}

3. If the aaSurvey.txt is present, then it will be read into an object with the relevant fields. Then the following will occur:

a) Check a cookie to see if this person has been contacted or has already been randomly skipped (as most are, see item b).

b) Only one in every RandomizedFrequency will be invited, so generate a random number between one and RandomizedFrequency. If the result is 1, then continue. Otherwise record in a cookie (that expires in 60 days) that this person will not be contacted for a survey, and stop.

c) In Javascript start a timer that will wait MinutesBeforePrompt time (we will be defaulting to 10 minutes initially, dropping to 5 if we don't get many responses). When the timer expires, display InvitationalMessage in the message area used for the aAlertMsg and tip of the day (replacing it if there is already one there, or already a tip of the day there).

d) If the user clicks on the invitational message, it will pop up a javascript box with the RecruitmentText. This will include a link that says 'Click here to start the survey'. If the user clicks, then SurveyURL will be opened in another tab (using the target attribute of the a html tag to ensure it goes to a new tab). 

e) The javascript box disappears as does the invitational message, and a cookie is set to say the person responded to the survey. The cookie should expire after 60 days.

**Comment by TimLethbridge** [comment]
Some familiarity with the completed 'task' capability and issue #1490 would be useful. That too jumps the user to a survey at the end.

**Comment by Svetlana154** [comment]
Situations to consider: what should be done when...
i) the cookie has already been set -- according to the comments above, display alert/totd
ii) the cookie has not been set, but the random number is not 1 -- user is skipped, display alert/totd
iii) the InvitationalMessage has been displayed but the user chooses not to click on it -- (TBD)
iv) after the pop-up, the user chooses to not click "Click here to start survey" -- (TBD)

I believe it would be better to **not** set the cookie in cases iii) and iv) to still give those users a chance to participate in the survey in their next session. However, since they already chose not to do it, perhaps it might be even more beneficial for a cookie to still be created (as if they skipped) but set the expiration day to something shorter than 60 days.

**Comment by TimLethbridge** [comment]
Alerts should always have priority; don't prompt for a survey if there is an alert. Survey is second priority. If the dice rolls in favor of a survey, then do it, otherwise fall back on totd. For item iii, I think set the cookie for only 15 days.  For option iv. I think set the cookie, but yes for maybe only 30 days.

**Comment by Svetlana154** [comment]
The feature should probably have 3 backdoor debugging commands (in the line number section of UmpleOnline):
1) "sp" -- Survey Pass - bypasses all conditions for the appearance of the survey message, sets the randomized roll to 1, MinutesBeforePrompt to 5 seconds, EditsBeforePrompt to 1 edit; it does not set surveyCookie or surveyShown afterwards (can be cleared/deactivated with the "sc" cmd)
2) "sr" -- Survey Roll - simply rolls 1 every single time and doesn't affect any other operations [DISCARDED]
3) "sc" -- Survey Clear - clears all cookies related to the survey: surveyCookie (expiration date of 15, 30, 60 days), surveyShown (if surveyURL has already been visited by that specific user), surveyPass

**Comment by Svetlana154** [comment]
The JSON file that seemed to work for me:
```
{
  "InvitationalMessage": "The Umple developers would like to invite you to participate in a user experience survey. Click here to open in a separate tab",
  "RecruitmentText": "<p>We would appreciate it if you could take 10 minutes to give us some feedback about your experience while using UmpleOnline.</p><p>Your answers will help us evaluate the usability of the system and ultimately improve it. The project title is: 'Flow Experience in a Software Modeling Tool: Umple'</p><p>The survey is being conducted by Reyhaneh Kalantari, a Ph.D. student at the University of Ottawa, as part of her thesis work. You have been randomly selected to participate from among those working with UmpleOnline.<br/>No data gathered will result in you being identifiable, and your responses will remain confidential. There are no known risks to participating in the survey.</p><p>If you have any questions about this study, please contact the investigator at <a href='mailto:Reyhaneh.Kalantari@uottawa.ca' target='mailoriginator'>Reyhaneh.Kalantari@uottawa.ca</a></p>",
  "EditsBeforePrompt": 10,
  "MinutesBeforePrompt": 5,
  "RandomizedFrequency": 10,
  "SurveyURL": "https://www.surveymonkey.ca/r/NJPMXQZ"
}
```

Please ensure the format remains the same for all aaSurvey.txt files and that there are no "Enters" within a string value (use `<p>` tags or \n)
