### ISSUE TITLE
Remove task creation panel when not required in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1697]
## Summary

Within the UmpleOnline, the users can create a task by providing the necessary details. In a sample scenario, a user can start creating a task and then decide to skip the process at any point in time. But the system does not provide a **Discard or Cancel** button to cancel the operation.  Even if the user starts browsing different features, the "create task" section stays at the top of the page.

## Steps to Reproduce

1. Click the "Tasks" menu item and then click "Create a Task".
![image](https://user-images.githubusercontent.com/82404135/118448589-2a9f6f80-b6c0-11eb-9f92-19be734a573a.png)
2. There will be a task creation section at the top left corner of the page.
![image](https://user-images.githubusercontent.com/82404135/118449080-c03aff00-b6c0-11eb-901b-539c5e9f7d67.png)
3. There is only a "Submit Task" button. There should another button (Cancel or Discard) to cancel the creation of that task if the user has changed his/her mind and does not want to save it.

## Expected Feature

There should a button (with the name "Cancel") to cancel the operation if the user does not want to save the task and move on to the next action. The new button should be added on the right side of the "Submit Task" button. There should be some space in between the two buttons to avoid accidental user-level (click) errors.

**Comment by TimLethbridge** [comment]
This is a high-priority change. The button should say 'Cancel task creation'
