### ISSUE TITLE
Copy to clipboard option does not work in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1702]
## Summary

Within the UmpleOnline, the users can generate code (e.g. Java, C++, etc) based on the models. In a sample scenario, a user can create a model and generate the source code accordingly. The user wants to copy the whole source code by clicking an easily accessible "Copy to clipboard" button. UmpleOnline provides that copy button but it is not functional. 

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
2. Under the "Generate" section, select the target programming language as "Java Code".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/118454167-12325380-b6c6-11eb-830d-2b5bd6b2daf0.png)
3. At the right corner of the source code section, there is an icon to copy the code to in the clipboard.
![image](https://user-images.githubusercontent.com/82404135/118470333-98559680-b6d4-11eb-824a-2b6f4a42d40d.png)
4. Now, click on that icon. Nothing happens if the user clicks on it.

## Expected Feature

The system should allow copying source code when the user clicks on the "Copy to clipboard" button. There is a similar functionality already implemented under the "source code" icon which only views the source code. Additional internal copy state is required.

**Comment by TimLethbridge** [comment]
Yes, this should either be removed or made to work. This feature was already turned off in the user manual because it would found not to work properly, maybe due to changes in security requirements of browsers.

This relates to the SyntaxHighlighter dependency. Be careful about changing SyntaxHighlighter, since there can be subtle bugs introduced. Any chanve here would require extensive testing.

**Comment by TimLethbridge** [comment]
Check out the control-o function that copies the code plus some unix/linux/mac shell commands that can be used to compile. We need to leave the function as is, but maybe calling this feature with an argument that doesn't include the shell stuff and only the stuff from ENDUMP to ENDUMP would work
