### ISSUE TITLE
Users find it hard to figure out how to rename a Model Tab in UmpleOnline -  add tips

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1704]
## Summary

Within the UmpleOnline, the users can create multiple tabs (worksheet) and work on separate models at each of the tabs. While opening a new tab, the system automatically assigns a generic name (untitled{NumberPostfix}) for that tab and there is no option to set the name of TAB according to the user's code saved under that worksheet. 

While working on more than two TABs, users need either to memorize the position of the TABs or click one after another to find a specific tab.

## Steps to Reproduce

1. Click at the plus (+) sign right side of the first tab. Repeat this three more times.
2. There will be four tabs in total. Each of the tabs has system-defined generic names.
3. Single or Double click at the Tab to rename it. Try any action to rename the tab to a custom name.
![image](https://user-images.githubusercontent.com/82404135/118480447-4286eb80-b6e0-11eb-9545-1d8cce13ac4e.png)

## Expected Feature

The system should allow renaming the tabs according to the user's preference. Users should be able to change the name at any point in time.

**Comment by TimLethbridge** [comment]
Double-clicking on a tab allows renaming easily, so this issue is not fully accurate

Perhaps single-clicking should work. 

At the very least there should be a tip to help users figure that out. Maybe hovering over a tab should say 'Double click to enable renaming'.
