### ISSUE TITLE
Selected top menu items should be highlighted in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1705]
## Summary

Within the UmpleOnline, the users can switch the page layout and change the diagram options. Users can click at any of the letters ("E", "G", "T", "D", etc.) at the top left corner to view and retain the change. Once clicked at any of these letters and the mode is changed, the system does not highlight the current selection. The system should highlight the current selection of letters (mode) so that the users are always aware of the mode that they are working on.

## Steps to Reproduce

1. Click at any of the letters in the top left corner.
![image](https://user-images.githubusercontent.com/82404135/118481671-b8d81d80-b6e1-11eb-996b-884facea8974.png)
2. Multiple modes have been toggled but no mode is highlighted. The system does not explicitly show the current selection set of modes.

## Expected Feature

The system should highlight the current selection set to explicitly display the user's mode.

**Comment by TimLethbridge** [comment]
Please explain more clearly what is being requested here. If in a mode, the letter is darker, highlighting it. What else is being requested?

**Comment by TimLethbridge** [comment]
This issue really now is to change the style of active buttons so they are a little darker, but not as dark as when hovered over, while retaining the same hue.
