### ISSUE TITLE
Task names that have uppercase letters do not work on Linux servers: Need to convert search string to lowercase

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1712]
If you create a task in UmpleOnline and include an uppercase letter, it will work fine on a Mac or Windows filesystem. But on a Linux filesystem users will not be able to find it unless they enter the task name in all lowercase.

For example if a task is created as TiTask999 (which exists on the main server, which runs on Linux) then users will not be able to find it if they type that. They would have to type titask999. The reason is that the directory name created for the task in the ump/tasks folder contains the filename as lowercase (this was deliberate to in fact prevent accidental creation of tasks that have lower and upper case variants that are different).

The solution: When searching for a task, convert the search string to lowercase first.

The relevant code for this would appear to be in the block starting around compiler.php line 110, where it gets the taskname from a directory entry and then compares it to the filename argument (which is just a task name and could have uppercase letters). The argument ought to be converted to lowercase first.

This will need testing on several platforms.

**Comment by RalphNgassa** [comment]
Issue seems to be fixed, updated files are available at 'issue1712_load'

**Comment by TimLethbridge** [comment]
Yes, do a pull request and I will close this issue when I merge it. I tested it on the main server. Bravo for finding both places where the change was needed.
