### ISSUE TITLE
Show/hide tabs should not be present in Umple internal representation generator results

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1719]
## Summary

Within the UmpleOnline, the users can generate code (e.g. Java, C++, Internal Umple Representation, etc) based on the modeling language. In a sample scenario, a user can create a model and generate the source code accordingly. Based on the viewing preference, the user can check the "Show Files in Separate Tabs" or not. If the user checks that box, then the entire source is encapsulated in separate tabs where each tab contains its own code.

If a user generates the source code for "Internal Umple Representation" and tries to see the result in separate tabs, the source code section vanishes. It does not show anything.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
2. Under the "Generate" section, select the target programming language as "Internal Umple Representation".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119898031-418b6080-bf0f-11eb-8d65-4e7fec5f90b9.png)
3. Scroll a bit down and check the box with the text "Show Files in Separate Tabs".
![image](https://user-images.githubusercontent.com/82404135/119898134-6aabf100-bf0f-11eb-8e57-c040563cda5a.png)

As soon as the user clicks the checkbox, the source code disappears. It shows no tab either.

## Expected Feature

When the checkbox is checked, the source is expected to be separated into multiple tabs according to the encapsulation logic.

**Comment by TimLethbridge** [comment]
Actually, the 'show files in separate tabs should not appear at all in the case of certain generators like this one that are not generating separate target language files. This should be a quick fix. Look at all other generators too for a similar problem
