### ISSUE TITLE
McCabe Metrics total is not showing the label Cyclomatic Complexity nor explanation of computation

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1721]
## Edit

The original issue below is incorrect; it has referred to the 'Sum' column and the person raising the issue assumed this means that column should show the Conditions plus Iterations. However that was never the intent. The 'Total' Column, should simply be changed to 'Class diagram Cyclomatic Complexity'. But further analysis is needed to understand the numbers and to add some explanation tips to them.

## Summary

Within the UmpleOnline, the users can analyze the source code. In a sample scenario, a user can create a model and analyze the code by LLOC, and McCabe metrics. Based on the comparison preference, the user can check any metrics or statistics. 

For "McCabe Metrics", the user can expect the "Total" line to be the SUM of # of Conditions and # of Iterations. But the total line is displayed as = (number of Conditions + number of Iterations + 1)

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "Code Analysis".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119900560-b01ded80-bf12-11eb-9653-ac4b61a976eb.png)
3. Scroll a bit down and see the "McCabe Metrics".
![image](https://user-images.githubusercontent.com/82404135/119900653-cfb51600-bf12-11eb-939a-d00d0c233880.png)

For a class "Watershed" which has two conditions, and zero iterations, the total is displayed as three.

## Expected Feature

The system can have any of these two expected features.

1. The system should have a hovering effect on the "Total" column to display how the value has been calculated. 
2. The system should have a URL to direct the users to a detailed McCabe Metrics calculation method.

**Comment by TimLethbridge** [comment]
The relevant code is in generators/Generator_CodeAnalysis.ump:374
