### ISSUE TITLE
Generate dropdown resets to Java with the change of example dropdown in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1722]
## Summary

Within the UmpleOnline, the users can generate code (e.g. Java, C++, USE model, etc) based on the modeling language. In a sample scenario, a user can create a model and generate the source code accordingly.

If a user generates the source code in "Ruby Code" programming language for a given example and tries to change the example dropdown to another value, the system automatically resets the programming language to "Java Code". Although the user's previous selection was "Ruby Code" as a programming language, the system ignores it and the user needs to re-select the programming language again.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "Ruby Code".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119902872-d4c79480-bf15-11eb-9700-40784634208f.png)
3. Now change the example dropdown value to "Airline" and go down to the generate dropdown.
![image](https://user-images.githubusercontent.com/82404135/119903016-11938b80-bf16-11eb-869b-a422cf756ac9.png)

The generate dropdown has been reset to "Java Code" again. Although the user wants to use the previous programming language preference (Ruby in that case), the system forcefully resets it to Java. Therefore the user should have to select the programming language again.

## Expected Feature

The system should retain the last value of the "Generate" dropdown. It should not change with the change of the "example" dropdown value. A similar implementation is available for the "diagram type" dropdown. The "Generate" dropdown does not change with that.

**Comment by TimLethbridge** [comment]
This would be a very important change. I have often found it annoying, when I want to compare outputs of several examples, that it jumps back to Java (or C++ in the case of composite).
