### ISSUE TITLE
State machine measures has a difference in column name and column description in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1723]
## Summary

Within the UmpleOnline, the users can generate statistics (e.g. Simple Metrics, Code Analysis, etc) based on the modeling language. In a sample scenario, a user can create a model and check the metrics accordingly.

There is a column naming "#Cycles" in "State Machine (SM) Measures". But the description of that column has a different name with different details. Moreover, it explains a formula to find the total of cycles = self cycles + cycles.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "Simple Metrics".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119924838-503f3b00-bf42-11eb-9f5c-d999b6de21d3.png)
3. Scroll a bit down and navigate to the section "State Machine (SM) Measures".
![image](https://user-images.githubusercontent.com/82404135/119924991-9a282100-bf42-11eb-80d9-72f9074345db.png)

The description has a different specification than the column in metrics (#cycle).

## Expected Feature

The description should have the specification of metrics column naming "#cycle".

**Comment by TimLethbridge** [comment]
This would be a trivial fix. The Legend for the second last line should simply be changed to say:

```
#Cycles - Total of cycles: Self cycles plus cycles that include two or more states
```

Also, change the last line to say 
```
#self Cycles - The number of transitions that start at a state and end at the same state 
```

**Comment by RalphNgassa** [comment]
The compiler code needs to be modified to fix this issue.

**Comment by TimLethbridge** [comment]
Yes, I know the compiler code needs to be modified, but it should still be easy
