### ISSUE TITLE
Download option at Yuml Class Diagram does not provide a proper return back in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1725]
## Summary

Within the UmpleOnline, the users can generate the Yuml class diagram based on the modeling language. In a sample scenario, a user can create a model, generate the Yuml class diagram, and download it.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "Yuml Class Diagram".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119928552-c8f5c580-bf49-11eb-892f-223846e7fc75.png)
3. Scroll a bit down and click on the "Download the PNG file for the image" linked text URL.
![image](https://user-images.githubusercontent.com/82404135/119928688-14a86f00-bf4a-11eb-97b8-34f21dc2b233.png)
4. The system loads the diagram in PNG format.
![image](https://user-images.githubusercontent.com/82404135/119928775-3e619600-bf4a-11eb-9d55-25c195ce1627.png)
5. Now, there is no system-generated BACK button to go back to the previous page. The only option to go back is to click on the browser BACK button. If the user clicks on the browser back button, the system is reset to an empty page. All the previous changes are deleted.
![image](https://user-images.githubusercontent.com/82404135/119928931-95676b00-bf4a-11eb-88ec-e7e42b6fb409.png)

## Expected Feature

The system should do any of the following-
1. Open the PNG image in a separate window.
2. Upon clicking on the browser back button, the system should return to the previously saved page.

**Comment by TimLethbridge** [comment]
This browser-specific behaviour. In Safari the behaviour is not as described: The back button works fine. The behaviour as described (back button reloads a fresh empty UmpleOnline) in Chrome,

Solution: The download links should always go to a separate tab. using the   target="YmlImage"   in the "a" link. This should happen for *all* download links in the system, for the same reason, so both download Yuml text and download PNG file here.
