### ISSUE TITLE
JSON is not displayed at proper format in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1727]
## Summary

Within the UmpleOnline, the users can generate the JSON output based on the modeling language. In a sample scenario, a user can create a model, generate the JSON, and view it.

The JSON returned by the system is completely in RAW text. No formating or indentation is applied to the output.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "JSON".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119938504-838dc400-bf5a-11eb-83f4-3de47a9e39fa.png)
3. Scroll a bit down and check the JSON output. The JSON does not have the output standard formatting or indentation
![image](https://user-images.githubusercontent.com/82404135/119938607-addf8180-bf5a-11eb-968b-aaa5c311fd1e.png)
4. Moreover, if the user clicks on the "Show Files in Separate Tabs" checkbox, the complete JSON output disappears. 
![image](https://user-images.githubusercontent.com/82404135/119938899-13337280-bf5b-11eb-9f85-2286f9c4a7eb.png)

## Expected Feature

1. The JSON output should have some indentation by each node.
![image](https://user-images.githubusercontent.com/82404135/119939069-483fc500-bf5b-11eb-9afb-cea85647f7e4.png)
2. If a user clicks on the "Show Files in Separate Tabs" checkbox, the system should show the JSON.

**Comment by TimLethbridge** [comment]
Yes. This should be fixed. Although the Json is only partial as it stands, and won't for example, generate anything for state machines. The usefulness of this feature is questionable, hence I am giving this low priority, although the fix should be super quick.

**Comment by RalphNgassa** [comment]
I commited my work, the generated json code should now be displayed with the proper indentation.
