### ISSUE TITLE
Start Over button resets the workspace to initial state without proper hover/popup message in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1749]
## Summary

Within the UmpleOnline, the users can UNDO and REDO to go back and forth in between two code revisions. But, in a sample scenario, a user can also erase all the changes in the workspace (editor and diagram) in a single click. Once clicked, there is no option to get back the erased code. The system does not mention this in the hover tooltip or any confirmation pop-up message.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> "2DShapes".
![image](https://user-images.githubusercontent.com/82404135/119940965-f64c6e80-bf5d-11eb-8942-809a807ffdc5.png)
2. Do any change in the code window or design window.
![image](https://user-images.githubusercontent.com/82404135/121869277-e0fe7080-cccf-11eb-807e-663cb938e1e0.png)
3. Now hover your mouse at the SAVE & LOAD >> Start Over.
![image](https://user-images.githubusercontent.com/82404135/121869583-30dd3780-ccd0-11eb-9baa-88bea7c43547.png)

There is no way to get the previous code back if the button is clicked once. Moreover, the button hover message does not display the appropriate message.

## Expected Feature

The system should display a hover message - "Click to clear the text editor and diagram. Once clicked, all of your saved works will be lost."
The system can also have an additional pop-up to get confirmation from the user if he/she understands the impact of clicking this button.

**Comment by TimLethbridge** [comment]
The Start Over buttom was placed there to deal with situations where the environment gets completely corrupted and the user needs a new environment. The 'Restore Saved State' should then allow restoring.

My suggestion for this is the following:

1. Change the tool tip on "Start Over' to say "Refresh UmpleOnline completely. The text and diagram will also disappear a blank model will be present. You will not be able to use the 'undo' to restore, but a 'Restore Saved State' will appear for a short while to allow you to recover your work. Use this only if UmpleOnline starts giving problems"

2. Add above 'Start Over' another button that says 'Load blank model'. This would just load an empty model as though it was an example, the undo would function as normal then. It would have the same effect as selecting the all text and hitting delete, but would also clear out any hidden layout.  The tool tip would say. "Load empty text and diagram to start a fresh work. You will still be able to use 'undo' to go back to what you currently see, but save your model first if it matters to you"

3. On the original "Start over" button when selected make it display below it text "Click here to completely refresh UmpleOnline" (this would be non-modal and only clicking on that new link would actually do what Start Over currently does.
