### ISSUE TITLE
Pinch to Zoom does not have a hover message in UmpleOnline 

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1752]
## Summary

Within the UmpleOnline, the users set preferences. There are three preferences to set within the system. The system does not display a hover tooltip message when the mouse is on "Pinch to Zoom" while it shows the details for the other two preferences (Photo Ready, Manual Sync).

## Steps to Reproduce

1. Click the "Options" menu item, and take the mouse on "Pinch to Zoom".
![image](https://user-images.githubusercontent.com/82404135/121876730-da73f700-ccd7-11eb-8c3c-a0765bb95a86.png)

The system does not display a hover tooltip with a detailed message.

## Expected Feature

The system should display an appropiate hover message.

**Comment by TimLethbridge** [comment]
This should say "When selected the diagram will be redrawn and then the user can adjust its size using pinch gestures (such as two fingers moving together and apart on a trackpad or touchscreen without affecting the whole interface), the disadvantage is that the diagram may not be positioned perfectly this can make it difficult to zoom the whole tab."
