### ISSUE TITLE
Traits diagram option does not have a hover message in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1756]
## Summary

Within the UmpleOnline, the users can select "show view" options within the window according to their preference. The system does not display a hover tooltip message when the mouse is on "Traits" while it shows the details for the other five preferences (Diagram, Text Editor, etc).

## Steps to Reproduce

1. Click the "Options" menu item, and take the mouse on Show View >> "Traits".
![image](https://user-images.githubusercontent.com/82404135/121881629-89670180-ccdd-11eb-905b-6bb67475068c.png)

The system does not display a hover tooltip with a detailed message.

## Expected Feature

The system should display an appropriate hover message. It should also mention the shortcut keys to perform this action.

**Comment by TimLethbridge** [comment]
The message should be: "Show/hide traits; when selected any traits and their relationships are explicitly shown; when unselected, traits are merged into their client classes"
