### ISSUE TITLE
Diagram does not auto-refresh when a user corrects an error at the same line without any backspace UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1757]
## Summary

Within the UmpleOnline, the diagram is auto-refreshed as soon as the user types some code at the code editor. In a sample scenario, when the user faces any error and rectifies that error at the same line without typing a backspace or newline, the system stops auto-refreshing the diagram.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> "Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119940965-f64c6e80-bf5d-11eb-8942-809a807ffdc5.png)
2. Add an erroneous line in the WorkersOnSurvey class exactly as shown. See the example below where the ending "semicolon" is missing.
![image](https://user-images.githubusercontent.com/82404135/121884193-a0f3b980-cce0-11eb-9299-605ed8654e69.png)
3. The system has returned an error. Now, add a semicolon and wait for the system to refresh the diagram automatically.
![image](https://user-images.githubusercontent.com/82404135/121884475-f6c86180-cce0-11eb-82e9-d9ed2b9b8ef1.png)

The system does not refresh the diagram automatically and still shows the error message.

## Expected Feature

The system should refresh the diagram when the user finishing a statement (for example, typing a semicolon);

**Comment by TimLethbridge** [comment]
This only occurs in very special situations. In this case, when there is a key following an erroneous attribute. So in the example case, it looked as though the sinble line said

```
Date date_dob key {id}
```

The real issues here is why the edit to add back the semicolon did not trigger a recompilation. Recompilation does not occur if a comment is edited, so it is possible that the same logic is causing the problem,

This issue needs to be explored with other examples to see if it is more general.
