### ISSUE TITLE
Java API Doc does not provide class details in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1759]
## Summary

Within the UmpleOnline, the users can generate "Java API Doc" for an example or custom umple code. While displaying the documentation, the system does not display the class level details. The respective TAB does not work.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> "2DShapes".
![image](https://user-images.githubusercontent.com/82404135/119940965-f64c6e80-bf5d-11eb-8942-809a807ffdc5.png)
2. Select Generate >> Java API Doc. Click "Generate It"
![image](https://user-images.githubusercontent.com/82404135/121889736-98eb4800-cce7-11eb-8915-f3361fb51962.png)
3. Scroll a bit down and click at the "CLASS" tab.
![image](https://user-images.githubusercontent.com/82404135/121889844-b3bdbc80-cce7-11eb-85f6-916fa8fa0199.png)

The CLASS tab is not clickable. The other tabs (TREE, INDEX, etc) display the respective information while that particular tab does not work.

## Expected Feature

The system should display the class-related information when clicked on the "CLASS" tab.

**Comment by TimLethbridge** [comment]
This is not an issue with Umple, it is an issue with Javadoc. It needs fixing there See for example 

https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/package-summary.html

(this is package information about Java strings)

I am marking this as will not fix and will close it
