### ISSUE TITLE
Selecting examples from the Umpr Repository brings up a 404 error page

### ISSUE THREAD

**Issue by Svetlana154** [umple/umple#1764]
Selecting "Composite Structure" from the Tools section in UmpleOnline and picking the "Select from Umpr Repository..." option, immediately brings the user to a 404 error page, instead of the Umpr Repository. 
<br/>Consider the pictures below for clarification:<br/>

![image](https://user-images.githubusercontent.com/71353118/122249192-a3980f80-ce96-11eb-8f5b-341547f9c6c2.png)
Selecting the example
<br/>
![image](https://user-images.githubusercontent.com/71353118/122249822-28832900-ce97-11eb-991b-a8fb222ecd19.png)
The 404 error page

**Comment by TimLethbridge** [comment]
We either need to enable the umpr repository to give something other than a 404 error if it is entered with diagram-type=composite (perhaps it could just show 'no examples found', or alternatively (and perhaps an easy solution) would be not to display the umpr option in the case of Composute structure.

**Comment by TimLethbridge** [comment]
This was fixed.
