### ISSUE TITLE
A Class Name Consisting of More Than One Word on the Joint.js Diagram Causes an Infinite Generation of Errors

### ISSUE THREAD

**Issue by Svetlana154** [umple/umple#1791]
When the user edits the class name on a Joint.js diagram or in the text editor (when the Joint.js diagram type is chosen) with more than 1 word, the event triggers an infinite generation of error messages in the text editor.  Changing the diagram type or selecting a different example doesn't stop the error messages and it seems like refreshing the page is the only option the user is left with.
<br/>Consider the picture below for reference:

![image](https://user-images.githubusercontent.com/71353118/124953511-384be400-dfe3-11eb-9c1a-f4219f1d8960.png)

<h2>Proposed Change </h2>

The program should probably react in the same manner as the Editable Class diagram, where a single message appears on top of the diagram panel to notify the user that their edit causes an error. Refer to the screenshot below:

![image](https://user-images.githubusercontent.com/71353118/124954667-536b2380-dfe4-11eb-8ac6-a5bdb42f0e7d.png)

**Comment by TimLethbridge** [comment]
Closing because I don't want to do further work on joint.js
