### ISSUE TITLE
Hello world example in C++

### ISSUE THREAD

**Issue by dragondive** [umple/umple#1797]
## Brief Description

The Getting Started page on the Umple site says: 
> Add UML modeling constructs directly into your programs, when you are programming in Java, PHP, **C++** or Ruby

As I understand this, it means Umple should also be able to compile "pure" C++ code. [I only started using Umple a few days ago, so my understanding may be incorrect. In that case, how do I add modeling constructs directly into C++ code?]

The Hello World Examples page also shows a Java code example, which I could compile successfully with Umple. However, when I try to create a similar Hello World example for C++, it fails to compile. 

## Minimum Steps to Reproduce

This is a **minimum** test case to validate the problem. 

1. Write a Hello World C++ program like below (for example, in a file named `helloworld_cpp.ump`):

```
#include <cstdio>

int main()
{
    printf("Hello World!");
}

```
2. Attempt to compile it with Umple on the command line as below:

`java -jar umple.jar helloworld_cpp.ump`

## Expected Result

Code compiles successfully.

## Actual Result

Compiler error:

```
Error 1503 on line 1 of file 'helloworld_cpp.ump':
Parsing error: #include, did you mean class
Processed helloworld_cpp.ump.
```

**Comment by TimLethbridge** [comment]
We need to clarify the documentation here. And test with the use of depend to ensure it is converted to include. Some hello world examples for different languages would also be useful

**Comment by dragondive** [comment]
> We need to clarify the documentation here. And test with the use of depend to ensure it is converted to include. Some hello world examples for different languages would also be useful

Thanks for your response, Tim. Does this mean C++ is not presently supported? 

I want to do a demo of Umple to my colleagues. I would like to include both Java and C++ examples, if this is possible.

**Comment by TimLethbridge** [comment]
There are hello world examples in the user manual for Java and Python. We should include cpp too ...

**Comment by TimLethbridge** [comment]
@dragondive Thanks for this issue ... we hope it is now resolved ... with improvements to the user manual and examples. The C++ generator is still beta, but it is being actively worked on.
