### ISSUE TITLE
Create task option is unavailable when a task response is submitted in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1817]
## Summary

Within the UmpleOnline, the users load a task and submit the response. Once the task response in submitted, the system has no option to create a new task. It only shows the "Load a task" option under the "TASKS" section. Therefore, the user is forced to reload the home page in browser to create a new task.

## Steps to Reproduce

1. Go to the "TASKS", then click on the "Load a Task". Type "test" in the box and click "Load Task".
![image](https://user-images.githubusercontent.com/82404135/128378300-502752be-99d2-49f3-9304-3de4eac6f9e4.png)
2. Click at the "Submit Response" button. Then click "OK" to confirm the successful submission.
![image](https://user-images.githubusercontent.com/82404135/128378611-20bb4a08-420d-480d-9b2e-4fb9eef6a61c.png)
3. Now, go to the "TASKS" again and try to create a task. The "Create a Task" option is not available. No visible way to get this option back. User needs to reload the umpleonline home page, and go to the TASKS again to get this option back.
![image](https://user-images.githubusercontent.com/82404135/128378892-68d535a2-76d8-4a01-aca6-855557be460c.png)

## Expected Feature

The system should display this option after a response is submitted. A similar workflow is implemented when clicked on "Cancel this task response".

**Comment by TimLethbridge** [comment]
This is deliberate. The system is in read-only mode after submitting the work. We don't want them to be able to change anything. It certainly makes no sense to create a task out of this while in read only mode.

However, there would be some value, as with issue  #1820 in having a button that would be labelled 'Exit task submission', and would take the user to a completely normal UmpleOnline state, with the same model (not associated with a task submission), from which they could then do anything, including submitting a new task.
