### ISSUE TITLE
No option to cancel the Task Create Panel after a task is created in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1820]
## Summary

Within the UmpleOnline, the users can create a task and save it. Once the task a saved, the system has no option to cancel this panel. Moreover, it does not show the "Load a task" option under the "TASKS" section. Therefore, the user is forced to reload the home page in browser to create a new task.

## Steps to Reproduce

1. Go to the "TASKS", then click on the "Create a Task". 
![image](https://user-images.githubusercontent.com/82404135/128386311-5d59de04-6769-4e9d-9e9d-fa36cb3c535f.png)
2. Enter a sample value at task name and instructions. Click "Submit Task".
![image](https://user-images.githubusercontent.com/82404135/128386666-391c6f39-33c7-428c-af22-9d3fd1904922.png)
3. Now, there is no option to hide this task creation panel. This panel is visible at every action that the user does.
![image](https://user-images.githubusercontent.com/82404135/128387177-0892a0aa-4b2e-49d7-aeff-ca88b44286e9.png)

## Expected Feature

The system should have a option to close this panel after a task is saved. A similar workflow is implemented when clicked on "Cancel this task response".

**Comment by TimLethbridge** [comment]
Yes, add a button on this panel: Exit task editing mode. See also #1817 for a related issue that could be done at the same time
