### ISSUE TITLE
Draw option in State Machines invalidates the diagram in UmpleOnline 

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1824]
## Summary

Within the UmpleOnline, the users can write code and generate the equivalent "State Machines" diagram. Unlike some other drawing options (Association, Generalization, etc.), "Class" drawing option is enabled and the users can drag and drop the "Class" component at the design pane. Once dropped, the existing design becomes invalid.

## Steps to Reproduce

1. Go to the "TOOLS", then select the "State Machines" from the dropdown. Select an example "Agents Communicating".
![image](https://user-images.githubusercontent.com/82404135/128395919-0c631653-ba4d-4794-bdfd-99a36dfd483b.png)
2. Look at the diagram pane. It will display the related state machine diagram.
![image](https://user-images.githubusercontent.com/82404135/128395981-37d14ba6-1f9a-4582-95d1-f7943c7b3cf7.png)
3. Now, click on the "Class" icon under the "DRAW" section and drag it into the design pane. Drop it.  
![image](https://user-images.githubusercontent.com/82404135/128396186-d8d8e55f-49d1-43a0-826e-232452db8108.png)
4. The previous state machine diagram vanishes.

## Expected Feature

The system should disable drag and drop option of "Class" control while in "State Machines". It would be better to hide these drawing options if drawing is not permitted in design pane.

**Comment by TimLethbridge** [comment]
This problem was fixed months ago. I am unable to reproduce this. It seems to work just fine in Safari for the Mac.

I have also tried it in Edge and Chrome and Firefox. Works fine there too.

Maybe there are circumstances where this in fact is a problem, but in that case the exact sequence leading up to the bug needs to be checked. Maybe it is a problem on Windows or Linux browsers.

**Comment by shoevancar** [comment]
I have tested this for four major browsers. Chrome, Safari, Edge, and Firefox. I could not re-produce this issue for any state machine. 
I would request to close this issue.
