### ISSUE TITLE
Selection from Umpr Repository option does not work in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1826]
## Summary

Within the UmpleOnline, the users can display a model in composite structure. There are a set of example available for user's understanding. When the users want to select a model from "umpr repository", the system crashes.

## Steps to Reproduce

1. Go to the "TOOLS", then select the "Composite Structure" from the dropdown. Select an example "Select from Umpr Repository".
![image](https://user-images.githubusercontent.com/82404135/128398761-8daf20d7-0c0b-45a0-8871-55f45968efc2.png)
2. Look at the window now. The system will redirect to 404 NOT FOUND error page.
![image](https://user-images.githubusercontent.com/82404135/128398899-cb60020d-2c11-49de-b368-a2539b1658b2.png)

## Expected Feature

The system should display the composite structure diagram without any error message for examples.

**Comment by TimLethbridge** [comment]
There are no examples of composite structure in the Umpr repository. This menu item should not appear for composite structure.
