### ISSUE TITLE
Feature Dependencies of BerkeleyDB SPL example does not work in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1827]
## Summary

Within the UmpleOnline, the users can display a model in feature diagram. There are a set of example available for user's understanding. When the users want to select an example with name "Feature Dependencies of BerkeleyDB SPL", the system crashes.

## Steps to Reproduce

1. Go to the "TOOLS", then select the "Feature Diagram" from the dropdown. Select an example "Feature Dependencies of BerkeleyDB SPL".
![image](https://user-images.githubusercontent.com/82404135/128400745-f8e23e44-61e0-42d1-9ed9-31f87eb3a465.png)
2. Look at the window now. The system returns error from umple compiler.
![image](https://user-images.githubusercontent.com/82404135/128400830-b546368f-2c5d-47bd-860d-2a997ebd270e.png)

## Expected Feature

The system should display the feature diagram without any error message for example models.

**Comment by TimLethbridge** [comment]
Reported for an urgent fix to the developer @gublan24

**Comment by TimLethbridge** [comment]
I did not mean to close it earlier.
