### ISSUE TITLE
Create task returns invalid instructions after saving in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1828]
## Summary

Within the UmpleOnline, the users can create a task and save it. Once the task a saved, the system displays the information of saved task at the same task panel. The system returns the details of a different task once it saves a task. It shows a details of previously saved task.

## Steps to Reproduce

1. Go to the "TASKS", then click on the "Create a Task". 
![image](https://user-images.githubusercontent.com/82404135/128386311-5d59de04-6769-4e9d-9e9d-fa36cb3c535f.png)
2. Enter a sample value at task name (testTask10) and instructions (test value as example) . Click "Submit Task".
![image](https://user-images.githubusercontent.com/82404135/128403060-61a86cd4-459b-4c95-9518-8ac7ca4d3af2.png)
3. The system will save the task and display the details.
4. Now, perform the step (1) for with a different task name. and check the task details. It will retrieve the task details of previously saved task.

## Expected Feature

The system should display the details of current task.

**Comment by TimLethbridge** [comment]
The reproduction steps are unclear. After step 3 you can't do step 2 again since the task name field is not editable. How do you get back to step 2? Please be more precise. I tried 'start over' but the issue did not occur.

**Comment by shoevancar** [comment]
The issue is not re-producible. I have tested it for 20 occurrences in three different browsers and found it working as expected.
I would request to close this ticket.
