### ISSUE TITLE
NullPointerException when a user tries to generate SQL code in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/Umple#1904]
In UmpleOnline, users can create a class diagram and generate its equivalent SQL code. The system returns the "NullPointerException"  when a user tries to generate equivalent code in SQL.

**Steps to produce:**
(1) Select a class diagram such as "2DShapes".
![image](https://user-images.githubusercontent.com/82404135/142798841-4118849f-bfeb-4f6e-93e3-44195699e4fd.png)
(2) Navigate to the "GENERATE" section and select "SQL" from the dropdown. Click on "Generate It".
![image](https://user-images.githubusercontent.com/82404135/142798963-1683a352-0108-4aaa-831d-a0ed5e53652d.png)
(3) The system returns the NullPointerException error and does not return the SQL.
![image](https://user-images.githubusercontent.com/82404135/142799091-e39406fc-d4ce-4415-8fb8-9e3afef09d25.png)

**Expected:**
(1) The system should display an appropriate SQL.

**Similar incidents:**
The same scenarios have been occurring for the following class diagrams.
* Airline
* Banking System A
* Banking System B
* Canal
* Card Games
* Election System
* Elevator System A
* Elevator System B
* Hotel
* Hospital
* Manufacturing Plant Controller
* Political Entities
* Telephone System
* Warehouse System
* University System
* Vending Machine

See PR #1788 which was the most recent work on this issue.

Note: We need to add automated tests that test examples for every generator to avoid regressions. See also #1907 in this regard

**Comment by TimLethbridge** [comment]
#1788 did not solve this issue completely.

**Comment by TimLethbridge** [comment]
A minimal case for the bug seems to be thee classes in an inheritance chain, with an attribute in the top class

```

class A {
  attr;
}

class B { 
 isA A;
}

class C {
 isA B;
}
```
