### ISSUE TITLE
Add ability to fine tune layout of graphviz class diagrams

### ISSUE THREAD

**Issue by TimLethbridge** [umple/Umple#2015]
Graphviz class diagrams are currently set with default node separateion. Sometimes when there are many associations this makes them look messy.

Graphviz has nodesep and ranksep settings that can be applied right after the digraph directive. The default setting is 0.5 but I have experimented, and sometimes being able to increase this to about 3 can be good. 

I suggest a 'suboption' be added to the generator (and related generators) that would inject a nodesep and ranksep value. 

In the UI, these settings could perhaps be adjusted by a separate menu item in Umpleonline (eg. Graphivz widely separated). Or a special command could be applied in the line number field e.g. sep=1.0 or sep=2.0 that would trigger regeneration of relevant diagrams (and persist the value)

**Comment by AxelTWC** [comment]
I explained briefly how this could be implemented and @syedahmed1674 got the solution down.
This issue is currently under developed with @syedahmed1674 PR
PR reference number: #2067
