### ISSUE TITLE
Create equivalent to dev-tools core commands for those developing Umple on windows dev-tools-windows

### ISSUE THREAD

**Issue by TimLethbridge** [umple/Umple#2048]
The dev-tools directory has several useful commands that work on Mac and Linux. It would be very useful if these could be made available for Windows users working on Umple.

Put relevant cmd or bat files in dev-tools-windows ... Windows users could then just put this in their path

qfbumple - quick build without running tests
bumple - full build, running all tests
pumple - do setup for umpleonline

... and any commands these call

**Comment by AxelTWC** [comment]
A PR has been created - Currently only have bumple.bat (The most important command), it will be set as a reference and a backup. I will  keep pushing as much as there can be done. Once finalize , another comment would be added.

**Comment by AxelTWC** [comment]
The Pull Request has now been updated with fresh and new content , please refer to #2061 if needed

# PR: Creation of Developer Tools for future Windows Developers

Umple originally had in built commands for Linux/Mac Users to enhance their development. This PR will create a new branch, a new manual and batch files for specific testing with users who are using Windows for developing Windows. 

The commands being created are included in this following list:
```
- bumple : does a full build of Umple (make sure you have done git pull first)
- fbumple : does a first build of Umple, needed after freshly cloning from git
- qbumple : Does a quick build (compiles .ump source, then generated code, then builds jars)
- qfbumple : Does a quick build (compiles .ump source, then generated code, then builds all other jars other than main umple.jar)
- tumple : Runs a the unit tests only
- pumple : Propagates the umple jars to umpleonline.
- mumple : Rebuilds the user manual from sources in build/reference
- uminify : Minify Umple Scripts
```
