### ISSUE TITLE
Allow multiple files umple in UmpleOnline using tabs.

### ISSUE THREAD

**Issue by Nava2** [umple/umple#225]
Originally reported on Google Code with ID 326

---

Currently UmpleOnline operates on a single model.ump file when it is editing.

This project would do the following:
1. If there are additional .ump files in the directory, it would create tabs in Umple
   Online. Clicking on a tab would load the file into model.ump (for compatibility) and
   display it. Saving model.ump would save the file also to the appropriate named file.
2. There would be the ability to add a tab, and tabs would be renewable, although the
   .ump extension would be automatically part of the name of the underlying file.
3. Code generation would compile the current file, but use clauses would be used to
   enable compiling of all the files. See also issue 325 for the ability to use files
   in standard libraries.
4. It should be possible to export all the ump files by downloading as a zip file,
   as can be done with generated code. Similarly the ability to upload should be possible
   for a set of files.
5. The diagram displayed would always be the one associated with the current file,
   although a mechanism could be incorporated to allow for use of different diagram files
   with the same model file.
6. The entire Umple system compiler should be able to be displayed in this manner in
   UmpleOnline (although don't copy the files).

---

Reported by @umple on 2012-08-16 17:31:21

**Comment by Nava2** [comment]
Reported by @umple on 2012-12-31 18:09:02
- **Status changed**: `Accepted`

**Comment by Nava2** [comment]
Reported by @umple on 2013-07-08 15:13:46
- **Owner removed**

**Comment by Nava2** [comment]
Reported by @umple on 2014-02-13 18:21:36
- **Labels added**: ucosp

**Comment by Nava2** [comment]
Reported by @umple on 2014-02-13 18:22:08
- **Labels added**: Priority-High
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
See also issue 411

---

Reported by @umple on 2014-02-13 18:31:49

**Comment by TimLethbridge** [comment]
This is being worked on in #1402
