### ISSUE TITLE
Enhance the XText integration of Umple

### ISSUE THREAD

**Issue by Nava2** [umple/umple#226]
Originally reported on Google Code with ID 327

---

Currently an XText grammar is maintained that drives display and editing in the XText
Ecliipse plugin. This project would consist of the following:
1. Write a translator that would automatically translate the main Umple grammar into
   XText, so that any changes to the main grammar would be reflected in XText. It may
   be necessary to develop annotations to the main grammar (e.g. specific elements in
   comments) that would allow complete context to be possble in the XText grammar.
2. Thoroughly test and debug the XText Eclipse plugin so it becomes more usable.

---

Reported by @umple on 2012-08-16 17:35:22

**Comment by Nava2** [comment]
Additional XText information
1. Java integration: 
   http://www.eclipse.org/Xtext/documentation.html#jvmtypes
   [www.eclipse.org] 
2. Automated Unit testing: 
   http://www.eclipse.org/Xtext/documentation.html#TutorialUnitTests
   [www.eclipse.org] 
3. Integration with GMF (visual models): 
   http://www.eclipse.org/Xtext/documentation/2.3.0/Documentation.pdf
   [www.eclipse.org]   (Page 196)

---

Reported by @umple on 2012-08-16 17:44:40

**Comment by Nava2** [comment]
issue 219 and  issue 78  and issue 226 are all related

---

Reported by @umple on 2012-09-13 19:38:13

**Comment by Nava2** [comment]
Reported by @umple on 2012-09-27 20:25:55
- **Owner removed**

**Comment by Nava2** [comment]
Reported by @umple on 2012-09-27 20:37:40
- **Labels added**: Priority-High
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Miguel Garzon has volunteered to be a resource person for anyone tacking this issue,
and related XText issues.

---

Reported by @umple on 2012-12-31 17:55:20
- **Labels added**: Ucosp
- **cc added:** +@mgarzon

**Comment by Nava2** [comment]
Reported by @umple on 2012-12-31 17:55:35
- **Status changed**: `Accepted`

**Comment by TimLethbridge** [comment]
We long ago stopped supporting the XText Eclipse plugin. We just use a regular plugin. The problem was that we needed an umple-grammar to xtext-grammar converter, and that was hard. I am closing this issue
