### ISSUE TITLE
Add a standard handler mechanism for non reception errors (an event not handled whle in a state)

### ISSUE THREAD

**Issue by Nava2** [umple/umple#275]
Originally reported on Google Code with ID 376
Owned by `msstraightway`

---

Currently if an event method is called, and the current state cannot respond to it,
the default behaviour is to return false.

However, in some designs we would like to consider this an error, or at least to give
the programmer the opportunity to handle it.

The solution is for the developer to write a method

   Boolean nonReceptionError (sm, state, event, EventArg ...) 

If it exists, this method will be called at the end of every event method. Event methods
will return the result of this.

This applies to basic state machines as well as queued state machines.

The argument types for this method need to be thought about. The first three could
be simply strings, or else could be enumerated values.

See also issue 260

---

Reported by @umple on 2013-02-08 19:53:41

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-12 14:50:25
- **Status changed**: `Accepted`
- **Labels added**: ucosp

**Comment by Nava2** [comment]
Call this method nonSpecifiedReception() instead

---

Reported by @umple on 2013-12-03 20:02:45

**Comment by Nava2** [comment]
Updating issue to make it easier to find non-specified state-machines

---

Reported by @umple on 2014-01-09 16:15:51
- **Owner changed**: `msstraightway`
- **cc removed:** -`msstraightway`

**Comment by Nava2** [comment]
There are two fundamental alternatives:
1. The user just writes an 'unspecifiedreception(String event;=)' method.  
   If this is present, then all the places which do nothing in response to an
   event will call unspecifiedEvent instead.
2. The user want finer control and writes a pseudo-event specification
   called 'unspecified' in any state (that takes a string argument into which
   the event will be placed). She or he could write this in any state, at any
   level of nesting. When encountered in a state, this would match any event 
   not handled. It would have the same semantics as any other event, so could
   have an action, could be a self-transition, transition to some other
   state, or even be guarded.

If the user does both 1 and 2, then the unspecifiedReception() method
from 1 is called before the state-specific unspecified pseudo-event  
actions are called.

---

Reported by @umple on 2014-02-11 17:06:24

**Comment by Nava2** [comment]
A test case:

class X {
  Boolean a;
  sm {
    s1 {
      e1 /{System.out.println("e1");}-> s2;
      unspecified(String event) /{printError(event);}-> error1;
      //ok /{System.out.println("this is error");} -> error1;
    }
    s2 {
      e2 /{System.out.println("e2");}-> s1;
      unspecified(String event) [a] /{printError(event);} -> error2;
      unspecified(String event) [!a] /{printError(event);} -> error1;
      //ok /{System.out.println("Err : this is error");} -> error2;
    }
    error1 {
      -> / {System.out.println("Cont : system is recovered");} s1;
    }

```
error2 {
  -> / {System.out.println("Cont : system is recovered");} s2;
}
```

  }

  boolean unspecifiedReception(String event, String state) {
    System.out.println("Unspecified Reception");
  }

  void printError(String event){
     System.out.println("Entry into error state : "+event+" is detected");
   }

   public static void main(String[] args){
     X x=new X();
     x.e1();
     x.e2();
     x.e2();
     x.e1();
     x.e2();
     x.e1();
     x.e1();
     x.e2();
   }
}

---

Reported by @umple on 2014-02-11 17:18:41

**Comment by TimLethbridge** [comment]
This was done long ago by Aliaa Alghamdi - you can specify unspecified
