### ISSUE TITLE
Improve ability to save and load umple files using DropBox API

### ISSUE THREAD

**Issue by Nava2** [umple/umple#29]
Originally reported on Google Code with ID 85

---

Currently the user can request a bookmarkable URL. Multiple users can collaborate to
change the model, but they have to take turns.

However, improvements include:
- Some form of security to limit who can change the model.
- Ability to delete the model.
- Ability to purge the oldest models that have not been looked at.
- Adding version control so people can revert to earlier versions of their
  model.
- Ability to add a nice name, rather than the generated integer.
- Ability to promote models into a catalog, and/or the official list of
  examples.

---

Reported by @umple on 2011-06-24 14:02:27

**Comment by Nava2** [comment]
Reported by @umple on 2011-06-24 14:05:04
- **Labels added**: loadAndSave, examples

**Comment by Nava2** [comment]
Reported by @umple on 2011-06-24 15:39:48
- **Labels added**: Security

**Comment by Nava2** [comment]
Purging was done by Andrew recently. Examples can now be accessed directly as of svn
670

---

Reported by @umple on 2011-09-02 21:56:18

**Comment by Nava2** [comment]
Suggested directions:
1. Add an ability to 'lock' a model so only people who know a certain ID can change
   it. THere could be a non-modal popup when people attempt to create a bookmark able
   URL that asks optionally for a login ID, model name and secret key.
2. Add an ability to log in using Google or Facebook. If this has been done, then this
   would serve as the loginID above.

---

Reported by @umple on 2012-02-04 13:51:46

**Comment by Nava2** [comment]
Key to this are the
- Ability/requirement to log in before/when requesting a bookmarkable URL
- Ability to delete a model

The others would be relatively easy to do after the above.

---

Reported by @umple on 2012-06-15 15:45:33
- **Labels added**: Type-ProjectUG, Diffic-Med
- **Labels removed**: Type-Enhancement

**Comment by Nava2** [comment]
Reported by @umple on 2013-07-08 15:14:17
- **Owner removed**

**Comment by Nava2** [comment]
Let's do this with the Dropbox API. 
https://www.dropbox.com/developers/core/start/php

In Umpleonline we would add a From Dropbox item to the load menu. Any saving once loaded
would save to the same location -- essentially every write to the model.ump in the
ump folder would also load from Dropbox (although perhaps we can just work with the
entire contents of the ump directory?) Also in the save menu, there would be save to
Dropbox that would set up a new dropbox file or directory.

Among the many advantages of this approach: The user could edit in any local text editor
(by pointing to the relevant dropbox file) and have their models also editable by UmpleOnline

---

Reported by @umple on 2013-07-09 18:27:12
- **Labels added**: Priority-High
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-22 15:04:34
- **Owner changed**: `kkigunda`

**Comment by Nava2** [comment]
I set up a system for receiving authorization for an Apps/UmpleOnline folder in a Dropbox
account and saving a simple test file to that folder, but as
I set things up I realized that there are difficulties with my original approach for
using the core Dropbox API. The full details, which I discussed with Tim, are attached.

At this point I have begun implementing the simple chooser/saver pattern (https://www.dropbox.com/developers/dropins),
and will reconsider the larger problem after this simpler pattern is working. So far
both the Chooser and Saver have been implemented, and the chooser is working well,
but I will have to set up a test production server to test the Saver because Dropbox
does not allow files to be uploaded directly. Instead, we must provide a link to the
file that Dropbox will download, and so the files must be hosted live online.

---

Reported by `kkigunda` on 2013-11-18 04:25:11
- **Status changed**: `Ongoing`
  - _Attachment: [Discussion - Dropbox Integration Plan.html](https://storage.googleapis.com/google-code-attachments/umple/issue-85/comment-9/Discussion - Dropbox Integration Plan.html)_

**Comment by Nava2** [comment]
This has been done to a certain level, however it has rough edges. For example, if you
try to save, there is no way to specify the filename. Each time you save it creates
a new file called model(n).ump, where n is incremented. However, a more sophisticated
extension of this capability seems as though it would require server https support,
which we might not do for now

---

Reported by @umple on 2013-12-13 16:01:17
- **Labels added**: Priority-Low
- **Labels removed**: Priority-High

**Comment by Nava2** [comment]
Reported by @umple on 2014-02-13 18:19:02
- **Owner removed**

**Comment by TimLethbridge** [comment]
The Cruise server does support https now, so we could improve Dropbox support if we want.

**Comment by TimLethbridge** [comment]
The Dropbox API has changed so this seems broken. Raising priority

**Comment by TimLethbridge** [comment]
We won't use Dropbox any more. We have plenty of other saving and loading mechanisms, and people can set up their own directories for saving and loading
