### ISSUE TITLE
Multiple Code injections for the same method lead to incorrect line numbers

### ISSUE THREAD

**Issue by Nava2** [umple/umple#292]
Originally reported on Google Code with ID 393
Owned by `redeyedmars`

---

**What steps will reproduce the problem?**
class A
{
  x;
  after getX { "first".toString(); }
  before getX { "second".toString(); }
  after getX { "last".toString(); }
}

produces:
public String getX()
{
  // line 4 m.ump
  "second".toString();
  //get method
  // line 3 m.ump
  "first".toString();
  "last".toString();
}

as you can see, "last".toString() does not come from line 3 of the umple file, indeed,
there is another code injection at line 4. This causes an irreconcilable bug when trying
to catch errors produced by the injected lines because "last".toString() is associated
to the position of "first".toString(). This is issue would most likely be fixed by
keeping each code injection separate, but some changes to the way they are applied
is needed.

---

Reported by `redeyedmars` on 2013-05-31 14:44:54

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-12 14:39:35
- **Labels added**: Diffic-Hard

**Comment by Nava2** [comment]
Reported by @umple on 2014-02-11 16:46:37
- **Labels added**: aspectOriented

**Comment by Nava2** [comment]
Not clear, Geoffrey, if you are solving this, but I am assigning it to you as you are
working on this part of the code.

---

Reported by @umple on 2014-05-01 14:16:55
- **Owner changed**: `redeyedmars`

**Comment by TimLethbridge** [comment]
This is fixed already, so closing
