### ISSUE TITLE
Class with attribute name that is the same as an attribute it inherits from a superclass generates code instead of throwing error

### ISSUE THREAD

**Issue by Nava2** [umple/umple#328]
Originally reported on Google Code with ID 429

---

**What steps will reproduce the problem?**
class C
{ cAttr; }

class E { 
  isA C; 
  cAttr;
}

**What is the expected output? What do you see instead?**

expected: "ERROR"

actual: generates code which has ambiguities, like the constructor

public E(String aCAttr, String aCAttr) {
 super(aCAttr);
 cAttr = aCAttr;
}

**Please use labels and text to provide additional information.**

---

Reported by `fkazhamiaka` on 2013-09-21 16:15:06

**Comment by Nava2** [comment]
This is a special case of what might be a more general case: What happens when you have
duplicates in subclasses of associations (perhaps 'refining' of multiplicity should
be allowed). What happens if you have duplicate state machines (merging of the state
machines should occur).

Make sure this works in interfaces (constants declared there might have the same name
as an attribute).

Create a new error message; don't reuse message 22.

---

Reported by @umple on 2013-09-21 16:38:10
- **Owner changed**: `fkazhamiaka`
- **Labels added**: Priority-High, ucosp, Component-SemanticsAndGen, Diffic-Easy, attributes
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Needs converting into an error message once some examples of this in the Umple compiler
are cleaned out

---

Reported by @umple on 2013-12-09 14:09:28
- **Status changed**: `MostlyDone`

**Comment by Nava2** [comment]
There is interaction between this issue and issue 316 -- the idea of specializing or
restricting of attributes.

---

Reported by @umple on 2013-12-22 15:44:36

**Comment by Nava2** [comment]
Opening for another student since it needs finishing

---

Reported by @umple on 2014-05-12 17:33:29
- **Owner removed**
- **cc added:** +`fkazhamiaka`

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-30 12:59:54
- **Owner changed**: `ac.ringeri`

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-30 13:02:05
- **Owner changed**: `alexwithaneye`

**Comment by Nava2** [comment]
Reported by @umple on 2015-02-06 16:17:04
- **Owner removed**

**Comment by TimLethbridge** [comment]
This is issue seems to have been dealt with. The example given no longer generates bad code. The repeated definition of an attribute in a subclass is ignored (if identical) which actually could be useful. If the the repeated definition has a different type it raises an error.
