### ISSUE TITLE
Add Warning if Abstract Method Not in Abstract Class

### ISSUE THREAD

**Issue by Nava2** [umple/umple#332]
Originally reported on Google Code with ID 433
Owned by `greg.hysen`

---

It should raise a warning because in most languages an abstract class is required for
there to be abstract methods. However, in c++ only the presence of a pure virtual method
is needed. 

---

Reported by `greg.hysen` on 2013-09-22 14:53:10

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-22 23:46:25
- **Status changed**: `Accepted`
- **Labels added**: Priority-Medium, Component-SemanticsAndGen, Diffic-Easy
- **Labels removed**: Code-Generation

**Comment by vahdat-ab** [comment]
currently, this is no issue for this in Java. Umple automatically detects this and consider the class as an abstract class. However, it's not generated for PHP. Other languages must be checked as well and there  should be proper test cases for all languages.

**Comment by vahdat-ab** [comment]
I think the approach used for Java is that best one. Instead of showing warning, we can cover it at the code generation level.
