### ISSUE TITLE
Write an Umple Journal Paper based on Chapters 4 and 5 of Andrews thesis and a summary of Umple

### ISSUE THREAD

**Issue by Nava2** [umple/umple#36]
Originally reported on Google Code with ID 99
Owned by @umple

---

Write an Umple Journal Paper based on Chapters 4 and 5 of Andrews thesis and a summary
of Umple

---

Reported by @umple on 2011-06-24 14:49:52

**Comment by TimLethbridge** [comment]
Not really relevant as an issue
