### ISSUE TITLE
Add images to Umple's xtext outline view

### ISSUE THREAD

**Issue by Nava2** [umple/umple#37]
Originally reported on Google Code with ID 100
Owned by @obahy

---

The xtext plugin is using the default images in the outline view. This should be enhanced
with more appropriate images, perhaps adopting the same images as available in other
open source UML tools.

---

Reported by @umple on 2011-06-24 14:52:18
- _Attachment: xtext_screenshot.png<br>![xtext_screenshot.png](https://storage.googleapis.com/google-code-attachments/umple/issue-100/comment-0/xtext_screenshot.png)_

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-17 13:32:44
- **Status changed**: `Accepted`
- **Labels added**: Diffic-Easy

**Comment by TimLethbridge** [comment]
The XText plugin has not been maintained for several years. If this issue is to be done, the entire plugin needs to be revisited.
