### ISSUE TITLE
Allow some form of specification of requirements in Umple including use cases and perhaps GRL

### ISSUE THREAD

**Issue by Nava2** [umple/umple#379]
Originally reported on Google Code with ID 481

---

It would be nice to support syntax like syntax like the following to allow incorporation
of features like use case diagrams and GRL into Umple.

Part of the syntax might be

actor regularUser;

usecase idnumber {
  isA generalUseCase; 
  doneBy regularUser;
  whatever
}

class X {
  implements idnumber;
}

Part of this issue is actually generating diagrams; part of it is validating the relationships

This would make Umple support more of UML, and would meld well with analysis phases.
Having requirements and code managed together would be helpful in many contexts.

---

Reported by @umple on 2014-01-10 14:43:15

**Comment by Nava2** [comment]
Reported by @umple on 2014-01-10 14:43:32
- **Owner removed**
- **Status changed**: `Accepted`

**Comment by Nava2** [comment]
Consider ReqIF in Umple http://www.omg.org/spec/ReqIF/

---

Reported by @umple on 2015-03-09 23:19:35

**Comment by vahdat-ab** [comment]
you might want to have a look at TGRL (https://github.com/vahdat-ab/TGRL). It offers a good syntax for textual representation of GRL.

A paper on this is here: https://www.researchgate.net/publication/292409207_Adding_a_Textual_Syntax_to_an_Existing_Graphical_Modeling_Language_Experience_Report_with_GRL  
And:  https://link.springer.com/chapter/10.1007%2F978-3-319-24912-4_12

We are, however, not going to directly do this, as we want to generically allow multiple languages.

**Comment by TimLethbridge** [comment]
The rough appearance in Umple of new constructs for the first agile iteration of this would be:

```
req IDENTIFIER LANGUAGE {
  // arbitrary text in the language
}

implements REQIDENTIFIER, REQIDENTIFIER ;
```
The LANGUAGE would be optional, just as it is in code.

The identifier could be anything other than spaces, but if there are dots, they can be used to help organize sub requirements.

The implements clauses could appear anywhere an inline comment can, so in fact they could be implemented in the comment clause in the grammar. Ideally the code that currently puts comments into generated code (class comment, method comment, etc.) would put A reference to the requirement there too.

We will take this feature much further later, but the above would be a start.

**Comment by TimLethbridge** [comment]
Suggested First sprint:

Enable grammar so anywhere 
 - at the top level
 - or inside a mixset
A requirement block can be specified

```
req IDENTIFIER LANGUAGE {
  ... anything ...
}
```

LANGUAGE would be optional. If not specified then the contents would be considered plain text. We could add md for markdown as an easy next step.

Example

```
req R01 {
  This is a test requirement
}
```

```
req R01 md {
  # This is a header
  This is lower level text
}
```

Later on we might implement use cases as per the first part of the issue text.


Enable wherever a comment can be specified whereever a comment can be

```
implements  R01;
```

This would have the result of enabling output of formatted text into classes, attributes. But would also later on allow us to generate various diagrams.

Suggested second sprint: Processing the textual requirements and storing them in a similar way to comments.

Suggested third sprint: Outputting requirements in the same places that comments (for classes, attributes, etc.) are currently output: I.e. in Javadoc, and as tooltips in Gv diagrams.
