### ISSUE TITLE
State machine repeated definition doesn't work

### ISSUE THREAD

**Issue by Nava2** [umple/umple#389]
Originally reported on Google Code with ID 491

---

Load the code below. There are a number of oddities that need resolving.

The second and subsequent occurrences of declaration of sm should be just aded together.
Currently they are ignored whether in the same class definition, or a mixing class
definition

class X {
  sm {
    s1 {
      e->s2;
      e4 -> s4;
    }
    s1 {
      e1 -> s2;
    }
    s2 {
      s3 {e6 -> s1;}
      s3 {}
      s1 {e7 -> s2;}
    }
  }
  sm {
    s8 {
       e9 -> s9;
    }
    s9 {}
  }
}

class X {
  a;
  sm {
    s4 {}
    s5 {}
  }
}

---

Reported by @umple on 2014-01-24 22:11:23

**Comment by Nava2** [comment]
Reported by @umple on 2014-01-24 22:12:53
- **Labels added**: ucosp, Component-SemanticsAndGen, Diffic-Easy, stateMachines

**Comment by Nava2** [comment]
Probably this issue was solved with the patches that solved issues 200/199 and 580.

---

Reported by `pedroaugusto3000` on 2014-06-04 15:19:34

**Comment by Nava2** [comment]
This example code doesn't generate a diagram

---

Reported by @umple on 2014-06-27 18:30:42
- **Owner removed**

**Comment by TimLethbridge** [comment]
Seems to be fixed
