### ISSUE TITLE
Allow developers to replace generated code - aspect-oriented around syntax

### ISSUE THREAD

**Issue by Nava2** [umple/umple#39]
Originally reported on Google Code with ID 102
Owned by @aforward

---

Draw upon more aspect-oriented approaches and introduce the around keyword. We need
to discuss the semantics of around which replaces the current implementation, and in
particular how around deals with other advice such as before and after, as well as
multiple arounds.

---

Reported by @umple on 2011-06-24 14:57:11

**Comment by Nava2** [comment]
Reported by @umple on 2011-06-24 15:46:38
- **Owner changed**: @aforward

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-17 13:37:47
- **Labels added**: Diffic-Hard
- **cc added:** +@vahdat-ab

**Comment by TimLethbridge** [comment]
Use cases for this are questionable. We haven't done it in many years so there appears to be little demand. Somebody who replaces the code might has well just use an attribute and code their own association logic.
