### ISSUE TITLE
Code generator for Alloy

### ISSUE THREAD

**Issue by Nava2** [umple/umple#396]
Originally reported on Google Code with ID 498
Owned by @ope

---

We need a code generator for Alloy.  http://alloy.mit.edu/alloy/

Opeyemi Adesina will be resting test cases. We will need to walk the metamodel and
generate the code. This should be done in an agile manner, just one or a few test cases
at a time.

The eventual idea is to be able, as part of Opeyemi's PhD work to be able to pass off
a model to Alloy for deeper analysis to find faults, prove various things. etc.

---

Reported by @umple on 2014-02-04 20:49:16

**Comment by Nava2** [comment]
Reported by @umple on 2014-02-21 02:56:37
- **Owner changed**: @ope
- **Status changed**: `Accepted`
- **cc removed:** -@ope

**Comment by Nava2** [comment]
The initial Alloy representation is now in place. 

---

Reported by @ope on 2014-02-21 03:26:21

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-05 15:13:15
- **Labels removed**: ucosp

**Comment by TimLethbridge** [comment]
I am closing this issue. new issues against the Alloy generator may be raised as separate issues.
