### ISSUE TITLE
Generate warning when a before or after statement doesn't match any methods

### ISSUE THREAD

**Issue by Nava2** [umple/umple#410]
Originally reported on Google Code with ID 512
Owned by `tylerjdmcconnell`

---

if I say 

after junk {destuff();}

This is silently ignored. Junk could be mis-spelled and the user would never know.

There should be a warning.

---

Reported by @umple on 2014-02-11 16:48:59

**Comment by Nava2** [comment]
Reported by `tylerjdmcconnell` on 2014-03-21 14:24:19
- **Owner changed**: `tylerjdmcconnell`

**Comment by Nava2** [comment]
The fix for this bug will exist in the code where the metamodel is fully populated.
Issue 403 is similar to this issue and the fix for it should give good guidance on
what to do for this issue.

---

Reported by `tylerjdmcconnell` on 2014-04-24 15:36:09

**Comment by TimLethbridge** [comment]
Hint: Messages are listed in en.error. You would need to add a new one in a logical place in numeric sequence (close to other messages related to methods or before/after).

Try looking in UmpleInternalParser_CodeClass.ump There are lots of places where the warning-message method is called -- such as setFailedPosition(...)

**Comment by mkmicik** [comment]
I can take this one. 

Mike

**Comment by vahdat-ab** [comment]
Mike, Shikib has already started to work on this. 
check ucosp.umple.org to see which issues have not been assigned.

**Comment by mkmicik** [comment]
Whoops didn't notice that was a reply sorry.

**Comment by TimLethbridge** [comment]
See issue #686 This issue wasn't correctly fixed
