### ISSUE TITLE
Allow as an option the display of generated code in UmpleOnline in a series of tabs

### ISSUE THREAD

**Issue by Nava2** [umple/umple#411]
Originally reported on Google Code with ID 513

---

Currently, all the generated files are joined together in the output. And you can't
even see the file names.

It would be better to allow, as an option, the ability to see the generated files in
separate tabs.

This should be optional because sometimes it is highly advantageous to be able to search
through all generated output looking for certain strings.

One way to achieve this would be to have the code that generates the single glommed
together file to insert a special line before each file containing the file name, for
example
//%% abcd.java

Then the option to display tabs could simply parse this and split it. Note that when
files are in subdirectories caused by namespace directives, this would have to be accounted
for.

An alternative would be just to look for all the generated files. The problem is that
currently generated files may be left lying around in certain cases from a previous
generate

---

Reported by @umple on 2014-02-13 18:27:40

**Comment by Nava2** [comment]
See also issue 225

---

Reported by @umple on 2014-02-13 18:32:00

**Comment by Nava2** [comment]
See also issue 225

---

Reported by @umple on 2014-09-05 15:06:33
- **Status changed**: `Accepted`

**Comment by TimLethbridge** [comment]
This was fixed long ago
