### ISSUE TITLE
Umple Online UI: In the options bar, the alignments of radio buttons are not consistent.  

### ISSUE THREAD

**Issue by Nava2** [umple/umple#420]
Originally reported on Google Code with ID 522
Owned by @howzlife

---
1. Text like "Show View" should be centered.
2. Icons and buttons should be left aligned.
3. "Text Editor <-", the < - is confusing. It can be improved by using a image. 

---

Reported by @chrissie926 on 2014-02-28 06:08:31
- _Attachment: Screen Shot 2014-02-28 at 1.05.10 AM.png<br>![Screen Shot 2014-02-28 at 1.05.10 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-522/comment-0/Screen Shot 2014-02-28 at 1.05.10 AM.png)_

**Comment by Nava2** [comment]
Reported by @umple on 2014-03-21 18:20:46
- **Owner removed**
- **Status changed**: `Accepted`
- **Labels added**: Priority-Low, Component-UmpleOnline, Diffic-VEasy, Usability

**Comment by Nava2** [comment]
Reported by @mgarzon on 2014-05-12 17:31:50
- **Owner changed**: @howzlife

**Comment by Nava2** [comment]
The alignment was fixed a while ago, but it'd be nice if any menu items that wrapped
would not wrap under the radio button, like in the screenshot above (the class diagram
and state diagram labels). 

---

Reported by @CraigBryan on 2014-11-05 21:36:40

**Comment by TimLethbridge** [comment]
This has been resolved in the past, so closing.
