### ISSUE TITLE
Creating set, get and all other API methods created in UmpleModel before code generation

### ISSUE THREAD

**Issue by Nava2** [umple/umple#462]
Originally reported on Google Code with ID 564

---

As we know, we generate get and set methods for attributes. We do this through code
generation mechanisms. However, these methods must be part of Umple model in order
to have control on them (e.g. detect users' methods  with the same name and so on).
we can add our manual codes easily and even modify them in the level of modelling.
Having them in the level of code generation is not suitable mechanism because we lose
our controls.
We need these methods for automatic test case generation, formal modelling, traits,
and aspect orientation.In fact, having them in model level provides consistency for
all of the mentioned cases.

---

Reported by @vahdat-ab on 2014-05-15 21:52:39

**Comment by Nava2** [comment]
The idea here is that you would parse the model, and then in the internal representation
of that model you would add the necessary methods that would be generated (instead
of relying on the code generators to do this). This would have to be multi-lingual
(Java, C++, php etc.).

Advantages: Would simplify creation of new generators. Would allow much better analysis
and conflict detection.

Would require a lot of very careful work to implement.

---

Reported by @umple on 2014-05-20 20:12:14
- **Labels added**: Type-Reengineering, Component-SemanticsAndGen, Diffic-VHard, Maintainability
- **Labels removed**: Type-Other

**Comment by katcavers** [comment]
@vahdat-ab Hey Vahdat! For constructors, do we want to return the autogenerated constructor in a call to UmpleClass.getMethods? I want to double check before I change some tests. Thanks!

**Comment by vahdat-ab** [comment]
Yes, it should be.

**Comment by TimLethbridge** [comment]
This is a duplicate of #962, which is being worked on steadily
