### ISSUE TITLE
Having execution time for compile and code generation in UmpleOnline

### ISSUE THREAD

**Issue by Nava2** [umple/umple#483]
Originally reported on Google Code with ID 585
Owned by @mgarzon

---

It would be good to see execution time related to code generation and compile time on
UmpleOnline. It will shows real-compile time without dependency to internet speed (which
some time users think that umple works slow while it's because of their machine). 
The following items, for example, can be shown in UmpleOnline:
1) Parsing time,
2) Analysis time, 
3) Code generation, and
4) total time.
We also need to show config of our server in order to have valid interpretation for
the times.

---

Reported by @vahdat-ab on 2014-06-06 15:43:14

**Comment by Nava2** [comment]
This feature may be considered as a keyword in command-line. 

---

Reported by @vahdat-ab on 2014-06-06 16:32:41
- **Owner changed**: @mgarzon
- **Status changed**: `Accepted`

**Comment by Nava2** [comment]
Reported by @vahdat-ab on 2014-06-06 16:33:26
- **Labels added**: Priority-Medium

**Comment by Nava2** [comment]
This needs to appear only as an option, and when it does appear it should appear either
in the message area above or below.

---

Reported by @umple on 2014-06-09 13:58:06

**Comment by Nava2** [comment]
For the fixml case, I implemented a Class Timer, with start, stop and total times. (See
image attached).

This will be an option in the command line.

---

Reported by @mgarzon on 2014-06-09 14:34:34
- _Attachment: elapsedTime.png<br>![elapsedTime.png](https://storage.googleapis.com/google-code-attachments/umple/issue-585/comment-4/elapsedTime.png)_

**Comment by vahdat-ab** [comment]
We should first do this through command line and when it's completed, we can easily have it in UmpleOnline or any other tools that want to use Umple.

**Comment by Jaorji** [comment]
This is the result doing it on the command line.

![image](https://cloud.githubusercontent.com/assets/22030859/22766150/db022558-ee41-11e6-849a-a81a95a9696d.png)

**Comment by Nava2** [comment]
https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html

Java's time library is probably useful here, nanoseconds are hard to read. 😄

**Comment by vahdat-ab** [comment]
@TimLethbridge do you think these are enough for the performance evaluation?

**Comment by TimLethbridge** [comment]
Change the units to seconds.

Don't use so many significant figures. To determine how many significant figures to use, run the query 20 times and strip off the sig figs that consistently vary (plus 1, rounded). For example it might be that parsing is 4.54713282 one time and 4.5467465 and 4.5471975 etc. That suggests to me that it is totally irrelevant to report anything other than 4.5471  4.5467 and 4.5472 for these. Anything else is just noise.

**Comment by Jaorji** [comment]
-I changed the units to seconds.

- Analysed scenario on performance execution tests:

1. System execution time and parsing time. Execute performance test for one-time and get the time result:
![qq 20170208205854](https://cloud.githubusercontent.com/assets/22030859/22804285/60bad95c-eee6-11e6-920f-7c6352f85160.png)

**Comment by vahdat-ab** [comment]
I think there are two cases that needs to be discussed.

1. We just want to know how much it takes to parse and generate the code. It is for our own info (not for a formal evaluation). For example, we want to show it to users on the Umpleonline. In my opinion it must be run once. Otherwise, users need to wait a lot to get their responses. They might not be interested to see the performance of Umple.

2. We want to actually do a full evaluation on different phases. In that case, we need to run several times (as Tim said) each phase and then make an avregare.

@TimLethbridge I think this issue is about the case `1` and case `2` can be explored later in anothe issue, if it is needed. What do you think?

@Jaorji  Please also show the system info at the end of the result. For example, CPU, RAM, JVM memory, OS, and others that might be helpful

**Comment by TimLethbridge** [comment]
My suggestion of 20 times was merely to find the right number of significant figures or decimals. We have that right now I think.

**Comment by Jaorji** [comment]
- I print some of System Information below:
![qq 20170210160406](https://cloud.githubusercontent.com/assets/22030859/22844139/b004574e-efaa-11e6-8cb2-e6c5992e84d1.png)

- When I want to print CPU  &RAM information, I need add **Sigar.jar**. The way I added it to the library is: Build Path-> Add Libraries->Add External JARs.However, it didn't succeed when I build umple.

- So if anyone knows other APIs I can use or the way to add .jar correctly? Must I add System Information here?

**Comment by Nava2** [comment]
Check the license of The library, and then add it to the ivy file if the license is safe. Putting it in the ivy build means it'll be downloaded when building Umple.

**Comment by vahdat-ab** [comment]
I would suggest using this [library ](https://github.com/oshi/oshi). The justification about why we should use it can be found in the link.
The license is Eclipse Public License 1.0.
@TimLethbridge I wonder if it's worth to have a package dependency to get the hardware info in the Umple? I suggested to have it, but I think everybody can get that info easily through command lines in their systems.

**Comment by TimLethbridge** [comment]
I think the extra complexity of getting the hardware data is not worth the cost at the current time.

**Comment by vahdat-ab** [comment]
@Jaorji 
I think now you can go head, and do your pull request. Please also remove the output related to "Current system information". As Tim said, we don't need in this phase of work. 
Good job :-)
