### ISSUE TITLE
Allow generation of state tables and sample runs

### ISSUE THREAD

**Issue by Nava2** [umple/umple#509]
Originally reported on Google Code with ID 611
Owned by @CraigBryan

---

Add a generator generate state-state and state-event tables. See the attached file for
examples and semantics.

Also add a generator to generate a random sequence of events (selected from the possible
events in the model) and a table showing what state the system would be in after every
transition. Each run of the generator would give a different result. It could be biased
to 'normally' choose events that are in fact expected, but not always. This would be
very good pedagogically.
**Please use tags such as 'stateMachines', 'Tracing', etc. to help us**
**categorize this request.**

---

Reported by @umple on 2014-07-24 14:16:57
- _Attachment: [StateTableForUmpleIssue.xlsx](https://storage.googleapis.com/google-code-attachments/umple/issue-611/comment-0/StateTableForUmpleIssue.xlsx)_

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-05 15:08:11
- **Labels added**: Priority-High, ucosp
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-05 15:11:14
- **Labels added**: Type-ProjectUG
- **Labels removed**: Type-Enhancement

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2015-02-09 01:19:01
- **Owner changed**: @CraigBryan

**Comment by Nava2** [comment]
Here's a draft of the colouring of sub-states and sub-sub-states (see the tabs at the
bottom left of the page to switch between examples):

https://docs.google.com/spreadsheets/d/1aL_elQ95AO0ehovMzsg6Auo3VK2ec6e4l74j1UNWcFE/edit?usp=sharing

---

Reported by @CraigBryan on 2015-02-09 02:10:09
- **Status changed**: `Ongoing`

**Comment by Nava2** [comment]
The state tables are implemented now, and I'm turning my focus to the generation of
sequences of events. I have a few questions to help me get started: 

How do you envision the layout of a table showing the resulting state after each transition?
States as rows and the series of transitions as the columns? Then the cell at (current
state, last transition) would contain a marker or be highlighted in some way? This
would allow for concurrency, but may result in very large tables.

How many transitions should be generated? Should we generate a random walk until all
states are visited? Until all transitions are taken?

How should guards be dealt with to ensure visiting all states/ doing all transitions?

---

Reported by @CraigBryan on 2015-03-03 13:44:03

**Comment by Nava2** [comment]
The sample run generator is implemented as of r5282.

---

Reported by @CraigBryan on 2015-04-02 13:15:52

**Comment by TimLethbridge** [comment]
Seems to be done as of summer 2015. Any bugs would be reported as new issues.
