### ISSUE TITLE
Not telling developers about having extra code

### ISSUE THREAD

**Issue by Nava2** [umple/umple#516]
Originally reported on Google Code with ID 618

---

When there is an extra code in the final generated code, Umple compiler should let developers
know about it through the proper warnings. This is critical because sometimes developers
forget to put a semicolon at the end of their codes and Umple compiler doesn't detect
them and consider them as extra codes while developers expect the suitable results
from their codes. This is completely confusing and have a direct association with the
fault tolerance criterion.
For example, consider the following example. Inside of class "X" there is a valid command
but without a semicolon. Umple put it as extra code and doesn't let the developer know
about it. There is two options. The First one is Umple compiler detects it and let
the developers know about it (I mean missing a semicolon). The second one is compiler
just arises an warning about having extra codes in the final generated code.

class X{
    isA T <X=B>
}

trait T<X>{
  X name;
}

---

Reported by @vahdat-ab on 2014-08-12 05:30:43

**Comment by Nava2** [comment]
Reported by @vahdat-ab on 2014-08-12 05:32:15
- **Labels added**: Component-SemanticsAndGen

**Comment by Nava2** [comment]
Reported by @vahdat-ab on 2014-08-12 05:32:55
- **Labels added**: Diffic-Med

**Comment by Nava2** [comment]
Reported by @umple on 2014-09-05 14:34:22
- **Labels added**: Priority-High
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2015-02-09 02:25:25
- **Status changed**: `Accepted`

**Comment by TimLethbridge** [comment]
This is an OK issue, but lots and lots of cases of extra code will appear, so we absolutely mustn't spit out a warning in every single case. Just one warning at the end if there was any 'Developer Code' would be acceptable. This should not include the bodies of methods, guards etc.
