### ISSUE TITLE
Code Injection for not Generated API methods doesn't work.

### ISSUE THREAD

**Issue by Nava2** [umple/umple#517]
Originally reported on Google Code with ID 619
Owned by @vahdat-ab

---

**What steps will reproduce the problem?**
1. Add a code injection to a method (not generated method) like in the following example:

class Test {

  before methodNotInApi {
    if (aName != null && aName.length() > 20) { return false; }
  }

  methodNotInApi(){
     return null;
  }
}

**What is the expected output? What do you see instead?**

In java, this should be the output:
public  methodNotInApi(){
   if (aName != null && aName.length() > 20) { return false; }
  return null;
}

The code injection, however, works if you put the star after the method name:

 before methodNotInApi\* {
    if (aName != null && aName.length() > 20) { return false; }
  }

---

Reported by @mgarzon on 2014-08-19 17:35:51

**Comment by Nava2** [comment]
In addition, after code injection doesn't work in mentioned above case:

after methodNotInApi\* {
    if (aName != null && aName.length() > 20) { return false; }
  }

---

Reported by @hjamaan on 2014-08-19 22:19:55

**Comment by Nava2** [comment]
It works fine if you say before methodNotInApi()

with the parentheses. Not sure if there are any side-effects of removing the requirement
for parentheses here but seems reasonable and a very quick fix.

---

Reported by @umple on 2014-09-21 14:01:00
- **Labels added**: Component-Metamodel, Diffic-VEasy

**Comment by TimLethbridge** [comment]
This has been fixed when fixing another issue
