### ISSUE TITLE
Syntax for ports results in silence

### ISSUE THREAD

**Issue by Nava2** [umple/umple#518]
Originally reported on Google Code with ID 620
Owned by @ahmedvc

---

**What steps will reproduce the problem?**
1. Umple command line compiler was not reported the error when I'm was made a mistake
and forgot to write multiplicity on directed association in model.ump file. 
"Similar" problem is evident on Umple web generator (in UML model - on the right side
of application, association was deleted and if one pay attention loosing association
was a good sign, but on the model.ump file on the application left side, line of code
become useless but compiler unfortunately, does not signalized the error and generated
the Java code).

NOTE: I'm was really excited when I was reveal and realized usefulness of yours project.
Thank you so much for your effort, for your idea and because you share Umple with community.
Best regards Zoran Savić from Belgrade, Serbia.

**What is the expected output? What do you see instead?**
As one expected, in that circumstances Java code generated without directed association.

**What is the expected output? What do you see instead?**
As one expected in that circumstances, Java code generated without directed association.

**What version of the product are you using? On what operating system?**
Umple release 1.20.2.4305
OS: Ubuntu 14.01 LTS (64-byte); Processor type is AMD; Browser type is Firefox..
Use: Live Examples From Umple Online -> Example was: Accidents

**Please provide any additional information below.**

file//: model.ump
class Nesreca { //class Accident. Class name was changed to Serbian language 
    id;
    Date datum;
    Time vreme;

```
* -> 1 TezinaPovrede; // class SeriousnessLevel
* ->  VrstaNesrece; // This line was not noticed as a error by Umple compiler! class
```

AccidentType
    \* -- 1 Zaposleni; // class Employee

```
key {id}
```

}

---

Reported by `zoranssavic` on 2014-08-21 20:38:23
- _Attachment: [model.ump](https://storage.googleapis.com/google-code-attachments/umple/issue-620/comment-0/model.ump)_
- _Attachment: [Nesreca.java](https://storage.googleapis.com/google-code-attachments/umple/issue-620/comment-0/Nesreca.java)_

**Comment by Nava2** [comment]
This is a clear problem that is easily reproducible. In the following simplified example,
the bad line is ignored.

class Nesreca {

```
* ->  VrstaNesrece; // This line was not noticed as a error by Umple compiler! 
```

}

---

Reported by @umple on 2014-08-21 22:58:32
- **Status changed**: `Accepted`
- **Labels added**: Priority-VHigh, Diffic-Easy, Component-Syntax, Usability, associations
- **Labels removed**: Priority-Medium, Diffic-Med

**Comment by Nava2** [comment]
I will fix this.
Right now, it is parsed as follows:

[classDefinition][name:Nesreca][portBindingDefinition][fromPort:*][toPort:VrstaNesrece][bindinHandler][inlineComment:This
line was not noticed as a error by Umple compiler!]

---

Reported by @mgarzon on 2014-08-25 13:03:15
- **Owner changed**: @mgarzon

**Comment by Nava2** [comment]
Solution requires modification of the grammar for the portBindingDefinition (in umple_structure
grammar).
We need to restrict what is considered a 'fromPort' and/or 'toPort'.

---

Reported by @mgarzon on 2014-08-25 13:35:34

**Comment by Nava2** [comment]
It turns out that this is valid syntax for ports. But ports can only be generated in
C++. 

We therefore need to generate a series of warnings when a generate target is Java and
certain syntax will be ignored in that language.

---

Reported by @umple on 2014-08-25 16:09:08

**Comment by Nava2** [comment]
Reported by @ahmedvc on 2014-08-25 16:41:38
- **Owner changed**: @ahmedvc

**Comment by TimLethbridge** [comment]
I think this has been resolved. The error message is

``
Error on line 2 : Port name '1' from class '' can not be resolved.. More information (3607)
```
