### ISSUE TITLE
Abstract methods should be rendered in italics in a class diagram

### ISSUE THREAD

**Issue by Nava2** [umple/umple#529]
Originally reported on Google Code with ID 631

---

In the following I would like to see m appear in italics or have the abstract stereotype

class X {
  abstract;
  abstract void m();
}

class Passenger {
  name;
}

class Flight {
  number;
}

class Booking {
  seatNumber;
- -- 1 Passenger;
- -- 1 Flight;
  }

---

Reported by @umple on 2014-09-19 16:38:40

**Comment by Nava2** [comment]
Should apply to graphviz as well as editable class diagrams. Probaby better to use italics,
although «abstract» might be clearer but more messy. Experiment with both.

---

Reported by @umple on 2014-09-21 13:54:43
- **Owner removed**
- **Labels added**: Priority-Low, Component-UmpleOnline, Diffic-Easy, ucosp
- **Labels removed**: Priority-Medium

**Comment by TimLethbridge** [comment]
Completed by M. Fritze
