### ISSUE TITLE
Assert testing not checking for empty arrays/null ArrayLists

### ISSUE THREAD

**Issue by Nava2** [umple/umple#532]
Originally reported on Google Code with ID 634
Owned by `alexwithaneye`

---

Currently, many of the test methods (AssertFailedParse and AssertHasWarningsParse namely)
are checking for errors in the ParseResults before checking if there are even any errors
to analyse. 

To reproduce the issue, in UmpleParserTest, you can do something like

{{{
@Test
public void testAFile()
{
  assertHasWarningsParse("###_SomeFileThatDoesNotProduceWarnings.ump");
}
}}}

---

Reported by `alexwithaneye` on 2014-09-20 20:39:59

**Comment by Nava2** [comment]
See also issue 534

---

Reported by @umple on 2014-09-21 13:51:58
- **Owner changed**: `alexwithaneye`
- **Labels added**: Priority-Low, Component-Builder, Diffic-VEasy, ucosp
- **Labels removed**: Priority-Medium

**Comment by TimLethbridge** [comment]
The code for assertHasWarningsParse is in line 2652 of UmpleParserTest.java

It does look as though this has been entirely fixed
