### ISSUE TITLE
Italicize abstract classes and methods in class diagrams.

### ISSUE THREAD

**Issue by Nava2** [umple/umple#539]
Originally reported on Google Code with ID 641

---

It would improve usability if abstract classes and methods were shown in italics in
all views.

---

Reported by @umple on 2014-10-04 20:40:45

**Comment by Nava2** [comment]
Also possible look at supporting «abstract» stereotype on the class

---

Reported by @aforward on 2015-01-16 15:09:51

**Comment by TimLethbridge** [comment]
This has been done for methods. See 
class Test {
  abstract void m();
}
