### ISSUE TITLE
An int attribute starting with the name 'port' cannot be created

### ISSUE THREAD

**Issue by Nava2** [umple/umple#546]
Originally reported on Google Code with ID 648

---

**What steps will reproduce the problem?**
1. declare an int with the name "portNumber" -->  "int portNumber;"

**What is the expected output? What do you see instead?**
And int attribute in my class.  Instead, I get the warning:

Warning on line 3 : Feature under development. 'int' found and ignored. processed as:
'{1}'. More information (9999)

**What version of the product are you using? On what operating system?**
Umple Online, accessed Oct 27, 2014 at 10:30PM.  OS Windows 7 SP1, using Chrome.

**Please provide any additional information below.**

Seems to work with "int port_number;" but not "int portNumber;"

---

Reported by `alex@snowycloud.com` on 2014-10-28 02:58:00

**Comment by Nava2** [comment]
It seems that

int portX;

also causes this issue, where X can be anything alphabetic.

It is a side-effect of the development of ports in Umple. It should go away in due
time. Thanks for reporting.

---

Reported by @umple on 2014-10-30 17:56:05
- **Status changed**: `Accepted`
- **Labels added**: Priority-Low, Diffic-VEasy
- **Labels removed**: Priority-Medium, Diffic-Med
- **cc added:** +@ahmedvc

**Comment by TimLethbridge** [comment]
It is OK for this to cause the error if the word 'port' is present; just not 'port' followed by something without a space.

**Comment by TimLethbridge** [comment]
After this is fixed, please verify that 

```
class X {
 private conjugated port theport [4];
}
```
does not generate any errors in Java, but does generate code in C++

**Comment by TimLethbridge** [comment]
This was fixed by pr #1367 (which accidentally referenced 564)
