### ISSUE TITLE
Ability to generate diagrams from a subset of classes

### ISSUE THREAD

**Issue by Nava2** [umple/umple#549]
Originally reported on Google Code with ID 651

---

Using the suboptions capability it should be possible to generate gv class diagrams
for

a) Just a particular set of classes/interfaces, and the associations/generalizations/
among them

b) Just a set of classes and neighbouring or tree of classes (by association/generalization/etc).

c) Just the classes in the selected namespaces/packages

The selected classes or namespaces would be arguments to the suboption

---

Reported by @umple on 2014-11-07 22:54:21

**Comment by Nava2** [comment]
This capability for filtering should have a standard syntax that should also be made
to work on the metrics generators, and any other such generators where it makes sense

---

Reported by @umple on 2014-11-09 13:19:38
- **Owner removed**

**Comment by TimLethbridge** [comment]
This has been solved with the 'filter' capability

**Comment by TimLethbridge** [comment]
This is now in UmpleOnline as of PR #2198
