### ISSUE TITLE
infinte loop parsing certain Umple code

### ISSUE THREAD

**Issue by Nava2** [umple/umple#551]
Originally reported on Google Code with ID 653

---

The following code causes an infinite loop, most likely in the parser. It causes compilation
to use up all the CPU until killed. This was causing big problems with UmpleOnline
until CPU limits were installed

Nonetheless this case needs investigating

class CarWindowController {
  CarWindow {
   Open {
      up[x.y -> Closing;

```
}
```

  }
}

---

Reported by @umple on 2014-11-15 21:35:24

**Comment by Nava2** [comment]
Started to look into it.

---

Reported by `ufowam` on 2015-02-11 03:51:33

**Comment by TimLethbridge** [comment]
This was fixed long ago. There is no longer an infinite loop in this case
