### ISSUE TITLE
Missing timer in certain state machines

### ISSUE THREAD

**Issue by Nava2** [umple/umple#552]
Originally reported on Google Code with ID 654

---

In the attached code the followin trace occurs:

/Users/tcl/tmp/Student/Window.java:961: error: cannot find symbol
  public static class TimedEventHandler extends TimerTask  
                                                ^
  symbol:   class TimerTask
  location: class Window
/Users/tcl/tmp/Student/Window.java:966: error: cannot find symbol
    private Timer timer;
            ^
  symbol:   class Timer
  location: class TimedEventHandler
/Users/tcl/tmp/Student/Window.java:973: error: cannot find symbol
      timer = new Timer();
                  ^
  symbol:   class Timer
  location: class TimedEventHandler

---

Reported by @umple on 2014-11-17 16:41:13
- _Attachment: [A6v3Leung.ump](https://storage.googleapis.com/google-code-attachments/umple/issue-654/comment-0/A6v3Leung.ump)_

**Comment by TimLethbridge** [comment]
For some reason the code is not injecting

import java.util.*;

Which it does do from the timer examples in the user manual at

https://cruise.eecs.uottawa.ca/umple/TimedTransitions.html
