### ISSUE TITLE
Interfaces not showing up in editable view of umple online

### ISSUE THREAD

**Issue by Nava2** [umple/umple#560]
Originally reported on Google Code with ID 662
Owned by @aforward

---

With the following model

{{{
interface Person  
{  

} 

class Mentor
{
  isA Person;
}
}}}

You will see the mentor, but not the Person interface when looking at the editable
view.  You should!

---

Reported by @aforward on 2015-01-16 14:50:04
- _Attachment: Screen Shot 2015-01-16 at 6.50.41 AM.png<br>![Screen Shot 2015-01-16 at 6.50.41 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-662/comment-0/Screen Shot 2015-01-16 at 6.50.41 AM.png)_

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-16 14:53:23
- _Attachment: Screen Shot 2015-01-16 at 6.50.19 AM.png<br>![Screen Shot 2015-01-16 at 6.50.19 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-662/comment-1/Screen Shot 2015-01-16 at 6.50.19 AM.png)_

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-16 15:07:39
- **Blocking**: #563

**Comment by TimLethbridge** [comment]
This was solved some time in the past
