### ISSUE TITLE
Tooltip for intefaces (graphviz) shows a \N with no other useful information

### ISSUE THREAD

**Issue by Nava2** [umple/umple#561]
Originally reported on Google Code with ID 663
Owned by @aforward

---

In umpleonline take a look at the tooltip for an interface in the graphviz view, you
will only see a \N. It should show the similar type of information as available for
a class tooltip.

interface Person  
{  

} 

class Mentor
{
  isA Person;
}

---

Reported by @aforward on 2015-01-16 14:55:47

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-16 14:56:12
- _Attachment: Screen Shot 2015-01-16 at 6.52.21 AM.png<br>![Screen Shot 2015-01-16 at 6.52.21 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-663/comment-1/Screen Shot 2015-01-16 at 6.52.21 AM.png)_
- _Attachment: Screen Shot 2015-01-16 at 6.56.11 AM.png<br>![Screen Shot 2015-01-16 at 6.56.11 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-663/comment-1/Screen Shot 2015-01-16 at 6.56.11 AM.png)_

**Comment by vahdat-ab** [comment]
The bug has been fixed.
