### ISSUE TITLE
Unused interfaces are not shown in graphviz UI

### ISSUE THREAD

**Issue by Nava2** [umple/umple#562]
Originally reported on Google Code with ID 664
Owned by `vivianxinxinkou`

---

With the following mode, you will see the Person interface

interface Person {}
class Mentor { isA Person; }

But, if the interface is unused you don't see it

---

Reported by @aforward on 2015-01-16 15:02:37

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-16 15:05:23
- _Attachment: Screen Shot 2015-01-16 at 7.01.54 AM.png<br>![Screen Shot 2015-01-16 at 7.01.54 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-664/comment-2/Screen Shot 2015-01-16 at 7.01.54 AM.png)_
- _Attachment: Screen Shot 2015-01-16 at 7.04.57 AM.png<br>![Screen Shot 2015-01-16 at 7.04.57 AM.png](https://storage.googleapis.com/google-code-attachments/umple/issue-664/comment-2/Screen Shot 2015-01-16 at 7.04.57 AM.png)_

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-18 19:38:40
- **Owner changed**: `vivianxinxinkou`

**Comment by Nava2** [comment]
Reported by @aforward on 2015-01-18 19:51:23
- **Blocked on**: #571

**Comment by vahdat-ab** [comment]
I've checked both graphical representations and it looks like the bug has been fixed.
