### ISSUE TITLE
Support for concurrent state machines in state table generation

### ISSUE THREAD

**Issue by Nava2** [umple/umple#569]
Originally reported on Google Code with ID 671

---

THIS IS RELATED TO #670

If you run the following

class Student
{

  status {

```
CrossingGuard {
  power -> Off;

  Walk {
    push -> DontWalk;
  }
  DontWalk { 
    push -> DontWalk; 
  }
  ||
    Green { 
      carAppraoch -> Red;
    }
  Red { 
     carApproach -> Green;
  }
}
Off { power -> CrossingGuard; }
```

  }

}

The state table doesn't support two things that it should.  First, much like nested
state machines, it should show the events related to the parent state (which should
be solved by #670).  Second, the display of the actual tables should keep the states
together to show the concurrency

---

Reported by @aforward on 2015-01-17 23:17:50

**Comment by Nava2** [comment]
I am trying to think of a way to deal with this. In the example there are two sets of
concurrent states: Walk/DontWalk and Green/Red. The statemachine can independently
switch between the concurrent states, leaving us with 4 possible positions in the state
machine (Walk-Green, Walk-Red, DontWalk-Green, DontWalk-Red). My first thought re:
"keep the states together to show the concurrency" is to have these 4 possible positions
as headers. So instead of 4 independent states, there are 4 combined states.

Here's how the example would work:
https://docs.google.com/spreadsheets/d/1ouxNcw7KutWN6E0_54euOnfF3PJyvmirMpVXb0nqiAg/edit?usp=sharing

---

Reported by @CraigBryan on 2015-03-01 16:29:53

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2015-03-01 16:30:11
- **Labels added**: stateMachines

**Comment by TimLethbridge** [comment]
The only problem with the proposes solution is that there could be an explosion of the number of possible state combinations. I think the generator would have to detect that and only give a subset if there are going to be more than, for example 50 combinations for a given set of states

**Comment by TimLethbridge** [comment]
A remaining edge case is transition between nested states, if the parent states differ.

**Comment by Delta-Hat** [comment]
`class Student
{
  status{
    ParentState1
    {
      crossDown -> AwayChildState2;
      ChildState1
      {
        action -> ChildState2;
      }
      ChildState2
      {
        action -> ChildState1;
        crossUp -> ParentState2;
      }
      ||
      OtherChildState1
      {
        otherAction -> OtherChildState2;
      }
      OtherChildState2
      {
        otherAction -> OtherChildState1;
      }
    }
    ParentState2
    {
      reset -> ParentState1;
      AwayChildState1
      {
        awayAction -> AwayChildState2;
      }
      AwayChildState2
      {
        awayAction -> AwayChildState1;
      }
    }
  }
}`
crossDown event should lead to ParentState2 (AwayChildState2).
crossUp event should lead to ParentState1 (AwayChildState1).
Currently, validation function returns false for all state combinations with these kinds of transitions.

Part of the issue is that the validation function, when scanning through a nesting level, doesn't take into account that the nextState or fromState might be on a different nesting level and that, said transition would lead to a difference in states in the nesting level it's scanning.

**Comment by Delta-Hat** [comment]
`class Student
{
  status{
    ParentState1
    {
      ChildState1
      {
        action -> ChildState2;
      }
      ChildState2
      {
        action -> ChildState1;
      }
      ||
      OtherChildState1
      {
        otherAction -> OtherChildState2;
        crossAnd -> ChildState2;
      }
      OtherChildState2
      {
        otherAction -> OtherChildState1;
      }
    }
  }
}`

validation function does not support and-cross transitions such as this.

![image](https://user-images.githubusercontent.com/28057051/165718074-1dc236b8-5f98-4496-b316-9b591512e1f9.png)

ParentState1 (OtherChildState1 || ChildState1) needs to have its crossAnd transitions detected.
The validation function doesn't take into account that nextStates can be on different nesting levels except in the case where the transition is between a state's own parent state.

**Comment by Delta-Hat** [comment]
It might be a good idea to, if possible, to implement a system where a CompositeStateWrapper can be converted into a status and vice versa. If one can do that, one could run a mini simulation of the transition and compare the resultant state to the CSW being checked.
