### ISSUE TITLE
Missing dot library (Graphviz) error shown when state machine syntax is wrong. 

### ISSUE THREAD

**Issue by Nava2** [umple/umple#574]
Originally reported on Google Code with ID 676

---

The error in question is:

```
dot (part of GraphViz) does not appear to be installed on the server
in /usr/local/bin/dot
```

And it will appear with some invalid state machine code when generating Graphviz State
Machines.

An example:

class StateMachineFun {
  sm {
    s1 {

  //There should be a '}' here
}

The missing curly brace makes a appropriate error appear:

```
Error on line 1 : Parsing error: Structure of 'class' invalid. More
information (1502)
```

But it also has the missing library error in the main diagram pane.

---

Reported by @CraigBryan on 2015-02-09 01:18:38

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2015-02-22 17:11:36
- **Owner removed**

**Comment by TimLethbridge** [comment]
I have changed the error message and will shortly submit a PR which should close this.
