### ISSUE TITLE
Filter parser isn't handling the following code in umpleonline

### ISSUE THREAD

**Issue by Nava2** [umple/umple#579]
Originally reported on Google Code with ID 681
Owned by `vivianxinxinkou`

---

If you run the following code, umpleonline barfs

class Student
{
  0..1 -- 0..1 Mentor;
}

class Mentor
{
}

class School
{
- -> \* Mentor;
- -> \* Student;
  }

filter X  {
  Student;
}

The issue is the "{" on the same line as filter X, please fix.

---

Reported by @aforward on 2015-02-25 18:49:22

**Comment by Nava2** [comment]
Actually, it has nothing to do with the "{" (I was doubting myself so wanted to check
some more).  The issue looks more like the filter is baulking at the relationship between
the filtered out classes and filtered in.

---

Reported by @aforward on 2015-02-25 18:53:48

**Comment by Nava2** [comment]
Relationships between filtered out/in classes are removed, then the issue is resolved.

---

Reported by `vivianxinxinkou` on 2015-03-02 18:27:23
- _Attachment: issue579.png<br>![issue579.png](https://storage.googleapis.com/google-code-attachments/umple/issue-681/comment-3/issue579.png)_
- _Attachment: issue681_2.png<br>![issue681_2.png](https://storage.googleapis.com/google-code-attachments/umple/issue-681/comment-3/issue681_2.png)_

**Comment by TimLethbridge** [comment]
This example code above is outdated, the correct code would be:

class Student
{
0..1 -- 0..1 Mentor;
}

class Mentor
{
}

class School
{
- -> \* Mentor;
- -> \* Student; }

class Something {}

filter {
  include Student;
}

This now seems to work just fine.

Closing issue
