### ISSUE TITLE
'Ruby' appears twice in Umple command line compiler's 'generate' option

### ISSUE THREAD

**Issue by Nava2** [umple/umple#603]
Originally reported on Google Code with ID 705
Owned by @umple

---

**What steps will reproduce the problem?**
1. View the 'help' output of the umple command line compiler (`java -jar umple.jar
--help`)
2. Look at the comment for the 'generate' option

**What is the expected output? What do you see instead?**
'Ruby' appears twice in the list of possible languages.

**Please use labels and text to provide additional information.**

---

Reported by `jzwiep` on 2015-04-13 04:38:42

**Comment by TimLethbridge** [comment]
This is be fixed now!
