### ISSUE TITLE
Having generated methods for abstract classes that implement interfaces

### ISSUE THREAD

**Issue by Nava2** [umple/umple#608]
Originally reported on Google Code with ID 710
Owned by @vahdat-ab

---

Umple automatically generates a default implementation for those methods inside interfaces
not implemented in the class. This is reasonable when the class is not abstract (although
developers must get warning on it). If the class is abstract, there must not be a default
implementation. Those methods must be implemented by subclasses of that class. 

interface I {
  Integer I1(); 
}

class A {
  isA I;
}

class B {
  abstract;
  isA I;
}
class C {
  isA B;
}

class A gets an automatic implementation for the method I1(). class B gets an automatic
implementation for the method I1() which is wrong because it is abstract. 
class C doesn't need to implement the method I() because it's already been implemented,
but it's wrong and there is no valid code there. This can sometimes create defects
which are hard to notice. There must always warnings regarding these kinds of situations.

---

Reported by @vahdat-ab on 2015-06-04 20:34:14

**Comment by vtrlx** [comment]
I'd like to take this one.
