### ISSUE TITLE
Eclipse Development Setup is incorrect

### ISSUE THREAD

**Issue by Nava2** [umple/umple#612]
@vahdat-ab brought up that the steps for getting the new build to work with Eclipse were outdated. This issue tracks this problem. 

[Development Setup Wiki Page](https://github.com/umple/umple/wiki/DevelopmentSetUp)
#611 started this issue.

**Comment by vahdat-ab** [comment]
It worked.
thanks.

**Comment by Nava2** [comment]
Closing
