### ISSUE TITLE
Re-enable TravisCI testing

### ISSUE THREAD

**Issue by aforward** [umple/umple#616]
There are batch-mode issues with testing in TravisCI and Umple that need to be resovled.  This ticket will track progress to get this back and running within TravisCI.

**Comment by Nava2** [comment]
Tests have been re-enabled within #665. However, @TimLethbridge noticed I missed the testbed. 

I'll fix create a new PR to address adding the test-bed for both OS X and Linux. I will have to add the language dependencies for OS X to have them run.
