### ISSUE TITLE
Enable offline building through "ant bootstrap"

### ISSUE THREAD

**Issue by aforward** [umple/umple#617]
The current build mechanism requires an internet connection.  Ideally, we could run a "bootstrap" ant task to get all necessary dependencies, and then all additional build scripts would run assuming the environment was setup.  The "local" (as in ant -Dmyenv=local) would run in this offline mode, but connected entities (like a build server) could be run in an always on mode (but it should be configurable).

The bootstrap task _would_ need internet connectivity.

**Comment by Nava2** [comment]
What about having a conditional online build? I don't like the idea of
having bootstrap doing all of the dependencies. Some will change at some
point and will need to be updated.

I think having a property that is set after testing an Internet connection
would be a good idea.. Such as trying the ivy resolve and if it fails, fall
back on an offline approach.

After ivy is run once, the libraries pulled in are all put into a
consistent place: dist/lib/[CONF]. Ivy may also have a caching mechanism
that is more offline than the default one. I will look into this today.

**Comment by aforward** [comment]
That's what I am saying.

A config in our environments would set online or offline, and for those in the "offline" mode, they would be expected to run "bootstrap" from time to time to update libs

**Comment by Nava2** [comment]
I'm going to do this via [`<condition @isreachable>`](https://ant.apache.org/manual/Tasks/conditions.html#isreachable) and ant-contrib's [`<if>`](http://ant-contrib.sourceforge.net/tasks/tasks/if.html). Seems like exactly what we need.

**Comment by Nava2** [comment]
I've been working on this for a bit. I now have checks for whether the build is offline or not. It also will update if it is online, otherwise it will use what is present. I need to polish it before I open a PR.

**Comment by Nava2** [comment]
There was a problem in the PR, reopening as per @TimLethbridge request.

**Comment by Nava2** [comment]
Blocked by #639 (I blew out my dist/ folder and don't have a jar anymore).
