### ISSUE TITLE
Images for the Wiki 

### ISSUE THREAD

**Issue by CMeerkerk** [umple/umple#621]
*NOTE: Issue needs to be resolved in 2015!

Problem: The correct images are on Google Code the links are correct in the alt. text of the images however the GitHub Wiki does not display the images.

To resolve: Get images from google code locations and move them to a new location that works with the GitHub Wiki and the links must be updated

**Comment by Nava2** [comment]
If using the web interface, you can drag and drop images. Otherwise,
hosting via imgur or another host works too.

**Comment by TimLethbridge** [comment]
Images on Google code are long gone. Any will have to be recreated.
