### ISSUE TITLE
Multilayer Modeling support in Umple

### ISSUE THREAD

**Issue by obahy** [umple/umple#627]
The idea is to add different layers of information.  E.g. complexity, coupling, cohesion.  Those layers could then manifest themselves in UI hints (e.g. more complex classes are physically bigger, highly coupled classes would have a thicker border and cohesion classes would share a common colour / gradient).

**Comment by obahy** [comment]
There was a paper in Models 2015 on Multilayer modeling that embodies some of those ideas, and a papyrus plugin.

**Comment by TimLethbridge** [comment]
This is too abstract ... and we have too many other things to work on.
