### ISSUE TITLE
Fix problem with nondeterministic timer dependent tests

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#629]
When the server runs slowly we have been getting failures on

cruise.queued.statemachine.test.MultipleQueuedStateMachinesTest (1)
cruise.queued.statemachine.test.QueuedStateMachineTest_timedTransition_1 (1)
cruise.statemachine.test.DoActivityTest (1)

Some of these were already commented out. Others will have to be deactivated then fixed since we have been getting random build fails

Test Failures (2)
cruise.queued.statemachine.test.QueuedStateMachineTest_timedTransition_1 (1)
TestName: processEvents Duration: 2.067

Expected: not <0>
     but: was <0>

```
                            junit.framework.AssertionFailedError: 
```

Expected: not <0>
     but: was <0>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at cruise.queued.statemachine.test.QueuedStateMachineTest_timedTransition_1.processEvents(QueuedStateMachineTest_timedTransition_1.java:59)

cruise.statemachine.test.DoActivityTest (1)
TestName: autoTransitionSyncAfterMultipleDo Duration: 1.941
                                expected:<[1, 2, [3]]> but was:<[1, 2, []>

```
                            junit.framework.AssertionFailedError: expected:<[1, 2, [3]]> but was:<[1, 2, []>
at cruise.statemachine.test.DoActivityTest.autoTransitionSyncAfterMultipleDo(DoActivityTest.java:49)
```

**Comment by Nava2** [comment]
I think this is a duplicate of #591. However, I can actually do my proposed solution. I just forgot about it.

**Comment by TimLethbridge** [comment]
This is a duplicate
