### ISSUE TITLE
Have myenv default to `local` when building

### ISSUE THREAD

**Issue by Nava2** [umple/umple#633]
## Description

Currently, myenv defaults to `cc`. This is a very specific case and most people are building via local developments. When building this way, one often types commands by hand. 

In contrast, when working with a build environment when scripting, e.g. Travis, or CC, you're writing scripts where it is straight forward to add the -Dmyenv=local to the script parameters. 
## Suggested fix

Change (`_template.xml`):

``` xml
<property name="myenv" value="cc" />
```

to: 

``` xml
<property name="myenv" value="local" />
```
## Known issues

This may require changes to the CC scripts. I do not have access to them, thus I have no idea about the scope of this change. 

Opening this as a discussion.

**Comment by Nava2** [comment]
I wrote a script to automatically find the environment: 

``` ant
<property environment="env"/>

  <!-- Try to detect the environment: -->
  <condition property="auto-myenv" value="travis">
    <and>
      <isset property="env.CI" />
      <isset property="env.TRAVIS" />
    </and>
  </condition>

  <condition property="auto-myenv" value="appveyor">
    <and>
      <isset property="env.CI" />
      <isset property="env.APPVEYOR" />
    </and>
  </condition>


  <local name="computer.hostname" />
  <exec executable="hostname" outputproperty="computer.hostname"/>

  <condition property="auto-myenv" value="cc">
    <and> <!-- Check for CC on cruise -->
      <os family="unix" />
      <equals arg1="${computer.hostname}" arg2="cruise.eecs.uottawa.ca" />
    </and>
  </condition>

  <condition property="auto-myenv" value="local">
    <os family="unix" />
  </condition>

  <condition property="auto-myenv" value="wlocal">
    <os family="windows" />
  </condition>

  <echo message="auto-myenv=${auto-myenv}" />
```

However, I do not want to consider swapping out the setting of `myenv` with it until I can get a confirmation of a CC variable. @TimLethbridge what is the output of `hostname` on cruise control?

Here is a checklist of targets: 
- [x] Windows -> `wlocal`
- [x] Unix (osx and Linux) -> `local`
- [x] Travis -> `travis`
- [x] Appveyor -> `appveyor`
- [ ] CC -> `cc`

E: Appveyor is a windows build CI that is free.. I'm trying to get umple building and I'm pretty close. :+1:

**Comment by TimLethbridge** [comment]
on cc, the output of hostname is
cruise

**Comment by Nava2** [comment]
Thanks, @TimLethbridge!
