### ISSUE TITLE
Umple Jar location has changed

### ISSUE THREAD

**Issue by Nava2** [umple/umple#639]
http://try.umple.org/scripts/umple.jar does not point to the latest stable umple jar anymore.

We need this for our bootstrapping in the build chain, where is this file located now?

**Comment by Nava2** [comment]
It looks like Cruise Control will let artifacts be placed in any folder. The artifacts could be put in a public folder for the HTTP server and we wouldn't need to "hack" around and download it from umpleonline's scripts. 

![](https://cloud.githubusercontent.com/assets/302365/10710872/44284816-7a38-11e5-8e0a-5f9b52f67181.png)

**Comment by Nava2** [comment]
This appears to have resolved. I've opened #653 to try to address this issue in the future.

**Comment by TimLethbridge** [comment]
No it is not resolved. It remains very annoying. Any push to master causes cruise control to fail because it tries to get the version of umple.jar that has not been created yet. A first-build has to be done every single time.
