### ISSUE TITLE
Sync with diagram when user has stopped typing. 

### ISSUE THREAD

**Issue by charle692** [umple/umple#640]
Just an idea, but currently when a user stops typing, Umple syncs with the diagram right away. This is quite annoying when trying to type again as the whole system lags.

I understand that syncing with the diagram is important however maybe you could delay syncing by 5 seconds after the user has stopped typing? That way if they start back up quickly again it doesn't cause any lag and delay in typing.  

This seems to affect Editable Diagram class type more than the GraphViz.

**Comment by TimLethbridge** [comment]
It delays syncing for 3 seconds. If you don't want it to sync, you can switch to manual mode, or hide the diagram (e.g. using control-D). The suggestion here is for 5 seconds. Perhaps that would be better than 3. But I suppose what is really needed is an experiment to see what most users prefer, and also to allow the threshold to be set.
