### ISSUE TITLE
Add user manual examples of some Errors and Warnings

### ISSUE THREAD

**Issue by charle692** [umple/umple#641]
Links for more information on errors or warnings don't actually link to more information. They just redirect to the Umple home page. 

I think errors are being sent to the wrong location. For example, when looking at "More Information (1006)" it's trying to redirect to http://umple.org/W1006StateMachineNotParsed.html instead of something along the lines of http://cruise.eecs.uottawa.ca/. 

![image](https://cloud.githubusercontent.com/assets/5891054/10810376/b837cea6-7dd6-11e5-9a31-58ac395f0343.png)

**Comment by TimLethbridge** [comment]
Attached is a spreadsheet showing the status of pages that need updates, mostly to error and warnings pages
[ErrorInventory.xlsx](https://github.com/umple/umple/files/2036728/ErrorInventory.xlsx)
