### ISSUE TITLE
Separate tabs do not appear for auxiliary files

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#650]
In Umpleonline, the following code produces X.java and also ConsoleTracer.java, but ConsoleTracer.java does not appear when 'Show Files in Separate Tabs' is invoked

``` java
class X {
  a;
  trace a;
}
```

**Comment by TimLethbridge** [comment]
The problem here is the 'extra files' generated in certain contexts are not being displayed. Only the files based on a one-to-one mapping with the Umple classes. This may require changing the way the splitting of the output works.

Thorough testing with many examples and many types of generated output would be needed to ensure that a fix does not cause other unintended effects.

**Comment by TimLethbridge** [comment]
In the following code, only tab Qx appears. This may be related, and should be fixed too.

``` java
class Qx {}
class Xs {}

association { * Qx qx -- * Xs xs; }
```

**Comment by TimLethbridge** [comment]
here's another example. No tabs appear at all!

class X{
isA T;
}

trait T{
X name
}

**Comment by vtrlx** [comment]
I'll take this issue to start out.

I'll probably just spend time until the code sprint testing different outputs in my local umpleonline and understanding how tabs are displayed and generated in the app.

**Comment by vahdat-ab** [comment]
Great. I've assigned this to you.
Good luck.
