### ISSUE TITLE
Make GraphViz the default for generated diagrams

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#673]
Currently when opening Umpleonline, the default is to use editable class diagrams. However these tend to be messy. The GraphViz generated ones are nicely laid out.

We should move to having gvclass the default (it is currently one of the options in UmpleOnline).

Be careful to ensure that when examples are loaded that are state machines, UmpleOnline still correctly switches to gestate as the default drawing mode (i.e. make sure this doesn't break). And make sure that when any class diagram examples are loaded after viewing a state diagram example, that UmpleOnline shows them in gvclass mode.

**Comment by vahdat-ab** [comment]
@TimLethbridge  I wonder if you still want to have this? The reason is that we might switch soon to the JointJS.

**Comment by TimLethbridge** [comment]
Good point. However, a quick investigation suggests that it might be JointJS that could be slowing down UmpleOnline loading now. I have raised issue #949 on this Also we have some way to go to perfect it. I agree it would be better to focus on other things.

**Comment by TimLethbridge** [comment]
Joint.js might eventually become the default once it is finished. I am closing this for now. Our editable tool has sped up a lot. We will consider which is the default later
