### ISSUE TITLE
Arrays marked const lose their array qualifier in translation

### ISSUE THREAD

**Issue by bitwizeshift** [umple/umple#689]
Any array variable marked 'const' loses `[]` in translation to Java/C++/php/etc..

Example:

```
class A{
  const String[] S = {"...","..."};
}
```

Java output:

```
public class A
{
  ...
  public static final String S = "...","...";
  ...
}
```

**Comment by Shikib** [comment]
The issue extends to initializing arrays with values overall. The following code doesn't generate a member variable at all.

```
class A {
  String[] S = {"a", "b"};
}
```
