### ISSUE TITLE
State machine code generation issuing incorrect warning for duplicate state transitions

### ISSUE THREAD

**Issue by mkmicik** [umple/umple#690]
When defining a state machine with duplicate state transitions like so:

class A{
    status {
        on{
            turnOff() -> off;
            turnOff() -> off;
        }
        off{
            turnOn -> on;  
        }
    }
}

warning 54 is issued. This scenario is technically allowed by the compiler and should be ignored.

**Comment by TimLethbridge** [comment]
But it _is_ true that the duplicate is ignored. I don't see this is particularly worth worrying about.

The warning was, I agree, supposed to flag cases where the destination state is different in the duplicate case, so I suppose it could be turned off if the destination is the same. But very low priority.

**Comment by vahdat-ab** [comment]
@mkmicik this is going to be resolved by pay more attention to the issue #656. The same methods are responsible can be responsible for this.

**Comment by vahdat-ab** [comment]
Since the second transition is detected properly and a proper warning is raised so I think this issue can be ignored. I'm closing this.
