### ISSUE TITLE
Umple build doesn't work offline

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#699]
It's supposed to have completely offline build process, but currently it's not working properly. 
You have to have internet connection in order to be able to build Umple.
If the parameters -Donline=true is used, there is no problem.

**Comment by Nava2** [comment]
Doing some investigation..
- :exclamation: `ant -Donline=false bootstrap`: PASSED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-offline-bootstrap-log)
- :+1: `ant -Donline=true bootstrap`: PASSED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-online-bootstrap-log)
- :exclamation: `ant -Donline=false -Dmyenv=local first-build`: FAILED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-offline-first-build-log)
-  :+1: `ant -Donline=true -Dmyenv=local first-build`: PASSED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-online-first-build-log)
- :+1: `ant -Donline=false -Dmyenv=local`: PASSED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-offline-full-log)
- :+1: `ant -Donline=true -Dmyenv=local`: PASSED [(Log)](https://gist.github.com/Nava2/3db03e2cdf6e95ae3352#file-online-full-log)

**Comment by Nava2** [comment]
Couple problems:
- [ ] Check for `online` being defined doesn't work for `bootstrap` target.
- [ ] `first-build` requires a network, `deps-resolve-all` fails because there is no network, should this target be called at all?

**Comment by TimLethbridge** [comment]
Fixed by PR #863
