### ISSUE TITLE
Umple Template Duplicate Template gives no feedback

### ISSUE THREAD

**Issue by Diusrex** [umple/umple#712]
When a class has multiple templates with the same name, there is no warning that earlier instances are being ignored. There should probably be a warning if possible, to keep the templates behavior similar to the rest of umple

For the example code:

```
class Generate
{
    template <<! x !>>
    template <<! y !>>

    emit gen()(template);
}
```

gen will just return a string that contains 'y', without warning that the earlier occurrence is being ignored.

**Comment by TimLethbridge** [comment]
Resolved. Now generates warning 3506
