### ISSUE TITLE
Umple Code Refactoring

### ISSUE THREAD

**Issue by bitwizeshift** [umple/umple#714]
As discussed in #709, refactoring various parts of Umple.

Taken from the previous issue thread (and slightly modified): 
For this project I will be doing the following:
- Removing coupling and extracting the Parser (`RuleBasedParser`) and all subclasses into an individual project/Module
  - Extract the files into an individual modifiable Git project
- Modify Ant build to compile all modules into the full version of Umple
  - Figure out a way for Ant to cache necessary sources for subsequent builds, only updating if the source has changed (perhaps with git hashes?). This way we don't pull in the code for the Parser each time we run Ant, which would increase build times. 
- Extract the Analyzer into different classes, so it isn't entirely in `UmpleInternalParser`. This has partially been done, so I just need to finish it, implement it, and test it (probably a lot easier said than done).
- General code refactoring/clean up
- Removing unnecessary dependencies
- If possible, where applicable, I'd like to document as well so that the javadocs don't have empty descriptions
- If time: Extract the Code generator (the umple template java generator) into a separate project, as it has further applications outside Umple as well

@vahdat-ab @TimLethbridge @Nava2 @aforward 

Everything with regards to the basic refactoring will be discussed here so that it's separate from the plugin architecture.

**Comment by Nava2** [comment]
> Figure out a way for Ant to cache necessary sources for subsequent builds, only updating if the source has changed (perhaps with git hashes?). This way we don't pull in the code for the Parser each time we run Ant, which would increase build times.

Most "submodule" solutions will let you tag a repository with a branch or commit (even if you use the generic approach). I would not worry about this too much, it should be a given by the solution. 

Whatever solution is used, "fetching" the repository should bring in all of the modules as required. I would strongly suggest not considering "optional" modules.

**Comment by bitwizeshift** [comment]
> Most "submodule" solutions will let you tag a repository with a branch or commit (even if you use the generic approach).

I'm still personally in favor of a submodule approach, but @aforward and @TimLethbridge are less for the idea -- which is why I'm looking into pulling it in during the build portion instead.

This way it can still be an individual project managed through git, but something that is built as part of the build process (instead of embedded in the repo). The only issue with this approach is that, if not done correctly, it could require frequent downloads of the source code for the build. If I can find a way to properly cache the code downloaded from a separate repo and only update if there have been changes made, then this could resolve this issue entirely without any need for submodules.

For the time being I'm going to be working on decoupling some of the classes and extracting them into the same repository, but in a root-level directory. This way when a solution is decided on it should be easier to move it to a separate repository later.

**Comment by Nava2** [comment]
> I'm still personally in favor of a submodule approach, but @aforward and @TimLethbridge are less for the idea -- which is why I'm looking into pulling it in during the build portion instead.

Caveat to having something in Ant.. there will be little support for "modern" tooling with Ant. Additionally, it would _likely_ put a hard requirement on having an internet connection -- this is a problem, checkout #699. 

I'm fairly confident a tool like Gradle would have a plugin that _someone_ wrote somewhere. If not.. writing this advanced of logic in Groovy would be a god-send in comparison to Ant. _shrug_

> For the time being I'm going to be working on decoupling some of the classes and extracting them into the same repository, but in a root-level directory. This way when a solution is decided on it should be easier to move it to a separate repository later.

Great. Solid start! :+1:

**Comment by Nava2** [comment]
I'm sorry for all the "yellow fever" that this will might give your warning screens, but I would recommend working through Eclipse, turning up the Java warnings and really working to remove them. Some will be problems with generated code, but perhaps they can be fixed too?

[Eclipse Warnings](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fcompiler%2Fref-preferences-javadoc.htm)

**Comment by bitwizeshift** [comment]
I was positive I replied to this the same day you posted -- sorry about how late this is!

Though that is a great idea, it might be moving a little bit further from the original scope of the project. I just don't want to get too side-tracked and not be able to complete my term project (extracting the parser and working on the Analyzer). 
Definitely not something I'm discounting though -- I'm happy to look into it when I have the time, since it seems like an important thing to have correct.

**Comment by bitwizeshift** [comment]
So I encountered something a little strange in the `RuleBasedParser`, and I was hoping someone may be able to explain it.

The method `setupRules(boolean forceParse)` in the `RuleBasedParser` has some code with execution paths that are never reached.

Here's a small snippet of what I'm referring to starting at [line 74 of `GrammarParsing_Code.ump`](https://github.com/umple/umple/blob/9fbd7d622528704b3addb7c3fbf95874cc48f1a8/cruise.umple/src/GrammarParsing_Code.ump#L74).

```
    boolean mustParse = true; <-- This never changes
    try {
      File rulesfile = new File(new File("cruise.umple").getAbsolutePath()+File.separator+"bin"+File.separator+"rules.grammar");

      if(rulesfile.exists()&&rulesfile.canRead())
      {
        reader = new BufferedReader(new FileReader(rulesfile));
      }
      else
      {
        resourceStream = getClass().getResourceAsStream(File.separator+"rules.grammar");
        if(resourceStream == null)
        {
          mustParse = true; <-- This is always true
          reader = null;
        }
        else
        {
          reader = new BufferedReader(new InputStreamReader(resourceStream));  
        }          
      }
      if(mustParse || forceParse) <-- mustParse is always true, this is the only flow of execution
      {
        readGrammarFiles();
        if(rulesfile.exists()&&rulesfile.canWrite()){
          rulesfile.delete(); <-- Delete the file ?
        }
        // ...
      }
      else if(reader!=null) <-- Never reached
      {
        // ...
      }
```

`mustParse` exists in only 3 places in this entire method. It exists in the declaration, beginning as `true`. It changes to `true` if the resource is not found, and then the if statement checks if it's true. 

This means that the entire flow of execution will always hit that first if statement, and never reach anywhere else. Even more curiously, this file gets deleted in the event that it exists on the disk, and everything continues on without ever making use of it. Another weird thing is the fact that I can't find a `rules.grammar` file in the repository anywhere, so I'm not sure why that's hardcoded.

Does anyone know if this code is in any way important, and left this way as a temporary measure? 

A `git blame` shows this was written in late 2013, where the original code had `mustParse` start as `false` -- but later changed by the same person (Geoffrey Guest) in early 2014 to start as `true`. This makes me suspect that it's just outdated/deprecated code that is no longer necessary.

Commenting or deleting the unnecessary lines (expectedly) resulted in it compiling perfectly and passing all the build tests.

Does anyone have any thoughts on this?

**Comment by TimLethbridge** [comment]
What is supposed to be happening is that the grammar must only be parsed if the cache does not exist. If you are going to be doing a lot of compiles, then the idea is parse the grammar and save the cache of it that can be quickly loaded, then delete the cache (in the build process) when you are done. The build does delete that cache, and when must parse is true presumably it should delete the cache before parsing the grammar and recreating it.

Rules.grammar should never be saved in the repo ... it should exist only during a build.

However why it was changed in 2014 to set it to be always true is unclear. This might have been a temporary workaround for something.

Can you set the boolean mustParse = true; line to false and see what happens. In particular, see if there are any timing differences if, for example you compile Master.ump 2 times in a row with it false as opposed to with it true, or compile a simple file 100 times in a row with it false as opposed to true. If it turns out to not make a significant difference, then we should consider deleting that cache functionality.

**Comment by bitwizeshift** [comment]
I was going to reply to the email you sent regarding the `rules.grammar` file, but I'll just reply here instead. 

Thanks for getting back to me about that, I could not figure out what the point of that file was supposed to be. It's a smart idea to keep a cache of the grammar, but very strange that it being disabled has gone unnoticed for so long.

I will test the performance with and without the cache to see if there's any reasonable timing differences, then post the results here.

**Comment by bitwizeshift** [comment]
Sorry I didn't get back to this sooner, I had a lot of work over the week and didn't get much chance to work on this until today.

I made the proposed change with the boolean flag and ran performance evaluations between the changed one and the original. Originally both results were nearly identical, and so I decided to look into the code to figure out what was happening.

It turns out that the current code never even creates a `rules.grammar` file anywhere, and so even by changing the flags it still never hit the branch for the cache. The original code that created the file was thankfully still available in a block comment in the file, and so I uncommented it and ran it -- which worked.

After that I ran some performance evaluation comparisons between the original and the changed one. For all tests I did multiple runs, and took the elapsed time and calculated the average time it took to run. 

The results of the tests are below, along with the script I used to run the tests.

## Results

### master.ump

I compiled `master.ump` 10 times with the original version, and then with the changed one. 

#### Without Caching

```
matthew[ ~/workspace/multifaceted/umple ] (master)$ umple_test.sh 10 cruise.umple/src/Master.ump
Executed 10 times
Time elapsed: 147.695043352 s
Time average: 14.76950433520000000000 s
```

#### With Caching

```
matthew[ ~/workspace/multifaceted/umple ] (refactor)$ umple_test.sh 10 cruise.umple/src/Master.ump
Executed 10 times
Time elapsed: 152.511227350 s
Time average: 15.25112273500000000000 s
```

### Small .ump project

I compiled the [coordination state machine example](http://cruise.eecs.uottawa.ca/umple/CoordinationStateMachine.html) 100 times with the original and with the changed one:

#### Without Caching

```
matthew[ ~/workspace/umple/crisis_example ]$ umple_test.sh 100 crisis.ump
Executed 100 times
Time elapsed: 82.024383248 s
Time average: .82024383248000000000 s
```

#### With Caching

```
matthew[ ~/workspace/umple/crisis_example ]$ umple_test.sh 100 crisis.ump
Executed 100 times
Time elapsed: 85.536402408 s
Time average: .85536402408000000000 s
```

## Discussion

On all tests, the cached version ran 3 to 4% longer than the non-cached version. These results came as a surprise to me, as it appears the caching actually causes a performance impact.

At first I was worried it was re-creating the cache each time it was running it, but a few successive runs of testing the branches proved that wasn't the case. I'm not entirely sure what is causing the penalty as I don't have detailed knowledge of the parser.

Given all this, what would be the best course of action for the cache? Caching sounds like a smart idea, but in practice is proving to be more detrimental than useful -- at least in the current state. It's still possible that it may prove to be useful in the future, but would require some performance tweaking/work.

**EDIT**
I'm pretty confident that the cache system can be improved, but it would require a significant change to the current cache method. Right now I think the performance impact is coming from a lot of string comparisons and splitting. For example, the `evaluate(...)` command is called on many lines in the file, which automatically split the line on the delimiters '[:]' and does many string comparisons. Methods like that, when called in a tight loop (as it is in the cache) can cause performance penalties. Given that the file is 4742 lines long, I suspect this is where the penalty comes from. 

If instead the cache were converted to a binary format that stores numeric identifiers instead of strings where possible, a byte (or word) of either 1 or 0 instead of the strings `"true"` and `"false"`, and didn't do string comparisons or call methods like "split" or "indexOf" repeatedly, it should be able to perform much better. 

If each line treated data positionally (e.g. expects the boolean for `BalancedRule` to be at offset +4 of each line), then it could be easily extracted without needing to constantly find indexes and create substrings. 

The only thing is that the cache itself would not be particularly readable (but mind you, it's a cache, so it doesn't necessarily have to be).

## The Test Script

For reference, the script I used for performance timing is just a simple bash for loop that calls umple `n` times in succession while timing it:

```
#!/bin/bash

# ... checks omitted for brevity

# Start timing
nums="$1"
start_time=$(date +%s.%N)

for((i=0;i<$nums;++i))
do
        umple ${@:2} >> /dev/null
done
end_time=$(date +%s.%N)

# Calculate results

secs=$(bc -l <<< "$end_time - $start_time")
average=$(bc -l <<< "$secs / $nums")

echo "Executed ${nums} times"
echo "Time elapsed: ${secs} s"
echo "Time average: ${average} s"
```

**Comment by TimLethbridge** [comment]
Interesting. I suggest we don't 'delete' it but add a comment referencing this issue, and pointing out that it actually runs slower with caching. Then just leave  it inactive.

**Comment by bitwizeshift** [comment]
So I ran into a little bit of a snag dealing with the parser that I was hoping for some suggestions on.

Some of the classes relating to the `RuleBasedParser` are actually from a completely different namespace because they are also used elsewhere. Classes like the `Token` and `ParseResult`, to name a few, are part of the `cruise.umple.compiler` package -- whereas almost everything else relating to the parser is in the `cruise.umple.parser`.

It doesn't seem as simple as just moving some classes from one namespace to another, since a lot of this is heavily tied to the `UmpleInternalParser` and the classes that implement `Parser` (of which `RuleBasedParser` is not one of).

Given that we are looking to extract the parser into a separate project, in my opinion, it doesn't seem ideal to simply move them from one namespace to the other. Particularly because the `UmpleInternalParser` and other `Parser` subclasses would then be relying on a class from an outside project extensively to build parsers internally.

The only way I can see this working nicely is to perhaps move the `Parser` interface to `cruise.umple.parser` and move all the classes strictly relating to parsing into there as well. From there we can perhaps make `RuleBasedParser` implement the interface as well. 
This way `Parser` would just be a public API that we can make use of from inside Umple. 

I'm open to any suggestions for how to deal with this though. Does anyone have any thoughts?

**Comment by aforward** [comment]
I am OK moving those classes into the separate NS.  Please note that the name UmpleInternalParser was only named that way (instead of just UmpleParser) as we had some efforts a long time back to replace our parser with an external framework. So it's no more "internal" than classes in the project.

The fact that it makes heavy use of Token, for example, is a good thing so long as it accesses it through the public interface.

**Comment by Nava2** [comment]
Interesting finding on "caching" (seems like the wrong term :wink:). You should consider a few things:
1. Replace string concats with [StringBuilder](https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html) (sorry, this is obvious)
2. Instead of using a handmade cache mechanism, checkout [Guava's Caches](https://github.com/google/guava/wiki/CachesExplained) -- _always_ looking at the cache for a value before computing could be a significant speed up, serializing and deserializing the cache from a file is questionable

I saw you commented about caching on your UCOSP log, figured I'd add a comment here. :+1:

**Comment by vahdat-ab** [comment]
Please consider that `UmpleInternalParser` is not just parsing Umple files. All analysis activities are done in this files.
if there is a need to use some classes from Parser it should be done through interfaces (as you also indicated). I know it's gonna be challenging because there is a heavy use of them inside `UmpleInternalParser`.

**Comment by bitwizeshift** [comment]
So I've gotten myself a little stuck trying to clean up references to `UmpleFile` in the parser, and I'm hoping someone may have a suggestion on how to fix this.

Right now, `UmpleFile` is passed to `RuleBasedParser` and then to all related classes (`GrammarAnalyzer`,`ParserDataPackage`,`RuleBasedParserThread`,etc). 

Mostly it is used for just the filename or path, but in the `GrammarAnalyzer` it does something a little different. It calls a method from `ParserDataPackage` called `AddExtraFiles`, which appends the `UmpleFiles.getLinkedFiles()` string to the raw parser input. (`geLinkedFiles()` just returns a string of "`use <umple file name>.ump; \n [use ...]`")

Simply put, it directly modifies the raw input _before_ parsing it by manually appending the umple-specific `use` statements for each linked file so that they get properly linked together. This, of course, is not particularly generic as far as parsing goes and thus would not be applicable outside of Umple -- hence the need to change this.

The problem is, I'm not sure how. This seems to be done so that the parse tree produced will properly recognize linked files to parse later -- and thus the way it is currently written. What I'd _like_ to do is make it so that the `RuleBasedParser`, or perhaps the `GrammarAnalyzer` can simply be passed an array of string filenames (or alternatively file objects) that it then links together in the parse step -- but I'm having a lot of difficulty finding where this can be done with the current state of the parser, without doing an entire re-write.

I've tried a little grepping through the source, but I haven't turned up much useful results.

Does anyone happen to have any information or ideas that may be able to weigh-in on this one?

**Comment by vahdat-ab** [comment]
This looks like a really tricky case.
we cannot give the list  of files that are needed to be parsed and analysed to the parser because we use the parser to get that list. This is a cascade process. We don't parse Umple files based on Folder/Project.

What currently comes to my mind is keeping that feature as a part of Umple parser (as a selling point). We can provide this feature along with the way that allows people add manually their files to the parsing list. This list will be parsed incrementally and will make one model. In other words, Umple parser provides a feature which allows making that list automatically.
The keyword `use` must be a part of parser configuration process that can be changed by users. The reason is that what if people want to use the keyword `use` for sth else. There should also be a mechanism to disable it if people don't want to use it.

We need more thoughts because this just came to my mind. Let's see what others say.

**Comment by bitwizeshift** [comment]
I forgot to mention that the reason I was thinking to pass an array of files is that Umple currently makes use of the `getLinkedFiles()` method in the command-line for if the user wants to compile more than one file (e.g. `java -jar umple.jar foo.ump bar.ump` would link `foo.ump` and `bar.ump` in the parser). But you make a good point that it is a cascading job.

I'm not so sure about keeping it as a core/configurable selling point though -- at least not in it's current state. In my opinion, to make it as generic as possible for the end-user, it should be up to them to decide whether or not they want a file-link feature. It's entirely reasonable to want a parser to parse only single files at a time.

I've been looking deeper into this since first posting that question, and I think I found where it parses further files; it looks like the `GrammarAnalyzer` looks like the identifier "useStatement", which is hard-coded from the grammar. Any time it finds that token it runs a parser action that seems to parse that new file and append those tokens in place of the "useStatement" to produce a parse-tree. 

I've also found that `GrammarAnalyzer`, `RuleBasedParser`, and `RuleBasedParserThread` are all very tightly coupled with each other (in-part due to the fact that `RuleBasedParser` acts almost like a singleton without actually being a singleton, thanks to it using static variables). This makes modifications to be quite tedious without breaking anything since they are all modifying the state of the same object (this has resulted in quite a few rebuilds of Umple to fix mistakes!).

Another issue I'm running into is that `GrammarAnalyzer` makes extensive use of classes from `cruise.umple.analysis`, which is specific to the Umple project.

And so, from this, I'm starting to think that my best course of action for handling this linkage problem and combat the coupling may just be to use an extra level of indirection. Basically just extract out the generic/important features from `GrammarAnalyzer` into an abstract superclass, leaving abstract methods as hooks for implementation to decide the capabilities for. From this, we can have our `UmpleGrammarAnalyzer` that adds the specific syntax support that we know and love.

Any thoughts?

**Comment by TimLethbridge** [comment]
The issue of allowing someone to compile several files at once on the command line is something that @vahdat-ab did as his first work item when he arrived, if I remember. We had quite a few requests for this. It is normal in a compiler to be able to compile several files together at once.

I don't have concrete suggestions for solving this, other than doing whatever refactoring is needed.

**Comment by bitwizeshift** [comment]
It's definitely normal for such functionality in a compiler, and I'm not suggesting to remove it or anything. I was more commenting on specific notation of `use <filename>.ump`, which is specific to Umple and wouldn't be particularly portable.

Even with a configuration, parsers for different languages may handle file imports in vastly different ways depending on language semantics (Take C/C++ for example, with triangle brackets searching for files in the include path vs quotes which are relative to the file). Or alternatively a parser may be used in a program that isn't a compiler, or doesn't need a cascading import semantic.

The biggest hurdle I have to deal with right now is the way the `GrammarAnalyzer` is implemented. Ideally the parser should be able to return a parse tree that is then analyzed by the analyzer. Currently it constructs a parser, which constructs an analyzer, which constructs a parser, and then constructs parser threads which construct more parsers. The result of the analysis is actually what is used for the ParseResult of the parser's `parse(...)` operation, which complicates it further since the analyzer is essential to returning a result.

I'm actually going to look into whether or not it's possible (in its current state) to sever ties with the `GrammarAnalyzer`, and delay the analysis until after parsing -- but I don't think it would be possible without almost entirely rewriting both the parser and the analyzer (hopefully I'm wrong!). Plus, the parser currently depends on the analyzer being constructed because it uses it to determine whether it needs to analyze grammar more than once (which is why I am thinking to use a level of indirection to work with this instead of severing ties).

**Comment by bitwizeshift** [comment]
I was instructed by @vahdat-ab to post this here from my recent Pull Request (#802)

My most recent changes do the following:
- Removed `StringFormatter` references in the `GrammarAnalyzer.ump` files. Most of this was able to be handled with simple string concatenation anyway.
- Removed `UmpleCompilerException` from the parser. This was basically just a simple extension of `RuntimeException` that didn't use any of the extensions anyway.
- Moves the main `Analyzer` class to `cruise.umple.analysis`. This is the base class for all analyzers that will be constructed in `GrammarAnalyzer`.
- Changes all calls from `UmpleFile` to `File`. Linked files are now handled as an array of `File` objects supplied in the `parse(...)` method. `UmpleModel` can now be passed the main `File` and the list of linked `File`s in its construction. For the cases that `UmpleFile`s are still passed, a temporary solution is used in `UmpleModel` that splits `UmpleFile`'s `getLinkedFiles()` and translates it into a list of `File` objects. This was done because a large amount of features or tests in Umple rely on the original constructor, and changing it would result in a large amount of changes. That said, this is a step toward deprecating the use of `UmpleFile`.
- Action tokens are now assignable in `RuleBasedParser`. When you assign an action token (which expects the token name and the `ParserAction` to perform) it will cascade the call to the `GrammarAnalyzer` if one is constructed. If one is not constructed, it will automatically populate the `GrammarAnalyzer` with the actions when it is.
- `ParserDataPackage` now contains information about the `GrammarAnalyzer` being used. This is important for being able to create actions that produce `RuleBasedParserThread`s, such as when you encounter a 'use' statement.
- Construction of analyzers, and linkage of files have been extracted out into the two handler classes, `AnalyzerGeneratorHandler` and `LinkedFileHandler` respectively. 
  - `AnalyzerGeneratorHandler` requires an implementation of `generateFromName(String name)` that generates and returns an `Analyzer` object based on the string name of the token. In Umple this generates analyzers using reflection from the `cruise.umple.analysis.` namespace.
  - `LikedFileHandler` requires an implementation of `onFileLink( String input, File[] linkedFiles )` that handles linkage of files and returns a string modified from input. In Umple, this generates a series of "use" statements prior to parsing so that the parser will add the files in-place.
- Implementations of the handler classes are given in `UmpleInternalParser_CodeParserHandlers.ump`. These are just concrete implementations that will be used in the parser, and were placed here since this is where the `RuleBasedParser` gets instantiated to begin with.

Now, with that said, the next important detail to look into is how to handle the Parser separately without the need for Umple to be carried along with it. Currently, the files necessary for the parser to compile are the following:
- `GrammarParsing.ump` & `GrammarParsing_Code.ump`
- `Parser.ump` & `Parser_Code.ump`
- `ParsingRules.ump` & `ParsingRules_Code.ump`
- `TextParser.ump` & `TextParser_Code.ump` 

these are tested by the following tests:
- `cruise.umple/test/cruise/umple/parser/TextParserTest.java`
- `cruise.umple/test/cruise/umple/parser/PositionTest.java`
- `cruise.umple/test/cruise/umple/parser/ParserTest.java`
- `cruise.umple/test/cruise/umple/parser/RuleInstanceTest.java`
- `cruise.umple/test/cruise/umple/parser/TokenTest.java`
- `cruise.umple/test/cruise/umple/parser/RulePartTest.java`
- `cruise.umple/test/cruise/umple/parser/CoupleTest.java`

This can all be compiled with a simple `master.ump` file such as the following:

```
generate Java "../src-gen-umple";

strictness allow 1006;
strictness allow 1007;
strictness allow 1008;
strictness allow 46;
strictness allow 36;

use Parser.ump;
use ParsingRules.ump;
use TextParser.ump;
use GrammarParsing.ump;
```

So the big question is where should this be handled? This can be handled in a variety of ways, such as being an independent git project brought in as a dependency, a sub-project (or just a directory) in the current Umple repo that's brought in during the build step, etc.

Does anyone have any thoughts or suggestions as per the best way to handle this?

**Comment by TimLethbridge** [comment]
My suggestion, is to use a top-level directory UmpleParser  with its own src, build and src-gen-umple directories in the Umple repo. Its own build could generate a standalone parser. It would have a Readme.md also to describe how to use it (and where to put grammar files). The main Umple parser would run the compile of the parser using the parser's build script, and then copy in the generated java files, into cruise.umple/src-gen-umple as is done for the UmpleToJava or UmpleToPhP.

This approach would avoid getting into dependency hell that we have found so great to avoid. We could later make the decision to move it into a separate repo.

**Comment by bitwizeshift** [comment]
Sounds like a good first-step. Should the tests all remain where they are in the `cruise.umple/test/`, or should they migrate to the new directory as well?

**Comment by TimLethbridge** [comment]
I think best to move the tests too.

**Comment by bitwizeshift** [comment]
So I've done work with Ant in the past, but never with the configuration like we currently have in Umple -- which is making the process of writing a working Ant script confusing. The other projects, as far as i can tell, don't have their own unique `build` directory either, so I don't really have much to base this off of short of the full build.

The current build for Umple seems to grab information from `_template.xml` which defines important context information for the build, such as where the previous Umple jar can be located. I would assume I would also want this information as well, so that if ever the location of the jar changes the script will update with it. But here's where I'm confused:

The main `build.xml` file defines the root drive as `..`, which means the main build area is in the root of Umple instead of the `build` directory. Since `_template.xml` refers a lot to `${basedir}`, wouldn't that mean my script (being in `UmpleParser/build/build.xml`) would have to define the base dir as `../..`?

The other thing that I'm unsure of is the fact that the `_template.xml` defines many of the template build targets that wouldn't be necessary for the build of the parser.

Am I perhaps approaching this wrong? Is there another way/a better way of retrieving the current umple jar compiler path for compiling the parser source?

**Comment by TimLethbridge** [comment]
Umple is really the only ant script I am familiar with, and I use the word 'familiar' in the sense that when I need to figure something out I debug it, but I have not studied it in depth. But I can see your conundrum. I don't have any immediate suggestions, nor the time to spend to figure it out for you.

One thing I can say for sure is that at least on Linux and Mac there is a symbolic link called dist/umple.jar that points to the most recent compiler But this isn't created on WIndows and is only to help users of Umple do manual testing.

@aforward knows more about the ant scripting since he created it originally

You are right at the end of your semester; one suggestion might be to ignore what I said above and simply put the build of your work in the build.umple.org as a very simple ant target (much like codegen) that could be invoked in the same manner as codegen. At some later point it could be refactored to make it work independently for other developers to use externally to Umple.

**Comment by bitwizeshift** [comment]
> You are right at the end of your semester; one suggestion might be to ignore what I said above and simply put the build of your work in the build.umple.org as a very simple ant target (much like codegen) that could be invoked in the same manner as codegen. At some later point it could be refactored to make it work independently for other developers to use externally to Umple.

I could always start by doing it this way, but port it after looking deeper into the issue. Right now, even if I was able to make the build work properly it would drag in extra unnecessary build-targets that could cause problems. The only other way I could think of is to repeat data from the other scripts that set up the various variables, but that could cause problems if anything changes. Alternatively, the `_template.xml` could be broken into a script that strictly handles definitions, and then the build script could import just those definitions.

I'll start by doing the simple build as a separate target so that it could be used as the basis for a change in the future, but it feels unfinished and I would like to change at some point later.

**Comment by TimLethbridge** [comment]
I am closing this issue. The core parts of it were all done (pulling out parser). Other refactoring and adding documentation would be useful too, but better as a separate issue.
