### ISSUE TITLE
Make `master` branch protected

### ISSUE THREAD

**Issue by Nava2** [umple/umple#718]
I would like to propose to make the `master` branch protected in this repository. 

The justification for this is to avoid accidental commits to the repository. Github's [guide](https://github.com/blog/2051-protected-branches-and-required-status-checks) explains the process. 

I think it should be set to only allowing project administrators the access to merge pull requests. This stops accidental pushes. Those who would be admins would be under [Umple Team Leads](https://github.com/orgs/umple/teams/umple-team-leads). Any UCOSP mentors would end up under there to give @TimLethbridge some sanity when dealing with lots of PRs. :smile:

**Comment by vahdat-ab** [comment]
I wonder if in this cases developers will be able to commit directly to the repository? 
If not, we may want to consider the psychological effect of this decision on other team members. 
Generally, students get admin permission from Tim when they are good enough to commit their own stuff. Having this permission makes students thinking how they are valuable to the project (more confidence as well) and also reduces the load out of Tim's shoulders. I agree we need this restriction, but we should think more.
We may first want to talk about the benefits of pull request to all members and promote this culture and then move to this state.

**Comment by Nava2** [comment]
Oh, you can create pull requests and push to branches that are **not** `master`. You just can't click "merge pull request."

**Comment by vahdat-ab** [comment]
cruise.umple is master and people with commit permission work with that directly. 
The question is this: Do Tim's students, who have committed directly to the master (cruise.umple) so far, need waiting for their pull request being merged by people in the admin group?

**Comment by Nava2** [comment]
What about just protecting from merging when CI fails as _only_ project admin? That way, grad students for example can create a PR and then merge the PR iff all CI passes? This would give more protection while removing the "admin" nature of it. 

The "git-way" of development should have no one developing on `master` at all, only merging into it. So while I acknowledge that some may work on `cruise.umple` in `master` directly, that is a bad idea and they should be working on branches. Even if they know their changes are satisfactory, they should be waiting to see if CI passes before committed to `master`.

**Comment by vahdat-ab** [comment]
I agree on this.

**Comment by TimLethbridge** [comment]
But we can't do this while travis is incorrectly failing ... we need to somehow figure out how to solve or work around that problem.

**Comment by Nava2** [comment]
Admins can still override the CI checks. It's under the assumption, you guys know better.

**Comment by TimLethbridge** [comment]
I have made the master branch protected, so PRs are required.

I have not put CI checks into place because we have found Travis to be too flaky (the OSX build seems to break intermittently and sometimes is offline for many hours).
