### ISSUE TITLE
Umple, Travis, and the Memory problem in general

### ISSUE THREAD

**Issue by Nava2** [umple/umple#720]
Currently, when we build on Travis-CI's Linux platform, it fails. See [#257](https://travis-ci.org/umple/umple/builds/107889342), [#255](https://travis-ci.org/umple/umple/builds/107675157), etc.. 

The reason why it fails (talked about [here](https://github.com/travis-ci/travis-ci/issues/5582)) is due to the memory Umple consumes is too large. Memory problems will arise on **any** memory constrained machine, not just Travis. The solution of "add more heap space" when we already consume 1.2+GB of RAM is not reasonable for a compilation process.

I'm not an expert by any means on memory profiling, so I would like any and all input about possible improvement points and reductions: 
- [ ] Investigate changing the GC cycle to run more often (this will likely slow down compilation)
- [ ] Use string caching instead of the "load at class time" scenario we currently have
  - Load from files stored as Java resources (packaged into the jar) instead of static strings
  - Use [Guava's Cache](https://code.google.com/p/guava-libraries/wiki/CachesExplained) or hand-roll one for our needs when loading/storing strings (with Ivy we can pull this in simply)
- [ ] Improve the memory footprint of Umple's template language 
  - This is a big consideration given #708 going forward
  - Also an opportunity!
- [ ] Cache models during compilation: 
  - Once a model is used, if we can drop any references from memory, it would be beneficial
    - I think the model verification stage needs all the memory at once, but we might be able to hack some parts together 
  - Cause "model rendering" to be incremental
  - Use a flat-file cache to write object meta-model data to then pull from it as required and recreate the objects when generating code and are needed keeping "weak" objects in memory that hold the graph of dependencies

These are my initial thoughts, I would really like input and help in implementing this. I don't think I have time to tackle this problem myself, but I'll make some time going forward to help out.

**Comment by Nava2** [comment]
@TimLethbridge I was unsure what to tag this, but I did my best.

@aforward any chance you've had some insight into VM profiling any have any ideas?

I have previously run the Umple compiler through a Java Profiler (no idea which one) and I remember it came back that we spend a ridiculous amount of memory holding onto template strings in `static` memory. This was obvious when I looked at the templates that JET creates. This memory can **never** be freed and that's a problem.

**Comment by aforward** [comment]
No specific insight from me, sorry.

## 

aforward

**Comment by TimLethbridge** [comment]
I will gather sone insights into how and if we can ... don't assign someone just yet.

Clearly Travis itself has lowered its allowable memory threshold or has started running on lower power machines since the exact same compile that used to run now does't. It would be good to see if Travis has any settings to increase the allowable memory before we do any compiler optimizations.

**Comment by TimLethbridge** [comment]
on OSX I did some experiments using a utility called memusg, and also forcing limits on process memory usage.

Wnen memory usage is unconstrained, on my OSX machine, compiling Master.ump uses 1.5GB of peak memory.
It takes about 15s

But if I force a memory limit of 100MB using the ulimit command, compilation still takes 15s, and compilation still is successful! Garbage collection clearly kicks in to constrain memory, but the amount of extra time used is marginal.

If I drop the memory limit to 85MB then CPU time starts to increase noticably ... up to 16.5s

If I drop the memory limit to 80MB then CPU time almost doubles ... up to 28s

If I drop the memory limit down to 75MB, then I get an out of memory error (garbage collection clearly can't handle things at this limit).

It seems impossible that Travis is not allowing 80MB processes, so either:
a) Umple is using the 1.5GB without garbage collection and Travis is just killing when it sees this (solution: force more garbage collection, which seemingly won't cause too much trouble) or
b) It is not memory that Travis is limiting; perhaps it is files open or CPU time

I will do further experiments

**Comment by Nava2** [comment]
Is this compiling the project itself or just running general compilation? Could it be a scale issue? 

And yes, 80MB is incredibly low.. I'd say a safe reasonable goal is around 800MB max. I have no justification for that number except that most machines have > 2GB of RAM.

**Comment by TimLethbridge** [comment]
My comments above were for compiling the project itself (compiling Master.ump). 

I am working on a branch where I am one-by-one forcing JVM jobs that crash to stay within a 500MB memory limit. This seems to work. The full compile of Umple is now working without being killed. However the documenter packager then had the same problem, so I slapped a limit on this. Next the template.tests were failing ... again I had to slap a JVM memory limit option on that, and all works ok.

And ... successful Travis build of the branch.

If the OSX build completes successfully I will create a pull request.

**Comment by Nava2** [comment]
That's excellent! 

May I suggest we keep this as a standing consideration for the template switch, though? While explicitly limiting memory works, most will not and it would have a usability approach to those running it locally.

**Comment by TimLethbridge** [comment]
Not quite sure what you mean by 'standing consideration for the template switch', I have just built the limitation into the build scripts; it will be invisible to all. It just causes 1% increase in garbage collection overhead, which is not noticeable.

Perhaps we could add a -DlimitJvmMemory where true would be the default and a user could use false if they want to eke out that last bit of speed. Or maybe you were thinking making the default false, and putting the true option on the travis task. I leave this as a later step.

**Comment by Nava2** [comment]
> Not quite sure what you mean by 'standing consideration for the template switch', I have just built the limitation into the build scripts; it will be invisible to all. It just causes 1% increase in garbage collection overhead, which is not noticeable.

I just meant that keeping reducing memory foot print as an important aspect to consider going forward. Especially since there is a large tendency to grow over time. 

> Perhaps we could add a -DlimitJvmMemory where true would be the default and a user could use false if they want to eke out that last bit of speed. Or maybe you were thinking making the default false, and putting the true option on the travis task. I leave this as a later step.

That's a really good idea.
