### ISSUE TITLE
Again build fails on Windows

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#730]
Today, I faced with a failed build in my Windows 10 and l thought it's because of Windows and started to reset my repository, cloned a new repository, etc. I even checked out a previous commit and it didn't work. 
After hours, I started to check out the previous commits and did a full build for each one.
The merge "Warning 1009 no longer appears when interface lists subclass method" passed completely the tests, but the commit "Add appveyor.yml and auto-myenv" fails.

I don't know what have been changed, but the source is related to appveyor.
I have been developing since I corrected the full build on Windows and I think we should fix this issue because now we know other people also started working on Windows.

Failed tests

```
    [junit] TEST cruise.umple.builder.BuilderTest FAILED
    [junit] Tests FAILED
```

**Comment by vahdat-ab** [comment]
@TimLethbridge @Nava2

**Comment by Nava2** [comment]
What shell are you using to run the test?

**Comment by Nava2** [comment]
I ask because that test hasn't changed ([Blame](https://github.com/umple/umple/blame/631a37df74fce94a9c4866e0c5664ce2ec540320/cruise.umple/test/cruise/umple/builder/BuilderTest.java)).

**Comment by vahdat-ab** [comment]
I use windows normal shell. I always use this. I think the reason might be indirect to this test cases.

**Comment by Nava2** [comment]
I think it is due to running the test cases through cmd. Would you mind
trying on power shell and seeing if it works?

Kevin

**Comment by vahdat-ab** [comment]
I compiled it in power shell and it failed again.

**Comment by Nava2** [comment]
I am extremily confused why it would work on Appveyor then. Do you have the `ant` shim installed (i.e. "symlink" between `ant` and `ant.bat`)?

The obvious solution is to just revert this [line](https://github.com/umple/umple/commit/ef073a2259c48f36c7fe7a5d873ad3438797b3dc#diff-dcd40f9f6ac21e088871e36ccd1eeaa9L246). I don't have time to do it today, though. So, @vahdat-ab do you think you could do it?

**Comment by vahdat-ab** [comment]
@Nava2
I don't have "symlink" and related stuff. I have never needed those. 
 It's better it's done by you in order not to lose the track. Thanks.

**Comment by Nava2** [comment]
The more I look at this code, the more I dislike it. I think I've fixed this class ~5 times over time, and I've never seen it used.

What is the use case for the "Builder" class? It calls Ant from Java, but I don't see why this is a useful/necessary feature. I am wondering what the context of it is. Could this be feature creep from the past?

**Comment by Nava2** [comment]
@aforward It looks like you wrote these classes for Umple Run, is this still used or is that deprecated? It was written 5 years ago.

**Comment by vahdat-ab** [comment]
@Nava2 I wonder if you have found a solution to get rid of windows errors? Is that possible to bring the code to the point it was working without affecting other parts?

**Comment by Nava2** [comment]
I was looking for input on @aforward.

**Comment by TimLethbridge** [comment]
I just noticed the following wiki page
https://github.com/umple/umple/wiki/BuilderTestFailingOnWindows 
that may shed some light on this @vahdat-ab can you see if this helps?

**Comment by Nava2** [comment]
The builder tests fail because of path issues. 

I wrote some code to traverse the `PATH` environment variable and find any executable matching `ant(?:\.bat)?` but it fails arbitrarily. 

I agree with the email thread you started, @TimLethbridge. I don't think the "builder" component is useful anymore. It's so platform dependent and we keep "fixing" it but to no benefit (from my view). I do want @aforward to comment on what the original and current important is for this component (no rush, @aforward).

**Comment by aforward** [comment]
`Builder` is used to build up a Jar, internally it uses `ant` to do that.  

```
      System.out.print("Building model... ");
      Builder b = new Builder();
      URL jarfile = b.compile(".",umpleFile.getSimpleFileName() + ".jar",umpleFile.getSimpleFileName(),"1.6");
```

Is the above code dead? Does the code work as expected on a Windows box?  The above is part of our `umple.jar`

If the code is not being used anymore, then I would remove both the tests and the core code.  If the code is still being used, then I would keep the cobbled test and try to get working on a Windows machine

**Comment by vahdat-ab** [comment]
I could fix the issue by adding "ant.bat" to the command when it's on windows. Looks like `ProcessorBuild` in Java is dealing with ".exe" files and if it's ".bat" we need to explicitly specify it.

**Comment by TimLethbridge** [comment]
OK. Can you try changing it to ant.bat when on Windows?

**Comment by vahdat-ab** [comment]
yes, I have already done it through my last merge. 
Now, I don't see any failures in my Windows machine. However, Appveyor fails. Maybe we need to run it twice.
