### ISSUE TITLE
Umple template vs JET template differences with code blocks

### ISSUE THREAD

**Issue by Diusrex** [umple/umple#732]
This issue revolves around the differences between how JET handles code blocks (`<% ... %>` and how Umple handles code blocks (`<<# ... #>>`).

From my investigation, I have found that there are two major differences. They can both be worked around, but I feel that they make the templates less intuitive to write and read.
1. If there is a line that starts with some whitespace, then is a code block, JET will not include the newline from the previous line, and will not include that whitespace. However, Umple will. 

This is best illustrated by how, in the following example, JET outputs

```
    Line before
    Line after
```

while Umple outputs

```
    Line before
        Line after
```

This is in the first group
1. If a line ends with the closing syntax for a code block, JET will output a newline, while Umple will not.

This is best illustrated by how, in the following example, JET outputs

```
    Line before

    Text inside    Line after
```

while Umple outputs

```
    Line before
    Text inside
    Line after
```

This is in the second group

where the Text inside was inserted using `stringBuffer.append("\n     Text inside")`.

NOTE: For all of the JET templates we have, whenever a code block (\inserts text into a template, it is done with (approximately) `stringBuffer.append("\n     <code>")`. As in, it always inserts a new line before the code, and gives the indentation for the code.

For a complete example of the major cases for text around the code blocks I used the following template example:

```
example <<!
    Text immediately before
    <<# // Without text on same line #>>
    Text immediately after

    Text immediately before
    <<# realSb.append("\n    Text inside"); #>>
    Text immediately after

    Text immediately before
    <<# // With text on same line, after #>>after code
    Text immediately after

    Text immediately before
    before code<<# // With text on same line, before #>>
    Text immediately after
!>>
```

creates the following text when compiled and run with Umple:

```
    Line before
        Line after

    Line before

    Text inside    Line after

    Line before

    Text insideText after code
    Line after

    Line before
    Text before code
    Text inside    Line after
```

but creates the following text when compiled and run with JET:

```
    Line before
    Line after

    Line before
    Text inside
    Line after

    Line before
    Text insideText after code
    Line after

    Line before
    Text before code
    Text inside
    Line after
```

This is possible to fix, but the fix isn't very pretty, since would need to do a change

```
     textBefore...
    <% codeBlock %>
    textAfter...
```

to

```
    textBefore...<<#
    codeBlock #>>

    textAfter
```

to get it to create the same text. We cannot rely on the template inserting text, (where could just change the newline and indentation to the end) since they are usually conditionals.

The Umple class that I used to create this example is available at http://pastebin.com/2mJHnbs8

(I can't seem to the list numbers to work unfortunately, presumably because there is text between them)

**Comment by TimLethbridge** [comment]
Yes, this is an important issue. We need a response from @ahmedvc about this

**Comment by TimLethbridge** [comment]
@ahmedvc Just merged pull request #738  that may solve this issued also #736 and #735  . Would @Diusrex comment and if the problem is solved, then close this issue please.

**Comment by Diusrex** [comment]
The differences that I had outlined between Umple and JET in this issue were fixed. However, I won't fix this issue yet because I have found some other differences after testing with replacing the full template.

Since I haven't yet had time to look into them, I cannot say whether we should change our templates, or if the converter should just handle them. Will determine this as soon as I can.

**Comment by Diusrex** [comment]
Of the existing differences between our code block and JET's, none should be implemented in ours due to being an unintuitive special case, like not adding a newline after `some text` in the following example:

```
   some text

   <% code block.....
```

unless it is:

```
   }

   <%
```

where a newline will be added after the }.

Therefore, my converter is able to handle all of the differences, and so this issues was completed from pull request #738.
