### ISSUE TITLE
Extend Umple syntax and code generation with tracing

### ISSUE THREAD

**Issue by Nava2** [umple/umple#74]
Originally reported on Google Code with ID 172
Owned by @hjamaan

---

Creating a Umple parser and code-generation extensions for the Model-Oriented Tracing
Language (MOTL).

This allows injection of tracing directives to trace attributes, associations, state
transitions, state entry and exit and other elements.

Directives can also be grouped into trace cases.

Triggering of a directive can cause generation of code that at run time will trace
output to various tracing technologies (gcc, LTTNG, plus a basic stderr and string
tracer). The tracing technology will be pluggable. 

Triggering of a directive can also cause activation and deactivation of one or more
other directives.

Traces can be triggered on all objects of a class, or all objects in the current thread,
as well as on the current object.

Tracing can also be made to operate for a certain amount of time, a certain number
of iterations etc.

---

Reported by @umple on 2011-06-25 01:50:05

**Comment by Nava2** [comment]
Reported by @umple on 2012-06-14 15:03:48
- **Labels added**: Diffic-VHard

**Comment by TimLethbridge** [comment]
I am closing this as it was the subject of Hamoud Aljamaan's thesis which is not accepted. Additional issues on tracing can be opened separately
