### ISSUE TITLE
Warning 1012 issued incorrectly in the context of an after statement injecting into a trait-specified method

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#755]
The following example is showing the warning 1012 while it shouldn't show it.

```
class A
{
    isA T;
    after testFunction{
        //injected code
    }
}
trait T{
    void testFunction(){
        //code  
    }
}
```

The solution is simple.
Please do checking after this method `private void applyTraits()` inside `UmpleInternalParser.ump`

**Comment by TimLethbridge** [comment]
In UmpleInternalParser_Code:329 we have the following sequence. The suggestion is to move the postTokenClassAnalysis(); until after applyTraits();. There may be other consequences, however. So this would need to be analyzed. It may be that we have simply to move  checkCodeInjections(); in postTokenClassAnalysis after applyTraits().

```
    if (getParseResult().getWasSuccess())
    {
      postTokenClassAnalysis();
    }
    
    if (getParseResult().getWasSuccess())
    {
      postTokenTraceAnalysis();
    }

    if (getParseResult().getWasSuccess())
    {
      postTokenTraitAnalysis();
    }

    if (getParseResult().getWasSuccess())
    {
      applyTraits();
    }    
    
```
