### ISSUE TITLE
Activate testing of UmpleOnline and User Manual examples during the build by compiling C++/Php

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#758]
Work was being done by @CraigBryan to ensure that all the examples in the user manual and umpleonline are compiled in the build.

This was never activated. We really need to finish that so we can keep improving the robustness

See also #363

**Comment by TimLethbridge** [comment]
I think we only need to activate this on travis, and make it optional when myenv=local

**Comment by CraigBryan** [comment]
@TimLethbridge What do you mean by 'optional' when `myenv=local`? Does that mean run when `myenv=local` or does it mean run when `myenv=local` and another variable is set?

**Comment by CraigBryan** [comment]
The other work that needs to be done is to add any missing flags to the manual code and example code so that the build actually passes with this enabled.

**Comment by jblang94** [comment]
Hello @CraigBryan  , I am wondering if you are still working on this issue?

**Comment by TimLethbridge** [comment]
I wouldn't worry ... It has been over a year since Craig finished doing his work; I am sure he would be happy to have someone pick this up, but he might be willing to help if there are questions.

**Comment by vahdat-ab** [comment]
I need to work on the example `GeometricSystem.ump`. Once, I'm done I'll close this.

**Comment by jblang94** [comment]
@vahdat-ab safe to close this issue?

**Comment by TimLethbridge** [comment]
This was never actually activated. I am going to activate today.

**Comment by TimLethbridge** [comment]
By the way, the command to run on the command line is

```
ant -Dmyenv=local -f build/build.exampletests.xml allUserManualAndExampleTests
```

**Comment by TimLethbridge** [comment]
This issue is being partially dealt with in PR #1228

However that PR only activates it for Java. Note that activation is done in build/build.exampletests.xml line 46-49

Most Cpp files do not compile. The following PhP do not compile, and should be either fixed or else the @@@ skipphpcompile should be added to them, and then php should be activated.

```
 AssociationClassDefinition4.ump
 AssociationClassDefinition5.ump
 CarTransmission.ump
 CollisionAvoidance.ump
 CourseSectionNested.ump
 Elevator_State_Machine.ump
 NestedStateMachines1.ump
 ParliamentBill.ump
 RegionFinal_ConcurrentExample.ump
 RegionFinal_NonConcurrentExample.ump
 Runway.ump
 SpecificFlight.ump
 TracingAssociations1.ump
 TracingAssociations2.ump
 TracingAssociations3.ump
 TracingAttributes2.ump
 TracingAttributeswithConditions2.ump
 TracingAttributeswithOccurrences2.ump
 TracingStateMachines1.ump
 TracingStateMachines2.ump
 TracingStateMachines3.ump
 traits_example_018.ump
 traits_example_024.ump
 W055DuplicateEventsWithinSubstates1.ump
 W142TypeIsAccessSpecifierExplicit.ump
 W228InitialStates.ump
```

**Comment by ZainabAlShowely** [comment]
PHP code generation issues (that get triggered by the examples that do not compile) are being worked on in branch [Issue_758](https://github.com/umple/umple/tree/Issue_758). Tracing PHP code generation is not implemented, so these examples will be skipped until then.

**Comment by TimLethbridge** [comment]
C++ remains to be done.

**Comment by TimLethbridge** [comment]
PHP was done long ago. We need to do this for C++. We need also to tag the C++ examples that don't generate good code and raise issues to fix for each

**Comment by TimLethbridge** [comment]
This was completed earlier in 2024
