### ISSUE TITLE
Configure Cruise Control Email announcement

### ISSUE THREAD

**Issue by Nava2** [umple/umple#76]
Originally reported on Google Code with ID 174
Owned by @aforward

---

Announce failed builds to umpleupdates@googlegroups.com

---

Reported by @umple on 2011-06-25 01:56:22

**Comment by Nava2** [comment]
Reported by @umple on 2011-06-30 20:12:24
- **Owner changed**: @aforward

**Comment by Nava2** [comment]
Lowering priority since we have web monitoring tools that can tell us the same information
that have been working well. If we do implement this, it should likely go to umple-dev

---

Reported by @umple on 2012-06-14 21:50:48
- **Labels added**: Priority-Low
- **Labels removed**: Priority-High, keyPortfolio

**Comment by Nava2** [comment]
Reported by @umple on 2012-06-15 15:35:07
- **Labels added**: Diffic-Easy

**Comment by TimLethbridge** [comment]
Closing, since travis will send an email
