### ISSUE TITLE
Umple reference comment is not working correctly

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#768]
When we define a method inside a Umple file, in the generated code we have a reference to Umple file. Looks like, someone has broken it.
Check out the following example

//file: test.ump

```
use test1.ump;
class A{
    void test(){
        //test
    }
}
```

//file: test1.ump

```
use test2.ump;
class A{
    void test1(){
        //test1
    }
}
```

//file: test2.ump

```
class A{
    void test2(){
        //test 2
    }
}
```

**Generated code:**

```
  // line 4 "test2.ump"
  public void test2(){
    //test 2
  }

  // line 4 "test2.ump"
  public void test1(){
    //test1
  }

  // line 49 "test2.ump"
  public void test(){
    //test
  }
```

**Comment by vahdat-ab** [comment]
@bitwizeshift This may be related to your refactoring

**Comment by bitwizeshift** [comment]
Hmm, I'll look into this when I get the chance.

I think this may be related to the `getRelativePath` method.

**Comment by bitwizeshift** [comment]
I just went back to a commit made prior to the pull-request regarding the `getRelativePath` method, and it does appear that this is to blame for the issue. I'm surprised there aren't any tests that would have caught this problem initially.

I'll have to look into this further.

**Comment by vahdat-ab** [comment]
@bitwizeshift  Thanks.

**Comment by bitwizeshift** [comment]
I've found the problem; looks like I forgot to set the source filename in a couple locations in the jet files when I was refactoring the `getRelativePath`.
I'll make the changes and have a PR in a few hours.
