### ISSUE TITLE
Add cruisecontrol (cc) to init.d scripts for auto restart on reboot 

### ISSUE THREAD

**Issue by Nava2** [umple/umple#77]
Originally reported on Google Code with ID 175
Owned by @aforward

---

Add cruisecontrol (cc) to init.d scripts for auto restart on reboot, so if the server
restarts then cruisecontrol will be restarted too.

---

Reported by @umple on 2011-06-25 01:59:18

**Comment by TimLethbridge** [comment]
Done long ago
