### ISSUE TITLE
duplicate methods with the same name but different return types

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#771]
Umple accepts the following example:

```
class A{
  void test1(){
  }
  Integer test1(){ 
  }
}
```

It is not acceptable in Java and C++ to have two methods with the same name and different return types. I'm not sure about othe languages but Umple should avoid generating a wrong code.

**Comment by TimLethbridge** [comment]
Should return a warning for sure.

**Comment by a3994288** [comment]
If I have duplicated methods that return the SAME types, a warning will be generated.    
`class A{
  void test1(){}   
  void test1(){}
}`  
>A implementation of Method 'test1' in class 'A' is already defined at line 3 of 'model.ump' file. New definition at line 5 of 'model.ump' file is being disconsidered. More information (49)  

This warning has not been developed in user manual yet, so I assume I should document the warning in user manual if I like to use it.

I have two solutions to propose:  
1. Can I just re-use the warning above, generate a warning for duplicated method name (regardless of whether it returns the same type or not)

2. generate separate warning for the situation described in the issue, which means when they return different types, I only generate a warning for those languages that does not support it (like Java)

I personally support 1st propose as I believe use the same method name in the same package is not necessary for any language and can be achieved by other approaches.

Please let me know if I am on the right track, and also I am still not sure where should I fix it in the code. Could someone point out where should I make changes in the code or which document I should read?(I've been reading a lot documentations those days but still don't have a clue)

**Comment by vahdat-ab** [comment]
I would say first document the error code 49. Don't forget to point out this in you PR's comment because Tim needs to review the text.
solution 2 is not the case. We are not targeting a specific language at the modeling language. Therefore, Umple' modeling syntax and semantics are not going to depend on a specific language. 
The above case must be avoided all the time.
I am more in supporting of having a separate error code which describes the error more clearly. The error code 49 says methods are exactly the same,  but the new one might say they have the same name and parameters but different return types which are not acceptable in Umple.

**Comment by vahdat-ab** [comment]
Regarding the place to start, please check`Umple.ump` and `Umple_Code.ump` regarding how a method is structured and compared with others. Then you can check `UmpleInternalParser_Code.ump` for the exact place to find. To me, you just need to modify the comparison algorithm to consider the return type.

**Comment by a3994288** [comment]
#457 return warning 049 when methods have the same return types and names. For this issue, I will modify his code to (in UmpleInternalParser_CodeClass.ump):
`If (have same name and paras) {if(same type) return warning 049 else return warning 071}`
