### ISSUE TITLE
Umple doesn't parse a guard with a string variable and equal operation

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#789]
consider the following example"

```
class CommandControl{
    String cmdString = "";

    CommandControl{
        IDLE{
            execute -> CHECK_AVAILABILITY;
        }
        CHECK_AVAILABILITY{
        //The issue is with =="" and !="". When I remove !="" or =="" it works
        execute [cmdString!=""]-> COMMAND_VALIDITY;
        //  execute [cmdString==""] -> IDLE;

        //  execute [cmdString]-> COMMAND_VALIDITY;
        //  execute [cmdString] -> IDLE;
        }
        COMMAND_VALIDITY{
            [isCommandValid(cmdString)] -> EXECUTION;
        }
        EXECUTION{
        }
    }
}

```

It doesn't compile because of `cmdString!=""`. When the `!=""` is removed it is comp[iled.

**Comment by vahdat-ab** [comment]
@opeyemiAdesina

**Comment by TimLethbridge** [comment]
Yes it should use equals() when the comparison is string or some other non-primitive data.

**Comment by vahdat-ab** [comment]
I think it must be parsed because if we give correct rules, there is no problem. Using `equals()` is just a programming level concept and normally people won't use it at the modeling level. 
if we parse it correctly, the analysis phase can take care of correctness of the variable 9e.g. if it's been defined or it's an Integer or String). I think we should avoid bringing programming concepts to the modeling because they are hard to interpret.

**Comment by TimLethbridge** [comment]
Yes of course parse =. What I meant was _convert_ it to generate .equals() internally in generated code. The user would never see that.

**Comment by tlaport4** [comment]
This issue seems to have already been fixed. The generated code uses .equals to compare Strings.

In this example, the conditions in the generated code look like this:

```
 if (!"".equals(getCmdString()))
```

and

```
 if ("".equals(getCmdString()))
```

Should I just add some tests for this specific situation?

**Comment by vahdat-ab** [comment]
Yes. Just add test cases and then we will close this issue.
