### ISSUE TITLE
wrong code geneartion for state machine guards

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#796]
consider the following example:

```
class A{
    Boolean result;
    status {
        s0{
            go [result==true] -> s1;
        }
        s1{

        }
    }
}
```

Part of the generated code is as follows.

```
      case s0:
        if (getResult().equals(true))   // The problem is here
        {
          setStatus(Status.s1);
          wasEventProcessed = true;
          break;
        }
        break;
```

We cannot have a `equals` for a boolean. What is correct is to just use the name of variable (if it's boolean) or its get method.

**Comment by tlaport4** [comment]
Added logic to remove the comparison to true/false constant values. If it is comparing a boolean with "false" or is comparing with "!=" it will negate the boolean.

**Comment by TimLethbridge** [comment]
PR successfully merged
