### ISSUE TITLE
not having parameters for joint points that are generated automatically

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#804]
consider the following example:

```
class A{
  data;
  setData(String i,String j){
  }
  after setData(String,String) {
    //this is injected code
  }
}
```

because we don't use `custom` keyword, we aim at the auto-generated method`setData`for the attribute data. We dont' care about the parameters. Therefore, it should be removed from the grammar.
This will help people to understand if they want to go with maunal methods, they need to use the keyword `custom`

the preferred one:

```
class A{
  data;
  setData(String i,String j){
  }
  after setData {
    //this is injected code
  }
}
```

**Comment by vahdat-ab** [comment]
@Shikib

**Comment by Shikib** [comment]
Ok to make sure I'm understanding properly before I deal with this issue, what you mean is that we shouldn't allow people to specify parameters unless they're targeting custom methods?

Right now, it's possible to just omit the parameters for injections into generated methods -- but including parameters doesn't really do anything. So I should make it impossible to include parameters for anything except custom code injections?

**Comment by TimLethbridge** [comment]
Remember there can be parameters on generated event methods

**Comment by vahdat-ab** [comment]
- I'm just following what you said. The parameters are not considered when we don't use the keyword `custom`. Therefore, there is no need to have them right? They make sense when we have custom methods. If this is correct, so we should prevent developers from writing it. 
  @TimLethbridge  since we know what we generate we don't need to deal with their parameters (based on what understood from other issues).

**Comment by vahdat-ab** [comment]
There is another issue with injected code for auto-generated methods:
consider the following code:

```
class A{
    0..1 -> * B;
     after addB{
    //this is injected code 1
    }
    after removeB {
      //this is injected code 2
    }
   after addBAt {
      //this is injected code 3
   }
   after addOrMoveBAt{
    //this is injected code 4
   }
}
class B{

}
```

Injections 1 and 2 work, but 3 and 4 don't work. This is exactly the reason why I was saying we should  avoid differentiating custom and auto methods. Umple is growing and catching up with them is hard plus we can easily miss stuff (anyhow, one general solution would be a guarantee for the whole life).

**Comment by Shikib** [comment]
Regarding your code example. I briefly looked into the issue just now. It doesn't seem to have anything to do with custom methods or the injection code being incorrect. The issue seems to be that there is no call to `getApplicableCodeInjections` for the addAtMethod or the addOrMoveAt generated methods. 

For example for the addMethod, we have the following lines of code which allow injections into those methods to occur (this is in the UmpleTL btw).

```
attribute_Set_All.ump:77:      String customAddPrefixCode = GeneratorHelper.toCode(uClass.getApplicableCodeInjections("before", gen.translate("addMethod",av)));
attribute_Set_All.ump:78:      String customAddPostfixCode = GeneratorHelper.toCode(uClass.getApplicableCodeInjections("after", gen.translate("addMethod",av)));

```

However no such code exists for the other two methods. I think somebody may have accidentally removed these at some point. This is unrelated to the fact that we're differentiating between custom/generated code injections though.

**Comment by vahdat-ab** [comment]
I wanted to indicate that people can easy remove some part of code if there is no solid test case. Furthermore, Umple might decide to have those methods after developing `after` and `before`. Therefore, people who developed, for example,  `addBAt` had not know about this feature in AOP. However, if the approach was like matching methods without paying attention to custom or auto, it would be able to detect any methods. For example, if we decide to add new auto generated methods, we need to modify again the code. However, having general solution would detect new ones automatically.
anyhow, let's fix these an focus on what I said later. :-)

**Comment by vahdat-ab** [comment]
I'm closing this issue but I would like to indicate that having AOP fetaures with `all`, `custom` and even commands without paramters for auto-generated are really confusing. Even I'm familiar with AOP but taking hard time to deal with it.
