### ISSUE TITLE
strange behavior of use statement

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#811]
Consider the following structure for Umple files:

```
Folder: ProjectFolder
      Folder f1:
             f11.ump
             f12.ump
      main.ump
```

main.ump

```
use /f1/f11.ump;

class A{

}
```

f11.ump

```
use f12.ump;

class B{

}
```

f12.ump

```
class C{

}
```

It shows the following error:

```
Error 1510 on line 1 of file "/f1/f11.ump":
File 'f12.ump' referred to in use statement was not found
```

**Comment by vahdat-ab** [comment]
@bitwizeshift I wonder if this can be because of refactoring?

**Comment by TimLethbridge** [comment]
try going back to one of the earlier releases and seeing what happens, the jars are in the github releases

**Comment by Nava2** [comment]
Additionally, you could `git bisect` until the regression happens.

**Comment by vahdat-ab** [comment]
It fails till the release umple_1.19.0.3287.jar
This relaese doesn't show the warnning but doesn't generate class C.
It again shows the warning in umple_1.18.0.3036.jar

**Comment by vahdat-ab** [comment]
Looks like it's an old bug

**Comment by AdamBJ** [comment]
@vahdat-ab Can this issue be closed now?
