### ISSUE TITLE
Umple doesn't react properly to definition of guards

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#819]
consider the following example:

```
class A{
 Boolean repeatCheck = false;
  status {
    s1{
        [repeatCheck()]-> s2;
        [repeatCheck()]-> s3;
    }
    s2{
    }
    s3{
    }
  }

  Boolean repeatCheck() {
    return true;
  }
}
```

In the generated code, Umple changes the name of `repeatCheck` to `getRepeatCheck()` and puts another parantheses (`getRepeatCheck()()`). Looks look It doesn't recognize the method and consider it as a variable.

```

  private boolean __autotransition1__()
  {
    boolean wasEventProcessed = false;

    Status aStatus = status;
    switch (aStatus)
    {
      case SENDING:
        if (getRepeatCheck()())
        {
          setStatus(Status.UPDATING);
          wasEventProcessed = true;
          break;
        }
        break;
      default:
        // Other states do respond to this event
    }

    return wasEventProcessed;
  }
```

**Comment by marc22alain** [comment]
This issue appears to be similar to #870. The class definition contains a field and a method with the same name, and the parser gets confused.

**Comment by vahdat-ab** [comment]
@tlaport4 Since our last meeting, I worked on this issue and found the solution. I created a branch and committed into it. The branch name is issue819. Please double check that it works and also write comprehensive test cases and then commit them to the branch. Afterward, you can make a PR. 
Another test case :-)
```
class A{
 Boolean repeatCheck = false;
  status {
    s1{
        [repeatCheck < repeatCheck(z)]-> s2;
    }
    s2{
    }
  }
  Boolean repeatCheck() {
    return true;
  }
}
```

**Comment by vahdat-ab** [comment]
This has been fixed by PR928
