### ISSUE TITLE
Test suite failing 

### ISSUE THREAD

**Issue by opeyemiAdesina** [umple/umple#821]
This is strange... Individual tests pass when executed independently... but these tests fail when tested as a suite. I observed this bizarre behavior after using the Multimap data structure from Guava libraries... 

What could be wrong?  What are the possible solutions?

**Comment by Nava2** [comment]
Do you have more context? What tests, errors, etc?

**Comment by opeyemiAdesina** [comment]
Okay, I am working on the NuSMV code generation from state machines. I made some modifications recently to the code generator to allow on-the-fly analysis of non-determinism... The modification includes a match-making algorithm to pair transitions (e.g. same source) to facilitate the generation of CTL properties for model checking.

The affected tests are in NuSMVTemplateTest but local to my machine...

**Comment by opeyemiAdesina** [comment]
Here is a screen shot of the failing tests...
![screenshot from 2016-04-19 11 19 13](https://cloud.githubusercontent.com/assets/7153816/14644592/97673c02-0620-11e6-9af9-97f451b96789.png)

**Comment by opeyemiAdesina** [comment]
I have been able to localized the problem. From the **dist** directory, two compilers (umple.jar and umple-1.23.0-3bd2bc7.jar) are being produced simultaneously or within an insignificant time difference. 

The first compiler (umple.jar) works perfectly and generate a reasonable output but the second compiler throws **ClassNotFoundException** when used at the command line. In particular, the following is the resulting error:

java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
    at cruise.umple.compiler.NuSMVGenerator.generate(Generator_CodeNuSMV.ump:26)
    at cruise.umple.compiler.UmpleModel.generate(UmpleModel.java:1310)
    at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1064)
    at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1242)
    at cruise.umple.UmpleConsoleMain.runConsole(UmpleConsoleMain.java:109)
    at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:151)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 6 more 

From my observation, it appears Umpleonline and travis build use the second compiler. I observed this from the build done via travis this morning and the local Umpleonline server on my machine (see attached picture). The tests are probably failing because 

Relevant questions include:
1. Why the difference in behaviors of these two compilers since there times of creation is the same?
2. Are the build processes or paths different in both cases?

![screenshot from 2016-04-25 11 43 11](https://cloud.githubusercontent.com/assets/7153816/14789542/0f7ae07c-0adb-11e6-8795-38dbc16badfa.png)

**Comment by Nava2** [comment]
Is Guava being brought in by Ivy? The Jar needs to be on your classpath when the tests are run. 

Not sure why the execution fails but compiling passes. That'll be to do with your classpath. The classpath shipped with the compiler Jars should be identical and uses the classpath that Ivy exports.

**Comment by opeyemiAdesina** [comment]
Will you be able to experiment with this path so that we conclude whether
it is a path issue or not?

On Mon, Apr 25, 2016 at 12:12 PM, Kevin Brightwell <notifications@github.com

**Comment by Nava2** [comment]
No, not right now, sorry. 

You could check those though and it would discern what's happening. If memory serves, Google signs their Jars so we can't "repackage" Guava into the Umple Jar.

**Comment by TimLethbridge** [comment]
Only one compiler is produced. The umple.jar is a symbolic link only (and it is produced only on Linux and Mac) to facilitate running shell scripts that do not need to know the name of the latest release.

So it sounds as though the code you are producing/working with is making some kind of incorrect assumption regarding a path somewhere (e.g. a path to a file being used while testing).

**Comment by opeyemiAdesina** [comment]
But this is the error message I obtained when I used the jar for compilation at the command line. This is in fact confusing... 

![screenshot from 2016-04-26 10_52_52](https://cloud.githubusercontent.com/assets/7153816/14822634/64da9d9c-0b9d-11e6-9d6e-607b004d9f71.png)
