### ISSUE TITLE
Wrong generated code when a class implements an interface and has a queued or pooled state machine

### ISSUE THREAD

**Issue by amidzak** [umple/umple#833]
When a class has a "queued" or "pooled" state machine, In the generated code the class implements "Runnable". When the class also implements another interface the generated code for defining the class is wrong.
For example:

```
interface X{}
class Y{
        isA X;
        pooled sm{
                s1{
                        e->s1; 
                }
        }
}
```

The generated code for defining the class is:
`public class Y implements X implements Runnable{`

It should be
`public class Y implements X, Runnable{`

**Comment by TimLethbridge** [comment]
Another good catch ... again, I suggest you fix this yourself, Should not be hard. Remember to add a test.
