### ISSUE TITLE
Generator folder is still called src-gen-jet

### ISSUE THREAD

**Issue by amidzak** [umple/umple#837]
Although we don not use Jet for code generation, the generated codes for code generations are put in a folder called "src-gen-jet".

**Comment by TimLethbridge** [comment]
Yes. This is a trivial fix to be done. We just have to a) Change all the build script references from src-gen-jet to src-gen-umpletl; b) make sure that  this file is in ,gitignore and that src-gen-jet is removed from .gitignore (the directory should not be saved as it should be built every time). @amidzak why don't you issue a pr for this?

**Comment by TimLethbridge** [comment]
This has been dealt with
