### ISSUE TITLE
Singleton class should not be inherited from

### ISSUE THREAD

**Issue by amidzak** [umple/umple#841]
In Umple, It is allowed for a class to be inherited from a singleton class. Since the singleton class has a private constructor, and Java does not allow a class to extend a class with private constructor, the generated code is wrong.
`class X{
   singleton;
}
class Y{
  isA X;
}
`
even if we define the class "Y" it is also wrong.
`class X{
   singleton;
}
class Y{
singleton;
  isA X;
}
`
The error is the java code "extends":
`public class Y extends X{`

There are two solutions:
1: Not allowing inheritance of singleton classes by showing an error,
2: Making the constructor of a singleton class "protected" instead of "private" and also forcing the inherited classes to also be singleton. This means children inherit the singleton feature of the parent.

**Comment by TimLethbridge** [comment]
It makes total sense that there should never be allowed to be a subclass of a singleton class. Good catch
