### ISSUE TITLE
wrong code generation for guards because of misinterpreting method calls

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#870]
Consider the following code:

```
class CrFwOutCmp{
    Boolean getData = false;
    Boolean data(){
        return true;
    } 
    sm{
        so{
            go [getData()] -> so;
        }
    }
}
```

The generated code for event `go` is as follows.

```
public boolean go()
  {
    boolean wasEventProcessed = false;

    Sm aSm = sm;
    switch (aSm)
    {
      case so:
        if (getGetData()())
        {
          setSm(Sm.so);
          wasEventProcessed = true;
          break;
        }
        break;
      default:
        // Other states do respond to this event
    }

    return wasEventProcessed;
  }
```

Check this code out `if (getGetData()())`. The method is considered as an attribute and it's replaced with its `get` method. This is wrong because the code meant the method.

**Comment by tlaport4** [comment]
After fixing issue #819, it produces the following code:
```
public boolean go()
  {
    boolean wasEventProcessed = false;

    Sm aSm = sm;
    switch (aSm)
    {
      case so:
        if (getData())
        {
          setSm(Sm.so);
          wasEventProcessed = true;
          break;
        }
        break;
      default:
        // Other states do respond to this event
    }

    return wasEventProcessed;
  }
```

So, it now uses the method getData() as stated in the umple code. However, this method isn't defined and it doesn't actually exist. Is this how it should be?

**Comment by vahdat-ab** [comment]
Yes, it's been fixed. It would be good to show a warning regarding this case. I mean, if there is a method called in the guard and there is not implementation for it inside its superclasses, interfaces, traits, and other events related to state machines then a warning must be raised. It can be considered as an error as well.

**Comment by TimLethbridge** [comment]
Methods as well cal call other methods that may not exist. These are detected by the target language compiler. I think it is best to leave this to the target language compiler too. There are just too many cases to check otherwise.
