### ISSUE TITLE
Expired server certificate of UmpleOnline

### ISSUE THREAD

**Issue by jokrugel** [umple/umple#876]
## Brief Description

The certificate of the UmpleOnline server expired on July 6th. Connections with HTTPS are therefore not possible anymore.
## Minimum Steps to Reproduce

Visit https://cruise.eecs.uottawa.ca/umpleonline/

Btw: Thanks for the really helpful tool!

**Comment by TimLethbridge** [comment]
Thanks for the heads up. We have now replaced the certificate.

Tim

> On Jul 10, 2016, at 05:14, jokrugel notifications@github.com wrote:
> 
> Brief Description
> 
> The certificate of the UmpleOnline server expired on July 6th. Connections with HTTPS are therefore not possible anymore.
> 
> Minimum Steps to Reproduce
> 
> Visit https://cruise.eecs.uottawa.ca/umpleonline/ https://cruise.eecs.uottawa.ca/umpleonline/
> Btw: Thanks for the really helpful tool!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/umple/umple/issues/876, or mute the thread https://github.com/notifications/unsubscribe/AAdP_gt_0xJDe-H1rm4mRp74xRtQ9--aks5qULf5gaJpZM4JIzBQ.

Timothy C. Lethbridge, PhD, P.Eng., I.S.P., CSDP
Professor of Software Engineering and Computer Science
Faculté de genie / Faculty of Engineering
Université d'Ottawa / University of Ottawa
Tel: 613-562-5800x6685   Fax: 613-562-5664    Mobile: 613-252-1850
http://www.site.uottawa.ca/~tcl

**Comment by TimLethbridge** [comment]
The certificat has been replaced by our IT staff
