### ISSUE TITLE
adding automatic build for new Umple Eclipse plugin

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#877]
Hi,

I have developed a new Umple eclipse plugin which is not based on xText. It uses the basic elements of Eclipse.
Currently it works (even though it's not perfect), but we need to add its building process to the Umple's automatic building process.
I'm not so much familiar with the process so need help. I really appreciate if someone helps or takes cares of this task. I'll be able to work with that person continuously to finish the integration.

**Comment by vahdat-ab** [comment]
@TimLethbridge  @Nava2 @mgarzon @aforward @opeyemiAdesina

**Comment by TimLethbridge** [comment]
If I wasn't about to head off on vacation in two days, I might tackle this. It looks fairly simple. Note that on the cruise control server, there is the extra deployment step to move it into the cruise home directory that I will likely have to automate after the build has run.

**Comment by vahdat-ab** [comment]
documenting the steps
**Requirements**: we need to have eclipse in the local machine or fetch it online.

1) Copying the latest version of Umple from the folder `dist` to the folder `org.cruise.umple.eclipse.plugin` and then renaming it to `umple.jar`
2) Modify the version of plugin based on the current verison. we need to change the version of feature as well. ???
3) build the plugin with this script:
`java -jar <eclipse-installation-path>\plugins\org.eclipse.equinox.launcher_<version><qualifier>.jar -application org.eclipse.ant.core.antRunner -buildfile org.cruise.umple.eclipse.plugin.build.xml`
**Note:** build.xml is generated automatically by Eclipse. so the process is easy.
**Note** we need to build the feature and update website to see the correct reflection.
4) This will generate the plugin inside the folder `org.cruise.umple.eclipse.plugin`
5) Delete the files and folders from the folder `org.cruise.umple.eclipse.plugin`
        a) file -> `umple.jar`
        b) file -> `@dot.log`
        c) folder -> `@dot`
6) copy the plugin inside the folder `C:\umple\org.cruise.umple.eclipse.plugin.update.site\plugins`

**Comment by ahochheiden** [comment]
Closing this issue as per Vahdat's recommendation. It will be resolved with the transition to Gradle (https://github.com/umple/umple/issues/751) as adding it to Ant when we're going to replace Ant is unnecessary.
