### ISSUE TITLE
build<Role> might be a better name than add<Role> associationClass entities

### ISSUE THREAD

**Issue by kellerapps** [umple/umple#878]
## Brief Description

Association classes generate two methods named add<Role>(). One of them is a factory while the other updates the links. build<Role> might be a better name for the factory. Or maybe it should call the linker add<Role> after construction.
## Minimum Steps to Reproduce

```
class Person {}
class Place {}
associationClass Visit {
  Time when;
  * Person visitor -- * Place visitedPlace;
}
```
## Expected Result

```
public Visit buildVisit(Time aWhen, Person aVisitor) { return new Visit(aWhen, aVisitor, this); }

public Visit addVisit(Time aWhen, Person aVisitor) { 
  Visit x = new Visit(aWhen, aVisitor, this); 
  addVisit(x);
  return x;
}
```
## Actual Result

```
public Visit buildVisit(Time aWhen, Person aVisitor) { return new Visit(aWhen, aVisitor, this); }
```

**Comment by TimLethbridge** [comment]
I don't think I agree with this. The term name 'add' is consistent with associations in general. I think this is of minor importance too. I will leave it as an issue in case others wish to discuss.
