### ISSUE TITLE
Add OCL-type constraints

### ISSUE THREAD

**Issue by Nava2** [umple/umple#89]
Originally reported on Google Code with ID 187
Owned by `redeyedmars`

---

OCL constraints would be built on top of the before and after capability that already
exists in Umple

---

Reported by @umple on 2011-06-25 02:53:40

**Comment by Nava2** [comment]
This should start with a small subset of OCL. The idea is that constraints should be
added that will be injected into any method (such as a setX method) that affects the
value of an attribute or a link of an association.
1. Limit the values of attributes to a certain range or set of values or, for strings,
   a certain pattern. The range could be dynamic based on some calculation, and should
   be able to navigate associations (like OCL does).
2. Limit what can be added as an association. I.e. checking the object about to be
   set or adde in an association to determine whether it fulfils a certain criterion.

Thorough testing needs to be done, including adding testbed tests. The user manual
also needs to be updated.

---

Reported by @umple on 2012-01-13 22:35:42

**Comment by Nava2** [comment]
See http://code.google.com/p/umple/wiki/OCLConstraints for the draft specifications.

---

Reported by @umple on 2012-03-27 15:55:23

**Comment by Nava2** [comment]
Some work has been started to implement this. Initial syntax would simply be initially
[attrib < 10] where there would be an operator and a constant. This would inject a
'before' statement to check before an attribute is set. The grammar has been prepared,
but that is as far as this task has been taken.

---

Reported by @umple on 2012-06-15 14:16:21
- **Status changed**: `Started`
- **Labels added**: Priority-High, Diffic-Med
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2012-10-12 15:24:34
- **Owner changed**: `christopher.hogan49`
- **Labels added**: ucosp

**Comment by Nava2** [comment]
This feature has now been partly done. You can inject a constraint such as [age > 5]
into a class, where age is an attribute, and the setter will fail on attempts to set
age <= 5.

However, there are still many things to do. 

Important: It is still possible to bypass the constraint in a constructor. There needs
to be a code injection before the constructor to reject attempts to construct an object
that has an invalid attribute. 

We also need to increase the set of constraints that are allowed. THis can be done
incrementally. The hard work is done.

Most likely will need to make some fixes to Ruby and PhP generation because it currently
requires the constraint to have parens around them. See my java fix in r2313

---

Reported by @umple on 2012-12-20 03:55:30

**Comment by Nava2** [comment]
This is being put back on the queue for UCOSP students to work on more in Jan-April
2013. We need to add a lot more test cases, to allow constraints relating to associations
and state machines, to raise errors when constraints are incorrect, and many other
improvements to constraints.

---

Reported by @umple on 2012-12-31 13:32:17
- **Owner removed**

**Comment by Nava2** [comment]
I am adding the tag 'constraints' to this. I am then going to file other issues related
to constraints. Please look at the entire list of constraints issues.

---

Reported by @umple on 2013-01-03 22:23:53
- **Labels added**: constraints

**Comment by Nava2** [comment]
Reported by @umple on 2013-01-30 13:57:49
- **Owner changed**: `quinlanjung`

**Comment by Nava2** [comment]
An ongoing issue, but Quinlan has done her part.

---

Reported by @umple on 2013-04-30 13:39:01
- **Owner removed**

**Comment by Nava2** [comment]
Reported by @umple on 2013-04-30 13:44:27
- **Labels added**: Priority-VHigh
- **Labels removed**: Priority-High

**Comment by Nava2** [comment]
Reported by `redeyedmars` on 2013-05-06 14:58:14
- **Labels removed**: ucosp

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-12 15:10:44
- **Owner changed**: `redeyedmars`

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-17 13:09:01
- **Labels added**: Type-ResearchGrad
- **Labels removed**: Type-ProjectUG

**Comment by Nava2** [comment]
Reported by @umple on 2014-04-14 14:20:16
- **Blocking**: #438

**Comment by TimLethbridge** [comment]
This issue is a longstanding issue. Constraints need to be continually evolved. I am lowering the priority, however as remaining work is enhancement.

**Comment by TimLethbridge** [comment]
I am closing this issue. Other issues can be raised about constraints as we expand them.
