### ISSUE TITLE
Where can i get the umple eclipse plugin?

### ISSUE THREAD

**Issue by txrnz** [umple/umple#892]
i am new to umple.I'm so confused when i read the umple manual. 
I can not find somewhere to download the eclipse plugin of ample.
can anybody tell me?

**Comment by Nava2** [comment]
It's currently not building so there is not somewhere to download it. 

However, if you're only after highlighting, you can check out the sublime grammar: [umple/umple.sublime](https://github.com/umple/umple.sublime).

**Comment by vahdat-ab** [comment]
The Umple plugin for Eclipse can be downloaded from the following link:
http://cruise.eecs.uottawa.ca/org.cruise.umple.eclipse.plugin.update.site/
It is a normal eclipse update site and you can install through the menu "Install new Software..."
If you get any issues feel free to ask for more details.
good luck.

**Comment by txrnz** [comment]
I'm very grateful for your help!@vahdat-ab

**Comment by TimLethbridge** [comment]
There is now a FAQ page. https://github.com/umple/umple/wiki/FAQ I have added this answer to that.
