### ISSUE TITLE
Add visit counter to UmpleOnline

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#893]
Add a visit counter to Umple online using the PhP code. 

The wording should be after 'Report an issue' and should say. "n visits since MMM 2016", where n is updated, and mmm is the month it was added.

I suggest using visit counter php code at http://justintadlock.com/web-design/counter
(Give him credit in a comment)

Why do this: It might build some excitement

**Comment by edmundluong** [comment]
I would absolutely love to work on this issue!

**Comment by vahdat-ab** [comment]
It might be beneficial to get benefits of some free websites that give more detailed statistical data. 
e.g. http://statcounter.com/

**Comment by vahdat-ab** [comment]
We need also keep a good track of all statistical data because in some point we will need to officially publish it.

**Comment by edmundluong** [comment]
Would some sort of web analytical software be of any use? I assume we cannot use Google Analytics as it is not open-source, but an open-source alternative such as [piwik](https://piwik.org/) could be interesting and give a lot of insight on the traffic coming to the website.

**Comment by Nava2** [comment]
Google Analytics is free, though. It can definitely be used. Also, it's a hosted solution so its less overhead to host it.

**Comment by TimLethbridge** [comment]
I don't want to load the server or client. One of these open source solutions might work if setup is lightweight and the amount of ucisp work is low. This is not a high priority. There are many high priority issues 

Timothy C Lethbridge
