### ISSUE TITLE
Minor typo in user manual

### ISSUE THREAD

**Issue by Fischercr** [umple/umple#894]
http://cruise.eecs.uottawa.ca/umple/DerivedAttributes.html

It says "you can specify at arbitrary expression."
It should say "an" instead of "at."

**Comment by vahdat-ab** [comment]
Thanks. It's fixed. Will be applied along with my other changes in my next commit.

**Comment by AdamBJ** [comment]
@vahdat-ab  Can this issue be closed?

**Comment by vahdat-ab** [comment]
Thanks @AdamBJ . I'm closing this.
