### ISSUE TITLE
when the methods view is selected attributes and class name changes revert back

### ISSUE THREAD

**Issue by Muxoid** [umple/umple#896]
There was no original comment on this issue. Could you please be a little specific?

Do you mean? i. You have edited an attribute in the class diagram, but have not pressed 'enter'. ii. You select the checkbox by 'Methods'. iii your changes to the attribute are reverted? If that is what you meant, it is simply that you didn't press enter.

**Comment by TimLethbridge** [comment]
Closing. I think if a user doesn't press enter it is not too huge a problem
