### ISSUE TITLE
Umple diagram and code updating

### ISSUE THREAD

**Issue by uneeb97** [umple/umple#897]
## Brief Description

The diagram isn't updating the code and vice versa. 
## Minimum Steps to Reproduce
1. Write code or make a diagram
## Expected Result

Getting either code or diagram generated based on what was initially made
## Actual Result

Nothing

**Comment by TimLethbridge** [comment]
The system was running slow just before an assignment was due. It has returned to normal. However this will be dealt with under issue #622 in the coming months
