### ISSUE TITLE
UmpleOnline source code in new tab behaves weirdly (Chrome OS X)

### ISSUE THREAD

**Issue by erickzhao** [umple/umple#902]
## Brief Description

This bug is occurring on Google Chrome Version 52.0.2743.116 (64-bit) on macOS Sierra when the browser window is maximized (i.e. it is its own desktop). Does not occur on Safari.
After generating Umple source code and using the resulting `about:blank` page to surf the web, Umple source code cannot be regenerated until that tab is closed.

(Sorry if this is too specific of a bug.)
## Minimum Steps to Reproduce
1. Use UmpleOnline on Chrome on Mac, and maximize the browser screen (i.e. create a new desktop with it).
2. Generate Umple source code (will appear in new tab instead of a new window because the browser screen is maximized).
3. Use that tab to navigate to any web page.
4. Attempt to generate Umple source code again.
## Expected Result

Umple source is generated in a separate new tab.
## Actual Result

The browser focuses on tab that the Umple code was previously generated in, and no code is generated.
## Labelling and Assigning

Component-UmpleOnline

**Comment by TimLethbridge** [comment]
A few observations: 1) By 'Generate Umple source code', the author means use 'Save Model' in UmpleOnline. 2) The still issue appears in Chrome (latest version) as of Nov 2017, 3) The issue doesn't require maximizing the browser.

**Comment by TimLethbridge** [comment]
Likely a super-quick solution that would simply requiring changing 'target=' tag in the URL to open in a new tab.

**Comment by TimLethbridge** [comment]
This behaviour is still present in 1.30.1 in Sept 2020. Relatively low priority though
