### ISSUE TITLE
Umpleonline Editable Class diagrams not showing methods specified by interfaces

### ISSUE THREAD

**Issue by marc22alain** [umple/umple#911]
## Brief Description

The Editable Diagram does not show the methods that are specified in an interface, while the GraphViz diagram does show the methods. The JSON file response from the server also contains no definition of the interface's methods. 

## Minimum Steps to Reproduce

Use as an example the class definitions found [here] (http://cruise.eecs.uottawa.ca/umple/interfaceDefinition.html)
1. Copy/paste the class definitions into an umpleonline text definitions window.
2. Select the "Editable Class" Diagram Type radio button and the "Methods" Show View checkbox.
3. Use the browser console to inspect the XHR response from the server.

## Expected Result

The "RegisterCapable" interface item should also display the following method: "+ registerForCourse(Course): Boolean".

The server response for the methods for the "RegisterCapable" interface item should be: `"methods": [{ "type" : "boolean", "name" : "registerForCourse", "parameters" : "Course", "visibility" : "", "isAbstract" : "true"}],`.

## Actual Result

There is no method information displayed with the "RegisterCapable" interface item.

The server response for the methods for the "RegisterCapable" interface item: `"methods": [],`

Note that the "GraphViz Class" Diagram Type does show this method description.

**Comment by TimLethbridge** [comment]
Here's another example

```
interface X {
  void m1();
}
```

**Comment by vash-evg** [comment]
While implementing the fix, I noticed that methods inside of the Interface are not identified as abstract.

**Comment by TimLethbridge** [comment]
All methods in interfaces are abstract, so I don't think anything special needs to be done.

**Comment by vash-evg** [comment]
The JSON I am getting is:
{"umpleClasses":[{"position": {"x": 268, "y": 30, "width": 109, "height": 45}, "attributes": [],"methods": [{ "type" : "void", "name" : "m", "parameters" : "", "visibility" : "", **"isAbstract" : "false"**}], "id": "X", "name": "X", "isAbstract": "false", "displayColor": "" , "isInterface": "true"}], "umpleAssociations":[] }]
  [/home/ev/Desktop/umple3/umple/umpleonline/ump/../ump/tmp938651/model.ump]

Should I assume this is correct behavior?

**Comment by TimLethbridge** [comment]
I would assume it is OK for now. I assume that this would be used to display an «abstract» steroetype, which would not be needed. So technically it might be incorrect that it says isAbstract is false, it is likely to break other stuff if we change it.
