### ISSUE TITLE
Remove unnecessary String variable "outputString" in generated Java code

### ISSUE THREAD

**Issue by AdamBJ** [umple/umple#947]
## Brief Description

When Umple Online generates the toString() method for Java code, it is often creating a unnecessary extra variable, `outputString`, as shown in the example below:

```
public String toString()
{
String outputString = "";
return super.toString() + "["+
"z" + ":" + getZ()+ "]"
+ outputString;
}
```

We should fix this issue, and check if it is occuring in other contexts (e.g. in other generated languages, outside of Umple Online).

## Minimum Steps to Reproduce

Look at the `toString()` method in the generated Java code associated with [this example from the Umple manual.](http://cruise.eecs.uottawa.ca/umpleonline/?example=manualexamples/LazyImmutableAttributes1)

## Expected Result

`outputString` should not be created nor used.

## Actual Result

`outputSting` is being created and used.

Omitting the build log output as this issue is occurring when using Umple Online.

## Assignees

I would like to look into this issue during the code sprint this coming weekend (January 20th-22nd).

**Comment by AdamBJ** [comment]
@vahdat-ab I've got a fix for this in my local repo. The problem is that there are about 200 template test cases that need to be changed to remove references to the extra string. I know Tim said to be careful when changing test cases, but I think in this case it should be ok?

**Comment by vahdat-ab** [comment]
yup. I would say check each one before deleting to see if you can find an exception :-)
