### ISSUE TITLE
Eliminate/investigate redundancy in generated get methods involving booleans

### ISSUE THREAD

**Issue by AdamBJ** [umple/umple#951]
## Brief Description

When  Umple Online generates Java based on the state machine in [this example from the manual](http://cruise.eecs.uottawa.ca/umpleonline/?example=manualexamples/BasicStateMachines2&diagramtype=state), redundant getter methods are generated for the `entranceClear` attribute. Currently, we're getting both of these methods:

```
public boolean getEntranceClear()
{
return entranceClear;
}
 
public boolean isEntranceClear()
{
return entranceClear;
}
```

It seems like overkill to have both of these, but removing one or the other might break existing implementations that use Umple. @TimLethbridge, @vahdat-ab mentioned you'd probably be the best person to make a decision on whether it's worthwhile to change what gets generated.

## Minimum Steps to Reproduce

Open the link in the description and generate Java code.

**Comment by TimLethbridge** [comment]
Originally we had just the 'is' for Booleans. But programming in Umple requires some remembering the rules, and a few people forgot, so we added the 'get'. We can't remove now; it would break code. So I am going to close
