### ISSUE TITLE
continuous-integration failure on Appveyor

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#979]
Appveyor is failing and it needs to be fixed.
The error it shows is
```
cinst ant 2>&1 | Out-Null
cinst php --version=5.6.29 2>&1 | Out-Null
Command exited with code 1
```

**Comment by TimLethbridge** [comment]
I tried changing the version of Php but it didn't work. We have to figure out how other projects get the latest php in Appveyor

**Comment by vahdat-ab** [comment]
@Nava2  any idea?

**Comment by Nava2** [comment]
Zero idea, @vahdat-ab. I'm sorry. I haven't time right now to debug either. I think @TimLethbridge has the right idea.
